[package]
name = "arkdeck-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "arkdeck"
path = "src/main.rs"

[dependencies]
arkdeck-contract.workspace = true
arkdeck-client.workspace = true
arkdeck-platform.workspace = true
serde_json.workspace = true

[lints]
workspace = true
