// Generated by rust/scripts/generate-contract.py. Do not edit.

pub const PROTOCOL_VERSION: &str = "1.0.0";
pub const MAX_REQUEST_BYTES: usize = 4194304;
pub const MAX_RESPONSE_BYTES: usize = 8388608;
pub const CONTRACT_IDENTITY: &str =
    "eb53eab3d4a05efddf7e1d3190d899aa82f800c5af82528f60f935fb23e48bc2";
pub const SWIFT_BASELINE: &str = include_str!("../../../../spec/baselines/swift-single-v1.json");
pub const CONTRACT_INPUTS: &str = SWIFT_BASELINE;
pub const METHODS: &[&str] = &[
    "agent.abandon",
    "agent.list",
    "agent.resume",
    "agent.run",
    "agent.status",
    "artifact.export",
    "artifact.import.abort",
    "artifact.import.append",
    "artifact.import.begin",
    "artifact.import.commit",
    "artifact.import.inspect",
    "artifact.import.inspection",
    "artifact.import.list",
    "artifact.import.release",
    "artifact.inspect",
    "artifact.list",
    "artifact.quota",
    "artifact.read",
    "capability.inspect",
    "capability.list",
    "cleanupDebt.continue",
    "cleanupDebt.list",
    "control-action.list",
    "control-action.reconcile",
    "control-action.show",
    "debug.evaluate",
    "debug.probe",
    "debug.start",
    "debug.status",
    "debug.template.run",
    "device.display-name.clear",
    "device.display-name.set",
    "device.observations",
    "doctor",
    "flash.bind-current-loader",
    "flash.bootloader-status",
    "flash.device-access",
    "flash.lanePlanPreview",
    "flash.prerequisites",
    "flash.reconcile-alias",
    "health",
    "history.filter.delete",
    "history.filter.list",
    "history.filter.save",
    "human-action.list",
    "human-action.resume",
    "human-action.show",
    "job.cancel",
    "job.events",
    "job.evidence",
    "job.list",
    "job.plan",
    "job.reconcile",
    "job.result",
    "job.run",
    "job.show",
    "job.status",
    "job.submit",
    "job.timeline",
    "operation.describe",
    "operation.list",
    "recovery.flash-invocation.list",
    "runtime.bundle.inspect",
    "runtime.bundle.list",
    "runtime.hdc.impact-preview",
    "runtime.hdc.restart",
    "runtime.hdc.status",
    "runtime.storage.policy",
    "runtime.storage.root",
    "runtime.storage.status",
    "runtime.tool.inspect",
    "runtime.tool.register",
    "runtime.tool.select",
    "session.cleanup.apply",
    "session.cleanup.preview",
    "session.export.apply",
    "session.export.preview",
    "session.list",
    "session.pin",
    "session.show",
    "session.unpin",
    "target.adopt",
    "target.availability",
    "target.display-name.clear",
    "target.display-name.set",
    "target.list",
    "target.show",
    "trace.cache.purge",
    "trace.cache.status",
    "trace.inspect",
    "trace.probe",
    "workspace.preset.list",
    "workspace.preset.register",
    "workspace.preset.remove",
    "workspace.preset.show",
    "workspace.preset.update",
    "workspace.project.list",
    "workspace.project.register",
    "workspace.project.remove",
    "workspace.project.show",
    "workspace.project.update",
];

pub const METHOD_SCHEMAS: &[(&str, &str)] = &[
    (
        "agent.abandon",
        include_str!("../../../../spec/control/methods/agent.abandon.json"),
    ),
    (
        "agent.list",
        include_str!("../../../../spec/control/methods/agent.list.json"),
    ),
    (
        "agent.resume",
        include_str!("../../../../spec/control/methods/agent.resume.json"),
    ),
    (
        "agent.run",
        include_str!("../../../../spec/control/methods/agent.run.json"),
    ),
    (
        "agent.status",
        include_str!("../../../../spec/control/methods/agent.status.json"),
    ),
    (
        "artifact.export",
        include_str!("../../../../spec/control/methods/artifact.export.json"),
    ),
    (
        "artifact.import.abort",
        include_str!("../../../../spec/control/methods/artifact.import.abort.json"),
    ),
    (
        "artifact.import.append",
        include_str!("../../../../spec/control/methods/artifact.import.append.json"),
    ),
    (
        "artifact.import.begin",
        include_str!("../../../../spec/control/methods/artifact.import.begin.json"),
    ),
    (
        "artifact.import.commit",
        include_str!("../../../../spec/control/methods/artifact.import.commit.json"),
    ),
    (
        "artifact.import.inspect",
        include_str!("../../../../spec/control/methods/artifact.import.inspect.json"),
    ),
    (
        "artifact.import.inspection",
        include_str!("../../../../spec/control/methods/artifact.import.inspection.json"),
    ),
    (
        "artifact.import.list",
        include_str!("../../../../spec/control/methods/artifact.import.list.json"),
    ),
    (
        "artifact.import.release",
        include_str!("../../../../spec/control/methods/artifact.import.release.json"),
    ),
    (
        "artifact.inspect",
        include_str!("../../../../spec/control/methods/artifact.inspect.json"),
    ),
    (
        "artifact.list",
        include_str!("../../../../spec/control/methods/artifact.list.json"),
    ),
    (
        "artifact.quota",
        include_str!("../../../../spec/control/methods/artifact.quota.json"),
    ),
    (
        "artifact.read",
        include_str!("../../../../spec/control/methods/artifact.read.json"),
    ),
    (
        "capability.inspect",
        include_str!("../../../../spec/control/methods/capability.inspect.json"),
    ),
    (
        "capability.list",
        include_str!("../../../../spec/control/methods/capability.list.json"),
    ),
    (
        "cleanupDebt.continue",
        include_str!("../../../../spec/control/methods/cleanupDebt.continue.json"),
    ),
    (
        "cleanupDebt.list",
        include_str!("../../../../spec/control/methods/cleanupDebt.list.json"),
    ),
    (
        "control-action.list",
        include_str!("../../../../spec/control/methods/control-action.list.json"),
    ),
    (
        "control-action.reconcile",
        include_str!("../../../../spec/control/methods/control-action.reconcile.json"),
    ),
    (
        "control-action.show",
        include_str!("../../../../spec/control/methods/control-action.show.json"),
    ),
    (
        "debug.evaluate",
        include_str!("../../../../spec/control/methods/debug.evaluate.json"),
    ),
    (
        "debug.probe",
        include_str!("../../../../spec/control/methods/debug.probe.json"),
    ),
    (
        "debug.start",
        include_str!("../../../../spec/control/methods/debug.start.json"),
    ),
    (
        "debug.status",
        include_str!("../../../../spec/control/methods/debug.status.json"),
    ),
    (
        "debug.template.run",
        include_str!("../../../../spec/control/methods/debug.template.run.json"),
    ),
    (
        "device.display-name.clear",
        include_str!("../../../../spec/control/methods/device.display-name.clear.json"),
    ),
    (
        "device.display-name.set",
        include_str!("../../../../spec/control/methods/device.display-name.set.json"),
    ),
    (
        "device.observations",
        include_str!("../../../../spec/control/methods/device.observations.json"),
    ),
    (
        "doctor",
        include_str!("../../../../spec/control/methods/doctor.json"),
    ),
    (
        "flash.bind-current-loader",
        include_str!("../../../../spec/control/methods/flash.bind-current-loader.json"),
    ),
    (
        "flash.bootloader-status",
        include_str!("../../../../spec/control/methods/flash.bootloader-status.json"),
    ),
    (
        "flash.device-access",
        include_str!("../../../../spec/control/methods/flash.device-access.json"),
    ),
    (
        "flash.lanePlanPreview",
        include_str!("../../../../spec/control/methods/flash.lanePlanPreview.json"),
    ),
    (
        "flash.prerequisites",
        include_str!("../../../../spec/control/methods/flash.prerequisites.json"),
    ),
    (
        "flash.reconcile-alias",
        include_str!("../../../../spec/control/methods/flash.reconcile-alias.json"),
    ),
    (
        "health",
        include_str!("../../../../spec/control/methods/health.json"),
    ),
    (
        "history.filter.delete",
        include_str!("../../../../spec/control/methods/history.filter.delete.json"),
    ),
    (
        "history.filter.list",
        include_str!("../../../../spec/control/methods/history.filter.list.json"),
    ),
    (
        "history.filter.save",
        include_str!("../../../../spec/control/methods/history.filter.save.json"),
    ),
    (
        "human-action.list",
        include_str!("../../../../spec/control/methods/human-action.list.json"),
    ),
    (
        "human-action.resume",
        include_str!("../../../../spec/control/methods/human-action.resume.json"),
    ),
    (
        "human-action.show",
        include_str!("../../../../spec/control/methods/human-action.show.json"),
    ),
    (
        "job.cancel",
        include_str!("../../../../spec/control/methods/job.cancel.json"),
    ),
    (
        "job.events",
        include_str!("../../../../spec/control/methods/job.events.json"),
    ),
    (
        "job.evidence",
        include_str!("../../../../spec/control/methods/job.evidence.json"),
    ),
    (
        "job.list",
        include_str!("../../../../spec/control/methods/job.list.json"),
    ),
    (
        "job.plan",
        include_str!("../../../../spec/control/methods/job.plan.json"),
    ),
    (
        "job.reconcile",
        include_str!("../../../../spec/control/methods/job.reconcile.json"),
    ),
    (
        "job.result",
        include_str!("../../../../spec/control/methods/job.result.json"),
    ),
    (
        "job.run",
        include_str!("../../../../spec/control/methods/job.run.json"),
    ),
    (
        "job.show",
        include_str!("../../../../spec/control/methods/job.show.json"),
    ),
    (
        "job.status",
        include_str!("../../../../spec/control/methods/job.status.json"),
    ),
    (
        "job.submit",
        include_str!("../../../../spec/control/methods/job.submit.json"),
    ),
    (
        "job.timeline",
        include_str!("../../../../spec/control/methods/job.timeline.json"),
    ),
    (
        "operation.describe",
        include_str!("../../../../spec/control/methods/operation.describe.json"),
    ),
    (
        "operation.list",
        include_str!("../../../../spec/control/methods/operation.list.json"),
    ),
    (
        "recovery.flash-invocation.list",
        include_str!("../../../../spec/control/methods/recovery.flash-invocation.list.json"),
    ),
    (
        "runtime.bundle.inspect",
        include_str!("../../../../spec/control/methods/runtime.bundle.inspect.json"),
    ),
    (
        "runtime.bundle.list",
        include_str!("../../../../spec/control/methods/runtime.bundle.list.json"),
    ),
    (
        "runtime.hdc.impact-preview",
        include_str!("../../../../spec/control/methods/runtime.hdc.impact-preview.json"),
    ),
    (
        "runtime.hdc.restart",
        include_str!("../../../../spec/control/methods/runtime.hdc.restart.json"),
    ),
    (
        "runtime.hdc.status",
        include_str!("../../../../spec/control/methods/runtime.hdc.status.json"),
    ),
    (
        "runtime.storage.policy",
        include_str!("../../../../spec/control/methods/runtime.storage.policy.json"),
    ),
    (
        "runtime.storage.root",
        include_str!("../../../../spec/control/methods/runtime.storage.root.json"),
    ),
    (
        "runtime.storage.status",
        include_str!("../../../../spec/control/methods/runtime.storage.status.json"),
    ),
    (
        "runtime.tool.inspect",
        include_str!("../../../../spec/control/methods/runtime.tool.inspect.json"),
    ),
    (
        "runtime.tool.register",
        include_str!("../../../../spec/control/methods/runtime.tool.register.json"),
    ),
    (
        "runtime.tool.select",
        include_str!("../../../../spec/control/methods/runtime.tool.select.json"),
    ),
    (
        "session.cleanup.apply",
        include_str!("../../../../spec/control/methods/session.cleanup.apply.json"),
    ),
    (
        "session.cleanup.preview",
        include_str!("../../../../spec/control/methods/session.cleanup.preview.json"),
    ),
    (
        "session.export.apply",
        include_str!("../../../../spec/control/methods/session.export.apply.json"),
    ),
    (
        "session.export.preview",
        include_str!("../../../../spec/control/methods/session.export.preview.json"),
    ),
    (
        "session.list",
        include_str!("../../../../spec/control/methods/session.list.json"),
    ),
    (
        "session.pin",
        include_str!("../../../../spec/control/methods/session.pin.json"),
    ),
    (
        "session.show",
        include_str!("../../../../spec/control/methods/session.show.json"),
    ),
    (
        "session.unpin",
        include_str!("../../../../spec/control/methods/session.unpin.json"),
    ),
    (
        "target.adopt",
        include_str!("../../../../spec/control/methods/target.adopt.json"),
    ),
    (
        "target.availability",
        include_str!("../../../../spec/control/methods/target.availability.json"),
    ),
    (
        "target.display-name.clear",
        include_str!("../../../../spec/control/methods/target.display-name.clear.json"),
    ),
    (
        "target.display-name.set",
        include_str!("../../../../spec/control/methods/target.display-name.set.json"),
    ),
    (
        "target.list",
        include_str!("../../../../spec/control/methods/target.list.json"),
    ),
    (
        "target.show",
        include_str!("../../../../spec/control/methods/target.show.json"),
    ),
    (
        "trace.cache.purge",
        include_str!("../../../../spec/control/methods/trace.cache.purge.json"),
    ),
    (
        "trace.cache.status",
        include_str!("../../../../spec/control/methods/trace.cache.status.json"),
    ),
    (
        "trace.inspect",
        include_str!("../../../../spec/control/methods/trace.inspect.json"),
    ),
    (
        "trace.probe",
        include_str!("../../../../spec/control/methods/trace.probe.json"),
    ),
    (
        "workspace.preset.list",
        include_str!("../../../../spec/control/methods/workspace.preset.list.json"),
    ),
    (
        "workspace.preset.register",
        include_str!("../../../../spec/control/methods/workspace.preset.register.json"),
    ),
    (
        "workspace.preset.remove",
        include_str!("../../../../spec/control/methods/workspace.preset.remove.json"),
    ),
    (
        "workspace.preset.show",
        include_str!("../../../../spec/control/methods/workspace.preset.show.json"),
    ),
    (
        "workspace.preset.update",
        include_str!("../../../../spec/control/methods/workspace.preset.update.json"),
    ),
    (
        "workspace.project.list",
        include_str!("../../../../spec/control/methods/workspace.project.list.json"),
    ),
    (
        "workspace.project.register",
        include_str!("../../../../spec/control/methods/workspace.project.register.json"),
    ),
    (
        "workspace.project.remove",
        include_str!("../../../../spec/control/methods/workspace.project.remove.json"),
    ),
    (
        "workspace.project.show",
        include_str!("../../../../spec/control/methods/workspace.project.show.json"),
    ),
    (
        "workspace.project.update",
        include_str!("../../../../spec/control/methods/workspace.project.update.json"),
    ),
];

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct HealthRequest {
    #[serde(rename = "padding", skip_serializing_if = "Option::is_none")]
    pub padding: Option<String>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct HealthResult {
    #[serde(rename = "catalogDigest")]
    pub catalog_digest: String,
    #[serde(rename = "contractIdentity")]
    pub contract_identity: String,
    #[serde(rename = "protocolVersion")]
    pub protocol_version: String,
    #[serde(rename = "providers")]
    pub providers: Vec<String>,
    #[serde(rename = "publishedMethods")]
    pub published_methods: Vec<String>,
    #[serde(rename = "status")]
    pub status: String,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DoctorRequest {
    #[serde(rename = "deep", skip_serializing_if = "Option::is_none")]
    pub deep: Option<serde_json::Value>,
    #[serde(rename = "unknown", skip_serializing_if = "Option::is_none")]
    pub unknown: Option<bool>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DoctorResultChecksCatalog {
    #[serde(rename = "availableOperationCount")]
    pub available_operation_count: i64,
    #[serde(rename = "digest")]
    pub digest: String,
    #[serde(rename = "operationCount")]
    pub operation_count: i64,
    #[serde(rename = "unavailableOperationCount")]
    pub unavailable_operation_count: i64,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DoctorResultChecksHdc {
    #[serde(rename = "availability")]
    pub availability: String,
    #[serde(rename = "checked")]
    pub checked: bool,
    #[serde(rename = "configured")]
    pub configured: bool,
    #[serde(rename = "ownership")]
    pub ownership: String,
    #[serde(rename = "reasonCode")]
    pub reason_code: String,
    #[serde(rename = "serverHealth")]
    pub server_health: String,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DoctorResultChecksProviders {
    #[serde(rename = "registered")]
    pub registered: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DoctorResultChecksRecovery {
    #[serde(rename = "checked")]
    pub checked: bool,
    #[serde(
        rename = "outstandingCleanupCount",
        deserialize_with = "crate::required_nullable"
    )]
    pub outstanding_cleanup_count: Option<i64>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DoctorResultChecksRuntime {
    #[serde(rename = "protocolVersion")]
    pub protocol_version: String,
    #[serde(rename = "runtimeRequestSchemaVersion")]
    pub runtime_request_schema_version: String,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DoctorResultChecksStorageRuntimeArtifacts {
    #[serde(rename = "checked")]
    pub checked: bool,
    #[serde(rename = "configured")]
    pub configured: bool,
    #[serde(
        rename = "remainingBytes",
        deserialize_with = "crate::required_nullable"
    )]
    pub remaining_bytes: Option<i64>,
    #[serde(rename = "totalBytes", deserialize_with = "crate::required_nullable")]
    pub total_bytes: Option<i64>,
    #[serde(rename = "usedBytes", deserialize_with = "crate::required_nullable")]
    pub used_bytes: Option<i64>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DoctorResultChecksStorageSessionOutput {
    #[serde(rename = "availability")]
    pub availability: String,
    #[serde(rename = "checked")]
    pub checked: bool,
    #[serde(rename = "reasonCode")]
    pub reason_code: String,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DoctorResultChecksStorage {
    #[serde(rename = "runtimeArtifacts")]
    pub runtime_artifacts: DoctorResultChecksStorageRuntimeArtifacts,
    #[serde(rename = "sessionOutput")]
    pub session_output: DoctorResultChecksStorageSessionOutput,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DoctorResultChecksTarget {
    #[serde(
        rename = "adoptedTargetCount",
        deserialize_with = "crate::required_nullable"
    )]
    pub adopted_target_count: Option<i64>,
    #[serde(rename = "bootstrapConfigured")]
    pub bootstrap_configured: bool,
    #[serde(rename = "configured")]
    pub configured: bool,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DoctorResultChecks {
    #[serde(rename = "catalog")]
    pub catalog: DoctorResultChecksCatalog,
    #[serde(rename = "hdc")]
    pub hdc: DoctorResultChecksHdc,
    #[serde(rename = "providers")]
    pub providers: DoctorResultChecksProviders,
    #[serde(rename = "recovery")]
    pub recovery: DoctorResultChecksRecovery,
    #[serde(rename = "runtime")]
    pub runtime: DoctorResultChecksRuntime,
    #[serde(rename = "storage")]
    pub storage: DoctorResultChecksStorage,
    #[serde(rename = "target")]
    pub target: DoctorResultChecksTarget,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DoctorResultFindingCounts {
    #[serde(rename = "blocker")]
    pub blocker: i64,
    #[serde(rename = "info")]
    pub info: i64,
    #[serde(rename = "warning")]
    pub warning: i64,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DoctorResultFindingsItemDetails {
    #[serde(rename = "adoptedTargetCount", skip_serializing_if = "Option::is_none")]
    pub adopted_target_count: Option<i64>,
    #[serde(
        rename = "availableOperationCount",
        skip_serializing_if = "Option::is_none"
    )]
    pub available_operation_count: Option<i64>,
    #[serde(
        rename = "outstandingCleanupCount",
        skip_serializing_if = "Option::is_none"
    )]
    pub outstanding_cleanup_count: Option<i64>,
    #[serde(rename = "providerCount", skip_serializing_if = "Option::is_none")]
    pub provider_count: Option<i64>,
    #[serde(
        rename = "unavailableOperationCount",
        skip_serializing_if = "Option::is_none"
    )]
    pub unavailable_operation_count: Option<i64>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DoctorResultFindingsItem {
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "details", skip_serializing_if = "Option::is_none")]
    pub details: Option<DoctorResultFindingsItemDetails>,
    #[serde(rename = "scope")]
    pub scope: String,
    #[serde(rename = "severity")]
    pub severity: String,
    #[serde(rename = "summary")]
    pub summary: String,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DoctorResult {
    #[serde(rename = "checks")]
    pub checks: DoctorResultChecks,
    #[serde(rename = "findingCounts")]
    pub finding_counts: DoctorResultFindingCounts,
    #[serde(rename = "findings")]
    pub findings: Vec<DoctorResultFindingsItem>,
    #[serde(rename = "mode")]
    pub mode: String,
    #[serde(rename = "observedAt")]
    pub observed_at: String,
    #[serde(rename = "overall")]
    pub overall: String,
    #[serde(rename = "ready")]
    pub ready: bool,
    #[serde(rename = "schemaVersion")]
    pub schema_version: String,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct OperationListRequest {}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct OperationListResultItem {
    #[serde(rename = "aliasFor", deserialize_with = "crate::required_nullable")]
    pub alias_for: Option<String>,
    #[serde(rename = "availability")]
    pub availability: String,
    #[serde(rename = "binding")]
    pub binding: String,
    #[serde(rename = "canonicalReference")]
    pub canonical_reference: String,
    #[serde(rename = "minimumEffect")]
    pub minimum_effect: String,
    #[serde(rename = "profiles")]
    pub profiles: Vec<String>,
    #[serde(rename = "reasonCodes")]
    pub reason_codes: Vec<String>,
    #[serde(rename = "reasonOrigins")]
    pub reason_origins: Vec<String>,
    #[serde(rename = "reasons")]
    pub reasons: Vec<String>,
    #[serde(rename = "reference")]
    pub reference: String,
}

pub type OperationListResult = Vec<OperationListResultItem>;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DeviceObservationsRequestFollowing {
    #[serde(rename = "candidate")]
    pub candidate: String,
    #[serde(rename = "observationGeneration")]
    pub observation_generation: String,
    #[serde(rename = "observationId")]
    pub observation_id: String,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DeviceObservationsRequest {
    #[serde(rename = "candidateKey", skip_serializing_if = "Option::is_none")]
    pub candidate_key: Option<String>,
    #[serde(rename = "following", skip_serializing_if = "Option::is_none")]
    pub following: Option<DeviceObservationsRequestFollowing>,
    #[serde(rename = "observationId", skip_serializing_if = "Option::is_none")]
    pub observation_id: Option<String>,
    #[serde(rename = "snapshotGeneration", skip_serializing_if = "Option::is_none")]
    pub snapshot_generation: Option<i64>,
    #[serde(rename = "useWarmSnapshot", skip_serializing_if = "Option::is_none")]
    pub use_warm_snapshot: Option<bool>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DeviceObservationsResultObservationsItemDeviceInformation {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "observedAtUtc")]
    pub observed_at_utc: String,
    #[serde(rename = "systemVersion")]
    pub system_version: String,
    #[serde(rename = "transport")]
    pub transport: String,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DeviceObservationsResultObservationsItem {
    #[serde(
        rename = "adoptedTargetId",
        deserialize_with = "crate::required_nullable"
    )]
    pub adopted_target_id: Option<String>,
    #[serde(rename = "authorizationState")]
    pub authorization_state: String,
    #[serde(
        rename = "bindingRevision",
        deserialize_with = "crate::required_nullable"
    )]
    pub binding_revision: Option<i64>,
    #[serde(rename = "candidateKey")]
    pub candidate_key: String,
    #[serde(
        rename = "deviceInformation",
        deserialize_with = "crate::required_nullable"
    )]
    pub device_information: Option<DeviceObservationsResultObservationsItemDeviceInformation>,
    #[serde(rename = "displayName", deserialize_with = "crate::required_nullable")]
    pub display_name: Option<String>,
    #[serde(rename = "displayNameGeneration")]
    pub display_name_generation: String,
    #[serde(rename = "observationContinuity")]
    pub observation_continuity: String,
    #[serde(rename = "observationId")]
    pub observation_id: String,
    #[serde(rename = "observedFacts")]
    pub observed_facts: (),
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DeviceObservationsResult {
    #[serde(rename = "health")]
    pub health: String,
    #[serde(rename = "observations")]
    pub observations: Vec<DeviceObservationsResultObservationsItem>,
    #[serde(rename = "observedAtUtc")]
    pub observed_at_utc: String,
    #[serde(rename = "schemaVersion")]
    pub schema_version: String,
    #[serde(rename = "snapshotGeneration")]
    pub snapshot_generation: String,
}
