# capture.diagnostics@1 read-leg answers of the shared fake HDC, by mode.
key=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
case "$*" in
"list targets -v")
  printf '%s\t\tUSB\tConnected\tlocalhost\n' "$key" ;;
"-t $key shell param get const.product.name")
  printf 'OpenHarmony Reference Device\n' ;;
"-t $key shell param get const.ohos.fullname")
  printf 'OpenHarmony-4.1-release\n' ;;
"-t $key shell df -k /data/local/tmp")
  printf 'Filesystem 1K-blocks Used Available Use%% Mounted on\n'
  printf '/dev/block/data 1048576 1024 1047552 1%% /data\n' ;;
"-t $key shell hilog -x")
  printf '01-01 00:00:00 I app: hello\n' ;;
"-t $key shell hidumper -s WindowManagerService -a -a")
  printf '{"windows":[]}\n' ;;
"-t $key shell hidumper -s WindowManagerService -a -w 7 -element -lastpage 42")
  case $mode in
  degraded) printf 'ComponentInfo \377\376\n' ;;
  hang) exec /bin/sleep 40 ;;
  *) printf 'WindowId: 7\nComponentId: 42\ntype: Button\ntext: Sign in\n' ;;
  esac ;;
"-t $key shell hidumper -s 1201 -a -p Faultlogger -l")
  case $mode in
  degraded)
    printf '\nFault log list:\n******\n******\nNo fault log exist.\n'
    exit 1 ;;
  truncated) /usr/bin/head -c 8400000 /dev/zero | /usr/bin/tr '\0' 'x' ;;
  large)
    /usr/bin/head -c 1100000 /dev/zero | /usr/bin/tr '\0' 'y'
    printf '\n' ;;
  *)
    printf '\n-------------------------------[ability]-------------------------------\n\n'
    printf '----------------------------------HiviewService----------------------------------\n'
    printf 'Fault log list:\n******\n'
    printf 'cppcrash-com.example.demo-20010039-20260914000000\n'
    printf 'jscrash-com.example.demo-20010039-20260913235959\n******\n' ;;
  esac ;;
"-t $key shell hidumper -s 1201 -a -p Faultlogger -f "*)
  case $mode in
  degraded) printf 'invalid parameters.\n' ;;
  headerless) printf 'Fault log list:\n' ;;
  *)
    printf 'Generated by HiviewDFX@OpenHarmony\n'
    printf '================================================================\n'
    printf 'Device info:OpenHarmony 3.2\nModule name:com.example.demo\n'
    printf 'Process name:%s\n' "${8##* }" ;;
  esac ;;
"-t $key shell pidof "*)
  case $mode in
  degraded) : ;;
  ambiguous) printf '1234 render\n' ;;
  unavailable)
    printf '/bin/sh: pidof: inaccessible or not found\n'
    exit 127 ;;
  killed) kill -9 $$ ;;
  *) printf '1234\n' ;;
  esac ;;
*)
  printf 'unregistered fixture output\n' >&2
  exit 23 ;;
esac
