#!/usr/bin/env python3
"""Consume the protected-main Swift contract without changing its source or corpus.

The baseline is a development input, never a hardware acceptance certificate.
--write requires an explicit protected-main revision. --check uses the recorded
commit, checks every pinned input, and compares generated Rust without writing.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re
import subprocess

ROOT = Path(__file__).resolve().parents[2]
REGISTRY = "Packages/ArkDeckKit/Contracts/control-protocol.json"
METHODS = "spec/control/methods"
CORPUS = "Packages/ArkDeckKit/Tests/ArkDeckContractTests/Fixtures/ControlFrames"
BASELINE = ROOT / "spec/baselines/swift-single-v1.json"
GENERATED = ROOT / "rust/crates/arkdeck-contract/src/control_generated.rs"
INPUTS = [
    REGISTRY,
    "Packages/ArkDeckKit/Sources/ArkDeckCore/ControlProtocolGenerated.swift",
    "Packages/ArkDeckKit/Sources/ArkDeckCore/PortableCanonicalJSON.swift",
    "Packages/ArkDeckKit/Sources/ArkDeckCore/CanonicalCBOR.swift",
    "Packages/ArkDeckKit/Sources/ArkDeckCore/ControlProtocolContract.swift",
    "Packages/ArkDeckKit/Sources/ArkDeckCore/ControlFrameJSON.swift",
    "openspec/contracts/runtime-control-plane.schema.json",
    "openspec/contracts/cli-canonical-json-vectors.json",
    "openspec/contracts/cli-result.schema.json",
    "openspec/contracts/cli-error-registry.yaml",
    "Packages/ArkDeckKit/Tests/ArkDeckContractTests/Fixtures/CLI/argv/doctor.json",
    "Packages/ArkDeckKit/Tests/ArkDeckContractTests/Fixtures/CLI/argv/operation.list.json",
    "Packages/ArkDeckKit/Tests/ArkDeckContractTests/Fixtures/CLI/argv/device.candidates.json",
    "openspec/changes/chg-2026-059-arkdeck-arkforge-authority/permit-vectors.md",
    "openspec/contracts/journal-event.schema.json",
    METHODS,
    CORPUS,
    "Catalog/operations",
    "Catalog/profiles",
    "Catalog/generated/effect-authorization-matrix.md",
    "Packages/ArkDeckKit/Tests/ArkDeckContractTests/Fixtures/HDC",
]
KEYWORDS = {"type", "properties", "additionalProperties", "required", "items", "enum", "anyOf"}


def git(*args: str) -> bytes:
    return subprocess.check_output(["git", "-C", str(ROOT), *args])


def sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def baseline(commit: str) -> dict:
    files = {}
    directories = {}
    for path in INPUTS:
        rows = git("ls-tree", "-r", commit, "--format=%(objectname) %(path)", "--", path)
        if not rows:
            raise ValueError(f"missing baseline input: {path}")
        if (ROOT / path).is_dir():
            directories[path] = sha(b"".join(line + b"\n" for line in sorted(rows.splitlines())))
        for line in rows.decode().splitlines():
            blob, file = line.split(" ", 1)
            contents = git("show", f"{commit}:{file}")
            if (ROOT / file).read_bytes() != contents:
                raise ValueError(f"working input differs from Swift baseline: {file}")
            files[file] = {"blob": blob, "sha256": sha(contents)}
    registry = json.loads((ROOT / REGISTRY).read_bytes())
    identity = sha(json.dumps(registry, sort_keys=True, separators=(",", ":")).encode())
    matrix = (ROOT / "Catalog/generated/effect-authorization-matrix.md").read_text(encoding="utf-8")
    digest = re.search(r"Catalog digest: `([a-f0-9]{64})`", matrix).group(1)
    return {
        "schemaVersion": "arkdeck.swift-development-baseline/1",
        "kind": "development",
        "commit": commit,
        "protocolVersion": registry["currentVersion"],
        "contractIdentity": identity,
        "catalogDigest": digest,
        "methodCount": len(registry["methods"]),
        "corpusFileCount": len(list((ROOT / CORPUS).glob("*.jsonl"))),
        "directoryDigests": directories,
        "files": dict(sorted(files.items())),
    }


def check_vocabulary(schema: dict) -> None:
    unknown = schema.keys() - KEYWORDS
    if unknown:
        raise ValueError(f"unsupported schema vocabulary: {sorted(unknown)}")
    for child in schema.get("properties", {}).values():
        check_vocabulary(child)
    for child in schema.get("anyOf", []):
        check_vocabulary(child)
    if "items" in schema:
        check_vocabulary(schema["items"])


def generate(info: dict) -> str:
    registry = json.loads((ROOT / REGISTRY).read_text(encoding="utf-8"))
    lines = ["// Generated by rust/scripts/generate-contract.py. Do not edit.", ""]
    for key, rust_name in [("currentVersion", "PROTOCOL_VERSION"),
                           ("maximumRequestFrameBytes", "MAX_REQUEST_BYTES"),
                           ("maximumResponseFrameBytes", "MAX_RESPONSE_BYTES")]:
        value = registry[key]
        ty = "&str" if isinstance(value, str) else "usize"
        lines.append(f"pub const {rust_name}: {ty} = {json.dumps(value)};")
    lines.append(f'pub const CONTRACT_IDENTITY: &str = "{info["contractIdentity"]}";')
    lines.append('pub const SWIFT_BASELINE: &str = include_str!("../../../../spec/baselines/swift-single-v1.json");')
    lines.append("pub const METHODS: &[&str] = &[")
    lines.extend(f'    "{method}",' for method in registry["methods"])
    lines.append("];\n")
    lines.append("pub const METHOD_SCHEMAS: &[(&str, &str)] = &[")
    schemas = {}
    for method in registry["methods"]:
        document = json.loads((ROOT / METHODS / f"{method}.json").read_text(encoding="utf-8"))
        if document["x-arkdeck-contractIdentity"] != info["contractIdentity"]:
            raise ValueError(f"schema identity drift: {method}")
        schemas[method] = document["$defs"]
        for schema in document["$defs"].values():
            check_vocabulary(schema)
        lines.append(f'    ("{method}", include_str!("../../../../{METHODS}/{method}.json")),')
    lines.append("];\n")

    def rust_type(schema: dict, name: str) -> str:
        if "anyOf" in schema:
            alternatives = schema["anyOf"]
            nonnull = [s for s in alternatives if s.get("type") not in ("null", ["null"])]
            if len(nonnull) == 1 and len(alternatives) == 2:
                return f"Option<{rust_type(nonnull[0], name)}>"
            return "serde_json::Value"
        kind = schema.get("type")
        if isinstance(kind, list):
            nonnull = [t for t in kind if t != "null"]
            if len(nonnull) == 1 and "null" in kind:
                return f"Option<{rust_type(dict(schema, type=nonnull[0]), name)}>"
            if not nonnull:
                return "()"
            return "serde_json::Value"
        if kind == "array":
            return f'Vec<{rust_type(schema["items"], name + "Item")}>'
        if kind == "object":
            fields = []
            for key, child in schema.get("properties", {}).items():
                suffix = key[0].upper() + key[1:]
                ty = rust_type(child, name + suffix)
                optional = key not in schema.get("required", [])
                if optional:
                    ty = f"Option<{ty}>"
                field = re.sub(r"(?<!^)(?=[A-Z])", "_", key).lower()
                fields.append(f'    #[serde(rename = "{key}"' +
                              (', skip_serializing_if = "Option::is_none"' if optional else '') +
                              (', deserialize_with = "crate::required_nullable"' if not optional and ty.startswith('Option<') else '') + ')]')
                fields.append(f"    pub {field}: {ty},")
            lines.extend(["#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]",
                          "#[serde(deny_unknown_fields)]", f"pub struct {name} {{", *fields, "}", ""])
            return name
        return {"string": "String", "boolean": "bool", "integer": "i64", "number": "f64", "null": "()"}.get(kind, "serde_json::Value")

    for method, name in [("health", "Health"), ("doctor", "Doctor"),
                         ("operation.list", "OperationList"), ("device.observations", "DeviceObservations")]:
        for part in ("request", "result"):
            type_name = name + part.title()
            actual = rust_type(schemas[method][part], type_name)
            if type_name != actual:
                lines.append(f"pub type {type_name} = {actual};\n")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    modes = parser.add_mutually_exclusive_group(required=True)
    modes.add_argument("--write", action="store_true")
    modes.add_argument("--check", action="store_true")
    parser.add_argument("--baseline-revision")
    args = parser.parse_args()
    if args.write:
        if not args.baseline_revision:
            parser.error("--write requires --baseline-revision (the protected-main Swift commit)")
        commit = git("rev-parse", args.baseline_revision + "^{commit}").decode().strip()
        subprocess.check_call(["git", "-C", str(ROOT), "merge-base", "--is-ancestor", commit, "origin/main"])
    else:
        commit = json.loads(BASELINE.read_text(encoding="utf-8"))["commit"]
    info = baseline(commit)
    outputs = {BASELINE: json.dumps(info, indent=2, sort_keys=True) + "\n", GENERATED: generate(info)}
    for path, content in outputs.items():
        if path == GENERATED:
            # The rustup proxy discovers and installs rust/rust-toolchain.toml
            # on a fresh host; `rustup run` would require a prior installation.
            content = subprocess.check_output(
                ["rustfmt", "--edition", "2024", "--config", "newline_style=Unix"],
                input=content.encode("utf-8"), cwd=ROOT / "rust",
            ).decode("utf-8")
        if args.write:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
        elif not path.exists() or path.read_text(encoding="utf-8") != content:
            raise SystemExit(f"generated input drift: {path.relative_to(ROOT)}")
    print(f'Swift development baseline {commit}: {info["methodCount"]} methods, {info["corpusFileCount"]} corpus files')


if __name__ == "__main__":
    main()
