#!/usr/bin/env python3
"""Extract pinned Unicode 17 Indic properties for frozen Swift compatibility.

Input: https://www.unicode.org/Public/17.0.0/ucd/DerivedCoreProperties.txt
No network or source audit is performed by this generator.
"""
import argparse
import hashlib
from pathlib import Path

PIN = "24c7fed1195c482faaefd5c1e7eb821c5ee1fb6de07ecdbaa64b56a99da22c08"


def generate(data: bytes) -> str:
    if hashlib.sha256(data).hexdigest() != PIN:
        raise ValueError("Unicode input does not match the pinned source")
    groups = {"Consonant": [], "Extend": [], "Linker": []}
    for line in data.decode("utf-8").splitlines():
        fields = [part.strip() for part in line.split("#", 1)[0].split(";")]
        if len(fields) != 3 or fields[1] != "InCB":
            continue
        bounds = fields[0].split("..")
        groups[fields[2]].append((int(bounds[0], 16), int(bounds[-1], 16)))
    lines = ["// Generated by rust/scripts/generate-swift-grapheme-tables.py; do not edit.",
             "// Unicode 17.0.0 DerivedCoreProperties.txt; Unicode License v3 (UNICODE-LICENSE).",
             f"// Source SHA-256: {PIN}"]
    for name, ranges in groups.items():
        ranges.sort()
        if not ranges or any(a[1] >= b[0] for a, b in zip(ranges, ranges[1:])):
            raise ValueError("missing or overlapping Unicode ranges")
        lines.append(f"pub(super) const {name.upper()}: &[(u32, u32)] = &[")
        lines.extend(f"    (0x{lo:X}, 0x{hi:X})," for lo, hi in ranges)
        lines.append("];")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    result = generate(args.input.read_bytes())
    if args.check:
        if args.output.read_text() != result:
            raise ValueError("generated Unicode ranges have drifted")
    else:
        args.output.write_text(result)


if __name__ == "__main__":
    main()
