#!/usr/bin/env python3
"""Generate the pinned Unicode tables behind arkdeck-platform's host text.

They stand in for CoreFoundation's predefined character sets and its NFC:
`controlCharacters` (Cc, Cf), `alphanumerics` (L*, M*, N*),
`whitespacesAndNewlines` (Z*, U+0009 to U+000D, U+0085), and the canonical
decomposition, combining class and primary composition data that
`CFStringNormalize(kCFStringNormalizationFormC)` applies.

Inputs, both from https://www.unicode.org/Public/17.0.0/ucd/:
  UnicodeData.txt, CompositionExclusions.txt
No network or source audit is performed by this generator.
"""
import argparse
import hashlib
from pathlib import Path

VERSION = "17.0.0"
PINS = {
    "UnicodeData.txt": "2e1efc1dcb59c575eedf5ccae60f95229f706ee6d031835247d843c11d96470c",
    "CompositionExclusions.txt": "2f239196ef3b5b61db5cc476e9bd80f534d15aa1b74e1be1dea5d042a344c85f",
}


def pinned(directory: Path, name: str) -> str:
    data = (directory / name).read_bytes()
    if hashlib.sha256(data).hexdigest() != PINS[name]:
        raise ValueError(f"{name} does not match the pinned Unicode {VERSION} source")
    return data.decode("utf-8")


def records(text: str):
    """Yield (first, last, fields) with First/Last ranges folded together."""
    first = None
    for line in text.splitlines():
        fields = line.split(";")
        code = int(fields[0], 16)
        if fields[1].endswith(", First>"):
            first = code
            continue
        if fields[1].endswith(", Last>"):
            if first is None:
                raise ValueError("range end without a start")
            yield first, code, fields
            first = None
            continue
        yield code, code, fields


def ranges(points):
    result = []
    for code in sorted(points):
        if result and result[-1][1] + 1 == code:
            result[-1][1] = code
        else:
            result.append([code, code])
    return result


def generate(directory: Path) -> str:
    data = pinned(directory, "UnicodeData.txt")
    exclusions_text = pinned(directory, "CompositionExclusions.txt")
    control, alphanumeric, whitespace = set(), set(), {0x9, 0xA, 0xB, 0xC, 0xD, 0x85}
    combining = {}
    decomposition = {}
    for low, high, fields in records(data):
        category = fields[2]
        for code in range(low, high + 1):
            if category in ("Cc", "Cf"):
                control.add(code)
            if category[0] in "LMN":
                alphanumeric.add(code)
            if category[0] == "Z":
                whitespace.add(code)
            if int(fields[3]):
                combining[code] = int(fields[3])
        mapping = fields[5]
        if mapping and not mapping.startswith("<"):
            if low != high:
                raise ValueError("canonical mapping on a code point range")
            parts = [int(part, 16) for part in mapping.split()]
            if not 1 <= len(parts) <= 2:
                raise ValueError("canonical mapping longer than two scalars")
            decomposition[low] = parts
    excluded = set()
    for line in exclusions_text.splitlines():
        body = line.split("#", 1)[0].strip()
        if body:
            excluded.add(int(body, 16))
    # Full_Composition_Exclusion (UAX #15): listed exclusions, singletons and
    # non-starter decompositions never recompose.
    compositions = []
    for code, parts in decomposition.items():
        if code in excluded or len(parts) == 1:
            continue
        if combining.get(code, 0) or combining.get(parts[0], 0):
            continue
        compositions.append((parts[0], parts[1], code))
    compositions.sort()
    if len({(a, b) for a, b, _ in compositions}) != len(compositions):
        raise ValueError("ambiguous primary composition")
    classes = []
    for code in sorted(combining):
        value = combining[code]
        if classes and classes[-1][1] + 1 == code and classes[-1][2] == value:
            classes[-1][1] = code
        else:
            classes.append([code, code, value])

    lines = [
        "// Generated by rust/scripts/generate-host-text-tables.py; do not edit.",
        f"// Unicode {VERSION} UnicodeData.txt and CompositionExclusions.txt;",
        "// Unicode License v3 (UNICODE-LICENSE).",
    ]
    lines += [f"// {name} SHA-256: {pin}" for name, pin in PINS.items()]
    lines.append("#[cfg(test)]")
    lines.append(f'pub(super) const UNICODE_VERSION: &str = "{VERSION}";')
    for name, points in (
        ("CONTROL", control),
        ("ALPHANUMERIC", alphanumeric),
        ("WHITESPACE_OR_NEWLINE", whitespace),
    ):
        lines.append(f"pub(super) const {name}: &[(u32, u32)] = &[")
        lines += [f"    (0x{lo:X}, 0x{hi:X})," for lo, hi in ranges(points)]
        lines.append("];")
    lines.append("pub(super) const COMBINING_CLASS: &[(u32, u32, u8)] = &[")
    lines += [f"    (0x{lo:X}, 0x{hi:X}, {value})," for lo, hi, value in classes]
    lines.append("];")
    lines.append("/// Canonical mapping: (scalar, first, second or 0 for a singleton).")
    lines.append("pub(super) const DECOMPOSITION: &[(u32, u32, u32)] = &[")
    for code in sorted(decomposition):
        parts = decomposition[code] + [0]
        lines.append(f"    (0x{code:X}, 0x{parts[0]:X}, 0x{parts[1]:X}),")
    lines.append("];")
    lines.append("/// Primary composites: (first, second, composite), sorted by the pair.")
    lines.append("pub(super) const COMPOSITION: &[(u32, u32, u32)] = &[")
    lines += [f"    (0x{a:X}, 0x{b:X}, 0x{c:X})," for a, b, c in compositions]
    lines.append("];")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", required=True, type=Path, help="directory with the UCD files")
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    result = generate(args.input)
    if args.check:
        if args.output.read_text(encoding="utf-8") != result:
            raise ValueError("generated Unicode tables have drifted")
    else:
        args.output.write_text(result, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
