import ArkDeckCore
import ArkDeckWorkflows
import Foundation

/// The §14 machine-contract bundle, generated from the build that publishes it.
///
/// Every product here is a projection of something the binary already owns:
/// the command registry, the error registry, the canonical-JSON encoder, the
/// control-method registry, the published Catalog and the App capability
/// registry. Nothing is restated. `arkdeck maintainer contracts export` writes
/// the projections to `openspec/contracts/` and the conformance fixtures next
/// to the contract tests; `arkdeck maintainer contracts check` holds the
/// committed files to the build, so a registry change that forgets to
/// regenerate the bundle fails the gate rather than shipping a contract that
/// describes the previous binary.
///
/// The bundle is language-neutral on purpose (§14): a native port reads the
/// YAML/JSON and replays the argv fixtures through its own parser, and the
/// feature-coverage table is where "full function" (§18) is decided — by a
/// closed classification of every daemon method, Catalog operation, App
/// capability and CLI leaf, not by prose.
enum CLIMachineContracts {

  // MARK: Versions

  /// The page envelope every list/events result uses (§7.3).
  static let pageSchemaVersion = "arkdeck.cli.page/1"
  /// The closed `nextAction` union shared by `job status` and `agent status` (§7.3).
  static let nextActionSchemaVersion = "arkdeck.cli.next-action/1"
  static let controlPlaneSchemaVersion = "arkdeck.runtime-control-plane/1"
  static let featureCoverageSchemaVersion = "arkdeck.cli.feature-coverage/1"
  static let canonicalVectorsSchemaVersion = "arkdeck.cli.canonical-json-vectors/1"
  static let argvFixtureSchemaVersion = "arkdeck.cli.argv-fixture/1"
  static let envelopeFixtureSchemaVersion = "arkdeck.cli.envelope-fixture/1"
  static let fixtureIndexSchemaVersion = "arkdeck.cli.fixture-index/1"

  /// The correlation identity every fixture envelope carries. Fixed, so that
  /// the committed bytes are a function of the build alone.
  static let fixtureControlRequestID = "ctl-fixture-0001"
  static let generatedNotice =
    "Generated by `arkdeck maintainer contracts export`; do not edit by hand."

  /// The ten §14 products, by file name under `openspec/contracts/`.
  static let contractRelativePaths: [String] = [
    "cli-command-registry.yaml",
    "cli-error-registry.yaml",
    "cli-canonical-json-vectors.json",
    "cli-feature-coverage.json",
    "app-product-capability-registry.yaml",
    "cli-result.schema.json",
    "cli-page.schema.json",
    "cli-event.schema.json",
    "cli-next-action.schema.json",
    "runtime-control-plane.schema.json",
  ]

  struct Failure: Error, CustomStringConvertible {
    let message: String
    init(_ message: String) { self.message = message }
    var description: String { message }
  }

  /// One generated file: a path relative to its root, and its exact bytes.
  struct Product: Equatable {
    let relativePath: String
    let bytes: Data
    var text: String { String(decoding: bytes, as: UTF8.self) }
  }

  // MARK: Products

  static func contractProducts() throws -> [Product] {
    let coverage = try FeatureCoverage.build()
    let products: [(String, Data)] = [
      ("cli-command-registry.yaml", ContractYAML.document(commandRegistryDocument())),
      ("cli-error-registry.yaml", ContractYAML.document(errorRegistryDocument())),
      ("cli-canonical-json-vectors.json", ContractJSON.document(try canonicalVectorsDocument())),
      ("cli-feature-coverage.json", ContractJSON.document(coverage.document)),
      ("app-product-capability-registry.yaml", ContractYAML.document(appRegistryDocument())),
      ("cli-result.schema.json", ContractJSON.document(Schemas.result)),
      ("cli-page.schema.json", ContractJSON.document(Schemas.page)),
      ("cli-event.schema.json", ContractJSON.document(Schemas.event)),
      ("cli-next-action.schema.json", ContractJSON.document(Schemas.nextAction)),
      ("runtime-control-plane.schema.json", ContractJSON.document(Schemas.controlPlane)),
    ]
    let paths = products.map(\.0)
    guard paths == contractRelativePaths else {
      throw Failure("the contract product list drifted from its declared file names")
    }
    return products.map { Product(relativePath: $0.0, bytes: $0.1) }
  }

  static func fixtureProducts() throws -> [Product] {
    var products: [Product] = []
    var seen: Set<String> = []
    for (path, leaf) in CLICommandRegistry.allLeaves() {
      guard seen.insert(leaf.canonicalCommand).inserted else {
        throw Failure("canonical command \(leaf.canonicalCommand) is declared twice")
      }
      let document = try ArgvFixtures.document(path: path, leaf: leaf)
      products.append(
        Product(
          relativePath: "argv/\(leaf.canonicalCommand).json",
          bytes: ContractJSON.document(document)))
    }
    products += try EnvelopeFixtures.products()
    products += SampleDocuments.products()
    let index: JSONValue = .object([
      "schemaVersion": .string(fixtureIndexSchemaVersion),
      "bundleVersion": .string(CLIProductVersion.machineContract),
      "cliVersion": .string(CLIProductVersion.product),
      "argvFixtureSchemaVersion": .string(argvFixtureSchemaVersion),
      "envelopeFixtureSchemaVersion": .string(envelopeFixtureSchemaVersion),
      "controlRequestId": .string(fixtureControlRequestID),
      "files": .array(products.map(\.relativePath).sorted().map(JSONValue.string)),
    ])
    products.append(Product(relativePath: "index.json", bytes: ContractJSON.document(index)))
    return products.sorted { $0.relativePath < $1.relativePath }
  }

  // MARK: Export and drift

  struct ExportReport {
    var written: [String] = []
    var removed: [String] = []
  }

  struct CheckReport {
    var drifted: [String] = []
    var missing: [String] = []
    var unexpected: [String] = []
    var checked = 0
    var isClean: Bool { drifted.isEmpty && missing.isEmpty && unexpected.isEmpty }

    var document: JSONValue {
      .object([
        "clean": .bool(isClean),
        "checked": .integer(Int64(checked)),
        "drifted": .array(drifted.map(JSONValue.string)),
        "missing": .array(missing.map(JSONValue.string)),
        "unexpected": .array(unexpected.map(JSONValue.string)),
      ])
    }
  }

  static func export(contractsDirectory: URL, fixturesDirectory: URL) throws -> ExportReport {
    let contracts = try contractProducts()
    let fixtures = try fixtureProducts()
    var report = ExportReport()
    for product in contracts {
      try write(product, under: contractsDirectory)
      report.written.append("contracts/\(product.relativePath)")
    }
    let expected = Set(fixtures.map(\.relativePath))
    for stale in try regularFiles(under: fixturesDirectory) where !expected.contains(stale) {
      try FileManager.default.removeItem(at: fixturesDirectory.appendingPathComponent(stale))
      report.removed.append("fixtures/\(stale)")
    }
    for product in fixtures {
      try write(product, under: fixturesDirectory)
      report.written.append("fixtures/\(product.relativePath)")
    }
    return report
  }

  static func check(contractsDirectory: URL, fixturesDirectory: URL) throws -> CheckReport {
    var report = CheckReport()
    for product in try contractProducts() {
      compare(product, under: contractsDirectory, label: "contracts", into: &report)
    }
    let fixtures = try fixtureProducts()
    for product in fixtures {
      compare(product, under: fixturesDirectory, label: "fixtures", into: &report)
    }
    let expected = Set(fixtures.map(\.relativePath))
    for extra in try regularFiles(under: fixturesDirectory) where !expected.contains(extra) {
      report.unexpected.append("fixtures/\(extra)")
    }
    report.unexpected.sort()
    return report
  }

  private static func compare(
    _ product: Product, under root: URL, label: String, into report: inout CheckReport
  ) {
    report.checked += 1
    let url = root.appendingPathComponent(product.relativePath)
    guard let existing = try? Data(contentsOf: url) else {
      report.missing.append("\(label)/\(product.relativePath)")
      return
    }
    if existing != product.bytes { report.drifted.append("\(label)/\(product.relativePath)") }
  }

  private static func write(_ product: Product, under root: URL) throws {
    let url = root.appendingPathComponent(product.relativePath)
    try FileManager.default.createDirectory(
      at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
    try product.bytes.write(to: url, options: .atomic)
  }

  /// Every regular file under `root`, as a sorted relative path list. Hidden
  /// files are skipped so a Finder sidecar never counts as a stray fixture.
  private static func regularFiles(under root: URL) throws -> [String] {
    var isDirectory: ObjCBool = false
    guard FileManager.default.fileExists(atPath: root.path, isDirectory: &isDirectory),
      isDirectory.boolValue
    else { return [] }
    guard
      let enumerator = FileManager.default.enumerator(
        at: root, includingPropertiesForKeys: [.isRegularFileKey], options: [.skipsHiddenFiles])
    else { return [] }
    var found: [String] = []
    let prefix = root.standardizedFileURL.path + "/"
    for case let url as URL in enumerator {
      guard (try? url.resourceValues(forKeys: [.isRegularFileKey]).isRegularFile) == true else {
        continue
      }
      let path = url.standardizedFileURL.path
      guard path.hasPrefix(prefix) else { continue }
      found.append(String(path.dropFirst(prefix.count)))
    }
    return found.sorted()
  }

  // MARK: Registry projections

  static func commandRegistryDocument() -> JSONValue {
    var commands: JSONValue = .array([])
    if case .object(let projection) = CLIRegistryProjection.result(),
      let published = projection["commands"]
    {
      commands = published
    }
    return .object([
      "schemaVersion": .string(CLICommandRegistry.schemaVersion),
      "bundleVersion": .string(CLIProductVersion.machineContract),
      "cliVersion": .string(CLIProductVersion.product),
      "catalogDigest": .string(RuntimeOperationCatalog.catalogDigest),
      "commands": commands,
    ])
  }

  static func errorRegistryDocument() -> JSONValue {
    let categories: [JSONValue] = CLIExitCategory.allCases.map { category in
      .object([
        "category": .string(category.machineCategory),
        "exitCode": .integer(Int64(category.exitCode)),
        "codes": .array(
          CLIErrorCode.allCases.filter { $0.category == category }
            .map { .string($0.rawValue) }),
      ])
    }
    let codes: [JSONValue] = CLIErrorCode.allCases.map { code in
      .object([
        "code": .string(code.rawValue),
        "category": .string(code.category.machineCategory),
        "exitCode": .integer(Int64(code.exitCode)),
        "controlRequestRetryable": .bool(code.isControlRequestRetryable),
        "attentionRequired": .bool(code.requiresAttention),
      ])
    }
    return .object([
      "schemaVersion": .string(CLIErrorRegistryVersion.current),
      "bundleVersion": .string(CLIProductVersion.machineContract),
      "cliVersion": .string(CLIProductVersion.product),
      "exitCategories": .array(categories),
      "codes": .array(codes),
    ])
  }

  static func appRegistryDocument() -> JSONValue {
    let capabilities: [JSONValue] = AppProductCapabilityRegistry.capabilities.map { capability in
      .object([
        "id": .string(capability.id),
        "surface": .string(capability.surface),
        "title": .string(capability.title),
        "owner": .string(capability.owner),
        "classification": .string(capability.classification.rawValue),
        "cliEquivalent": .array(capability.cliEquivalent.map(JSONValue.string)),
      ])
    }
    return .object([
      "schemaVersion": .string(AppProductCapabilityRegistry.schemaVersion),
      "bundleVersion": .string(CLIProductVersion.machineContract),
      "cliVersion": .string(CLIProductVersion.product),
      "classificationVocabulary": .array(
        ProductCoverageClassification.allCases.map { .string($0.rawValue) }),
      "capabilities": .array(capabilities),
    ])
  }

  // MARK: Canonical JSON vectors

  /// Inputs whose canonical form a port must reproduce byte for byte. The
  /// expected output is computed by this build's encoder, never typed in.
  static let canonicalVectorInputs: [(name: String, value: JSONValue)] = [
    ("emptyObject", .object([:])),
    ("emptyArray", .array([])),
    ("scalars", .array([.null, .bool(true), .bool(false), .integer(0), .string("")])),
    (
      "keyOrderIsUtf16CodeUnit",
      .object(["b": .integer(1), "a": .integer(2), "aa": .integer(3), "B": .integer(0)])
    ),
    (
      "nonAsciiKeyOrder",
      .object(["z": .integer(1), "\u{00E9}": .integer(2), "\u{1F600}": .integer(3), "Z": .integer(4)])
    ),
    (
      "stringEscapes",
      .string("quote\" backslash\\ newline\n tab\t control\u{01} slash/ euro\u{20AC} emoji\u{1F600}")
    ),
    ("integers", .array([.integer(-1), .integer(1), .integer(9_007_199_254_740_991)])),
    ("unsignedInteger", .unsignedInteger(9_007_199_254_740_991)),
    ("numbers", .array([.number(0.5), .number(1.0), .number(-0.0), .number(1e21), .number(123456789.125)])),
    (
      "nested",
      .object([
        "list": .array([.object([:]), .array([]), .object(["k": .array([.null])])]),
        "text": .string("x"),
      ])
    ),
  ]

  /// Values the encoder must refuse. Recorded with the refusal it actually
  /// gives, so the bundle cannot claim a rejection this build does not make.
  static let canonicalRejectionInputs: [(name: String, value: JSONValue)] = [
    ("positiveInfinity", .number(Double.infinity)),
    ("negativeInfinity", .number(-Double.infinity)),
    ("nan", .number(Double.nan)),
    ("integerBeyondExactRange", .integer(Int64.max)),
    ("unsignedIntegerBeyondExactRange", .unsignedInteger(UInt64.max)),
  ]

  static func canonicalVectorsDocument() throws -> JSONValue {
    var vectors: [JSONValue] = []
    for input in canonicalVectorInputs {
      let canonical: String
      do {
        canonical = try CLICanonicalJSON.canonicalString(input.value)
      } catch {
        throw Failure("canonical vector \(input.name) is refused by this build: \(error)")
      }
      vectors.append(
        .object([
          "name": .string(input.name),
          "value": input.value,
          "canonical": .string(canonical),
        ]))
    }
    var rejections: [JSONValue] = []
    for input in canonicalRejectionInputs {
      do {
        let unexpected = try CLICanonicalJSON.canonicalString(input.value)
        throw Failure(
          "canonical rejection \(input.name) was accepted by this build as \(unexpected)")
      } catch let failure as Failure {
        throw failure
      } catch {
        rejections.append(
          .object([
            "name": .string(input.name),
            "reason": .string(String(describing: error)),
          ]))
      }
    }
    return .object([
      "schemaVersion": .string(canonicalVectorsSchemaVersion),
      "canonicalJsonVersion": .string(CLICanonicalJSON.version),
      "bundleVersion": .string(CLIProductVersion.machineContract),
      "cliVersion": .string(CLIProductVersion.product),
      "vectors": .array(vectors),
      "rejections": .array(rejections),
    ])
  }

  // MARK: Feature coverage (§14, §18)

  enum FeatureCoverage {
    static let classificationVocabulary = ProductCoverageClassification.allCases.map(\.rawValue)
    static let lifecycleVocabulary = ["current", "deprecated", "legacy", "removed"]
    static let platformVocabulary = ["macos", "windows"]

    struct Entry {
      var feature: String
      var source: String
      var classification: String
      var targetClassification: String
      var lifecycle: String
      var targetCommand: String?
      var equivalentCommands: [String] = []
      var conformanceFixture: String?
      var requiredPlatforms: [String]
      var owner: String?
      var note: String?
      /// Canonical commands this entry reaches; not serialized.
      var referencedLeaves: [String] = []

      var document: JSONValue {
        var fields: [String: JSONValue] = [
          "feature": .string(feature),
          "source": .string(source),
          "classification": .string(classification),
          "targetClassification": .string(targetClassification),
          "lifecycle": .string(lifecycle),
          "targetCommand": targetCommand.map(JSONValue.string) ?? .null,
          "equivalentCommands": .array(equivalentCommands.map(JSONValue.string)),
          "conformanceFixture": conformanceFixture.map(JSONValue.string) ?? .null,
          "requiredPlatforms": .array(requiredPlatforms.map(JSONValue.string)),
          "implementationStatusByPlatform": .object(
            Dictionary(
              uniqueKeysWithValues: requiredPlatforms.map { platform in
                (platform, JSONValue.string(implementationStatus(on: platform)))
              })),
        ]
        if let owner { fields["owner"] = .string(owner) }
        if let note { fields["note"] = .string(note) }
        return .object(fields)
      }

      /// §14's closed status set. `implemented` on macOS means the entry's
      /// contract, registry mapping and fixture are closed — a tombstone or a
      /// refused stub that refuses exactly as contracted is implemented too;
      /// `blocked` is `partial`; a platform without a ratified profile is
      /// never reported as anything but `notImplemented`.
      func implementationStatus(on platform: String) -> String {
        guard platform == "macos" else { return "notImplemented" }
        return classification == ProductCoverageClassification.blocked.rawValue
          ? "partial" : "implemented"
      }
    }

    struct Coverage {
      let entries: [Entry]
      let document: JSONValue
    }

    /// How one daemon control method is reached from the product surface.
    enum DaemonCoverage {
      /// Fronted by this leaf; classification and lifecycle come from the
      /// leaf unless overridden. `also` names compatibility leaves that reach
      /// the same method under a superseded spelling.
      case leaf(String, lifecycle: String? = nil, note: String? = nil, also: [String] = [])
      /// Closed protocol plumbing behind a published leaf (§18 `internal`).
      case plumbing(behind: String, note: String)
      /// Kept so the name answers with a stable refusal (§18 `refused`).
      case refused(leaf: String, note: String)
    }

    /// The authored half of the table: every classified control method and
    /// how the CLI reaches it. `build()` refuses a method missing from here,
    /// so a new daemon method cannot enter the registry without a coverage
    /// ruling.
    static let daemonMethodCoverage: [String: DaemonCoverage] = [
      "agent.abandon": .leaf("agent.abandon"),
      "agent.list": .leaf("agent.list"),
      "agent.resume": .leaf("agent.resume"),
      "agent.run": .leaf("agent.run"),
      "agent.status": .leaf("agent.status"),
      "artifact.export": .leaf("artifact.export"),
      "artifact.import.abort": .leaf("artifact.import.abort"),
      "artifact.import.append": .plumbing(
        behind: "artifact.import.hap",
        note: "bounded chunk frame behind `artifact import <kind>`"),
      "artifact.import.begin": .plumbing(
        behind: "artifact.import.hap",
        note: "durable import session opening behind `artifact import <kind>`"),
      "artifact.import.commit": .plumbing(
        behind: "artifact.import.hap",
        note: "digest-checked commit behind `artifact import <kind>`"),
      "artifact.import.inspect": .leaf("artifact.import.inspect"),
      "artifact.import.inspection": .plumbing(
        behind: "artifact.import.hap",
        note: "idempotent re-entry probe behind `artifact import <kind>`"),
      "artifact.import.list": .leaf("artifact.import.list"),
      "artifact.import.release": .leaf("artifact.import.release"),
      "artifact.inspect": .leaf("artifact.inspect"),
      "artifact.list": .leaf("artifact.list"),
      "artifact.quota": .leaf("artifact.quota"),
      "artifact.read": .leaf("artifact.read"),
      "capability.inspect": .leaf("capability.inspect"),
      "capability.list": .leaf("capability.list"),
      "cleanupDebt.continue": .leaf("recovery.cleanup.continue", also: ["cleanup-debt.continue"]),
      "cleanupDebt.list": .leaf("recovery.cleanup.list", also: ["cleanup-debt.list"]),
      "control-action.list": .leaf("control-action.list"),
      "control-action.reconcile": .leaf("control-action.reconcile"),
      "control-action.show": .leaf("control-action.show"),
      "debug.evaluate": .leaf("recovery.flash-invocation.evaluate", also: ["debug.evaluate"]),
      "debug.probe": .leaf("debug.probe"),
      "debug.start": .leaf("recovery.flash-invocation.start", also: ["debug.start"]),
      "debug.status": .leaf("recovery.flash-invocation.status", also: ["debug.status"]),
      "debug.template.run": .leaf(
        "debug.template.run", lifecycle: "deprecated",
        note:
          "App direct path; the CLI reaches the same closed template set through Catalog operation debug.template@1"),
      "device.display-name.clear": .leaf("device.display-name.clear"),
      "device.display-name.set": .leaf("device.display-name.set"),
      "device.observations": .leaf(
        "device.wait", note: "observation snapshot read by `device wait` and `device list`",
        also: ["device.list"]),
      "doctor": .leaf("doctor"),
      "flash.bind-current-loader": .leaf("flash.bind-loader"),
      "flash.bootloader-status": .leaf("flash.bootloader-status"),
      "flash.device-access": .leaf("flash.device-access"),
      "flash.lanePlanPreview": .leaf("flash.lane-preview"),
      "flash.prerequisites": .leaf("flash.prerequisites"),
      "health": .leaf("runtime.health"),
      "history.filter.delete": .leaf("history.filter.delete"),
      "history.filter.list": .leaf("history.filter.list"),
      "history.filter.save": .leaf("history.filter.save"),
      "human-action.list": .leaf("human-action.list"),
      "human-action.resume": .leaf("human-action.resume"),
      "human-action.show": .leaf("human-action.show"),
      "job.cancel": .leaf("job.cancel"),
      "job.events": .leaf("job.events"),
      "job.evidence": .leaf("job.evidence"),
      "job.list": .leaf("job.list"),
      "job.plan": .leaf("job.plan"),
      "job.reconcile": .leaf("job.reconcile"),
      "job.result": .leaf("job.result"),
      "job.run": .leaf("job.run"),
      "job.show": .leaf("job.show"),
      "job.status": .leaf("job.status"),
      "job.submit": .leaf("job.submit"),
      "job.timeline": .leaf("job.timeline"),
      "operation.describe": .leaf("operation.describe"),
      "operation.list": .leaf("operation.list"),
      "recovery.flash-invocation.list": .leaf("recovery.flash-invocation.list"),
      "runtime.hdc.impact-preview": .leaf("runtime.hdc.impact-preview"),
      "runtime.hdc.restart": .leaf("runtime.hdc.restart"),
      "runtime.hdc.status": .leaf("runtime.hdc.status"),
      "runtime.storage.policy": .leaf("runtime.storage.policy"),
      "runtime.storage.root": .leaf("runtime.storage.root"),
      "runtime.storage.status": .leaf("runtime.storage.status"),
      "runtime.tool.select": .leaf("runtime.tool.select"),
      "session.cleanup.apply": .leaf("session.cleanup.apply"),
      "session.cleanup.preview": .leaf("session.cleanup.preview"),
      "session.export.apply": .leaf("session.export.apply"),
      "session.export.preview": .leaf("session.export.preview"),
      "session.list": .leaf("session.list"),
      "session.pin": .leaf("session.pin"),
      "session.show": .leaf("session.show"),
      "session.unpin": .leaf("session.unpin"),
      "target.adopt": .leaf("target.adopt"),
      "target.availability": .leaf("target.availability"),
      "target.display-name.clear": .leaf("target.display-name.clear"),
      "target.display-name.set": .leaf("target.display-name.set"),
      "target.list": .leaf("target.list"),
      "target.show": .leaf("target.show"),
      "trace.cache.purge": .leaf("trace.cache.purge"),
      "trace.cache.status": .leaf("trace.cache.status"),
      "trace.inspect": .leaf("trace.inspect"),
      "trace.probe": .leaf("trace.probe"),
      "workspace.preset.list": .leaf("workspace.preset.list"),
      "workspace.preset.register": .leaf("workspace.preset.register"),
      "workspace.preset.remove": .leaf("workspace.preset.remove"),
      "workspace.preset.show": .leaf("workspace.preset.show"),
      "workspace.preset.update": .leaf("workspace.preset.update"),
      "workspace.project.list": .leaf("workspace.project.list"),
      "workspace.project.register": .leaf("workspace.project.register"),
      "workspace.project.remove": .leaf("workspace.project.remove"),
      "workspace.project.show": .leaf("workspace.project.show"),
      "workspace.project.update": .leaf("workspace.project.update"),
    ]

    /// Leaves that are §18 `local`: bounded, versioned host-side product
    /// resources shared with the App, which never change Runtime authority.
    /// Everything executable and not listed here is `direct`.
    static let localRoots: Set<String> = [
      "help", "commands", "completion", "session", "history", "agentd", "signing",
      "update-feed", "maintainer",
    ]
    static let localRuntimeGroups: Set<String> = [
      "storage", "update", "support-bundle", "tool", "bundle", "service", "signing",
    ]
    static let localCommands: Set<String> = [
      "trace.cache.status", "trace.cache.purge", "trace.inspect", "trace.export",
      "ui-dump.inspect", "ui-dump.hit-test",
      "diagnostics.inspect", "diagnostics.preview", "diagnostics.export",
      "artifact.quota", "artifact.list", "artifact.inspect", "artifact.read", "artifact.export",
      "device.display-name.set", "device.display-name.clear",
      "target.display-name.set", "target.display-name.clear",
      "workspace.continuation.inspect", "debug.template.list",
      "legacy.flash.status", "legacy.flash.reconcile",
      "flash.status", "flash.reconcile", "flash.install-binding",
    ]
    static let localCommandPrefixes: [String] = ["workspace.project.", "workspace.preset."]
    /// Runtime-owned selections that live under an otherwise local group.
    static let directCommandsUnderLocalGroups: Set<String> = ["runtime.tool.select"]

    /// Host-specific families that have no Windows form until a Windows
    /// profile is ratified (§11): launchd service management, host code
    /// signing, bundle/tool registration, the auto-update lifecycle, the
    /// maintainer tooling and every frozen 1.x compatibility leaf.
    static let macOSOnlyRoots: Set<String> = ["legacy", "agentd", "signing", "update-feed", "maintainer"]
    static let macOSOnlyRuntimeGroups: Set<String> = [
      "service", "signing", "bundle", "tool", "update", "support-bundle",
    ]

    struct LeafIndex {
      let ordered: [(path: [String], leaf: CLILeafSpec)]
      let byCommand: [String: (path: [String], leaf: CLILeafSpec)]
      let byPath: [[String]: String]

      init() throws {
        let ordered = CLICommandRegistry.allLeaves()
        var byCommand: [String: (path: [String], leaf: CLILeafSpec)] = [:]
        var byPath: [[String]: String] = [:]
        for entry in ordered {
          guard byCommand[entry.leaf.canonicalCommand] == nil else {
            throw Failure("canonical command \(entry.leaf.canonicalCommand) is declared twice")
          }
          byCommand[entry.leaf.canonicalCommand] = entry
          byPath[entry.path] = entry.leaf.canonicalCommand
        }
        self.ordered = ordered
        self.byCommand = byCommand
        self.byPath = byPath
      }

      func leaf(_ command: String) throws -> (path: [String], leaf: CLILeafSpec) {
        guard let found = byCommand[command] else {
          throw Failure("coverage names an unknown command \(command)")
        }
        return found
      }

      /// The leaf an argv pattern such as `arkdeck job status --job <id>` names.
      func resolve(pattern: String) throws -> (path: [String], leaf: CLILeafSpec) {
        let tokens = pattern.split(separator: " ").map(String.init)
        guard tokens.first == "arkdeck" else {
          throw Failure("argv pattern does not start with arkdeck: \(pattern)")
        }
        var path: [String] = []
        for token in tokens.dropFirst() {
          guard !token.hasPrefix("-"), !token.hasPrefix("<"), !token.hasPrefix("("),
            !token.hasPrefix("["), token != "..."
          else { break }
          let candidate = path + [token]
          guard byPath.keys.contains(where: { $0.starts(with: candidate) }) else { break }
          path = candidate
        }
        guard let command = byPath[path] else {
          throw Failure("argv pattern does not name a command: \(pattern)")
        }
        return try leaf(command)
      }
    }

    static func isLocal(path: [String], command: String) -> Bool {
      if directCommandsUnderLocalGroups.contains(command) { return false }
      if let root = path.first, localRoots.contains(root) { return true }
      if path.count > 1, path[0] == "runtime", localRuntimeGroups.contains(path[1]) { return true }
      if localCommands.contains(command) { return true }
      return localCommandPrefixes.contains { command.hasPrefix($0) }
    }

    static func classification(path: [String], leaf: CLILeafSpec) -> String {
      switch leaf.kind {
      case .tombstone, .refused:
        return ProductCoverageClassification.refused.rawValue
      case .executable:
        return isLocal(path: path, command: leaf.canonicalCommand)
          ? ProductCoverageClassification.local.rawValue
          : ProductCoverageClassification.direct.rawValue
      }
    }

    static func lifecycle(of leaf: CLILeafSpec) -> String {
      if case .tombstone = leaf.kind { return "removed" }
      return leaf.lifecycle.rawValue
    }

    static func requiredPlatforms(path: [String], leaf: CLILeafSpec) -> [String] {
      if let root = path.first, macOSOnlyRoots.contains(root) { return ["macos"] }
      if path.count > 1, path[0] == "runtime", macOSOnlyRuntimeGroups.contains(path[1]) {
        return ["macos"]
      }
      if leaf.lifecycle == .legacy { return ["macos"] }
      if case .tombstone = leaf.kind { return ["macos"] }
      return platformVocabulary
    }

    /// The exact argv that reaches a leaf: its path, its required options
    /// with their placeholders, one member of each exactly-one group and its
    /// required positionals.
    static func targetCommand(path: [String], leaf: CLILeafSpec) -> String {
      var tokens = ["arkdeck"] + path
      for option in leaf.options where option.isRequired && option.isPublished {
        tokens.append(option.name)
        if case .value(let placeholder, _) = option.form { tokens.append("<\(placeholder)>") }
      }
      for group in leaf.requiresExactlyOneOf {
        let members = group.map { name -> String in
          guard let option = leaf.options.first(where: { $0.name == name }),
            case .value(let placeholder, _) = option.form
          else { return name }
          return "\(name) <\(placeholder)>"
        }
        tokens.append("(" + members.joined(separator: " | ") + ")")
      }
      for positional in leaf.positionals where positional.isRequired {
        tokens.append("<\(positional.name)>")
      }
      return tokens.joined(separator: " ")
    }

    static func fixture(for leaf: CLILeafSpec) -> String { "argv/\(leaf.canonicalCommand).json" }

    static func build() throws -> Coverage {
      let index = try LeafIndex()
      var entries: [Entry] = []

      // Daemon control methods.
      let methods = CLIControlMethodRegistry.classifiedMethods.sorted()
      for method in methods {
        guard let coverage = daemonMethodCoverage[method] else {
          throw Failure("daemon method \(method) has no coverage ruling")
        }
        entries.append(try daemonEntry(method: method, coverage: coverage, index: index))
      }
      for unknown in daemonMethodCoverage.keys.sorted()
      where !CLIControlMethodRegistry.classifiedMethods.contains(unknown) {
        throw Failure("coverage names a daemon method the registry does not classify: \(unknown)")
      }
      // Published Catalog operations.
      let operations = RuntimeOperationCatalog.operations.sorted { $0.reference < $1.reference }
      let submit = try index.leaf("job.submit")
      for descriptor in operations {
        let fronting = index.ordered.filter { $0.leaf.catalogOperation == descriptor.reference }
        var entry: Entry
        if let first = fronting.first {
          entry = Entry(
            feature: descriptor.reference,
            source: "catalog:\(descriptor.reference)",
            classification: classification(path: first.path, leaf: first.leaf),
            targetClassification: classification(path: first.path, leaf: first.leaf),
            lifecycle: lifecycle(of: first.leaf),
            targetCommand: targetCommand(path: first.path, leaf: first.leaf),
            equivalentCommands: fronting.dropFirst().map { targetCommand(path: $0.path, leaf: $0.leaf) },
            conformanceFixture: fixture(for: first.leaf),
            requiredPlatforms: requiredPlatforms(path: first.path, leaf: first.leaf),
            referencedLeaves: fronting.map(\.leaf.canonicalCommand))
        } else {
          for option in ["--operation", "--inputs-file"]
          where !submit.leaf.options.contains(where: { $0.name == option }) {
            throw Failure("job submit no longer accepts \(option); generic coverage is unreachable")
          }
          entry = Entry(
            feature: descriptor.reference,
            source: "catalog:\(descriptor.reference)",
            classification: ProductCoverageClassification.generic.rawValue,
            targetClassification: ProductCoverageClassification.generic.rawValue,
            lifecycle: "current",
            targetCommand:
              "arkdeck job submit --operation \(descriptor.reference) --inputs-file <path>",
            conformanceFixture: fixture(for: submit.leaf),
            requiredPlatforms: platformVocabulary,
            referencedLeaves: [])
        }
        if let alias = descriptor.aliasFor { entry.note = "alias of \(alias)" }
        entries.append(entry)
      }

      // App product capabilities.
      for capability in AppProductCapabilityRegistry.capabilities.sorted(by: { $0.id < $1.id }) {
        var resolved: [(path: [String], leaf: CLILeafSpec)] = []
        for pattern in capability.cliEquivalent {
          resolved.append(try index.resolve(pattern: pattern))
        }
        entries.append(
          Entry(
            feature: capability.id,
            source: "app:\(capability.surface)",
            classification: capability.classification.rawValue,
            targetClassification: capability.classification.rawValue,
            lifecycle: "current",
            targetCommand: capability.cliEquivalent.first,
            equivalentCommands: Array(capability.cliEquivalent.dropFirst()),
            conformanceFixture: resolved.first.map { fixture(for: $0.leaf) },
            requiredPlatforms: ["macos"],
            owner: capability.owner,
            note: capability.title,
            referencedLeaves: resolved.map(\.leaf.canonicalCommand)))
      }

      // Leaves nothing above reaches: they are features in their own right.
      let referenced = Set(entries.flatMap(\.referencedLeaves))
      for (path, leaf) in index.ordered where !referenced.contains(leaf.canonicalCommand) {
        var entry = Entry(
          feature: leaf.canonicalCommand,
          source: "cli:\(leaf.canonicalCommand)",
          classification: classification(path: path, leaf: leaf),
          targetClassification: classification(path: path, leaf: leaf),
          lifecycle: lifecycle(of: leaf),
          targetCommand: targetCommand(path: path, leaf: leaf),
          conformanceFixture: fixture(for: leaf),
          requiredPlatforms: requiredPlatforms(path: path, leaf: leaf),
          referencedLeaves: [leaf.canonicalCommand])
        switch leaf.kind {
        case .tombstone(let tombstone):
          entry.note = tombstone.replacementArgvPattern.map { "replaced by `\($0)`" }
            ?? tombstone.reason
        case .refused(let reason):
          entry.note = reason
        case .executable:
          if let replacement = leaf.replacementArgvPattern {
            entry.note = "superseded by `\(replacement)`"
          }
        }
        entries.append(entry)
      }

      try validate(entries, index: index)
      entries.sort { $0.feature < $1.feature }
      return Coverage(entries: entries, document: document(for: entries))
    }

    private static func daemonEntry(
      method: String, coverage: DaemonCoverage, index: LeafIndex
    ) throws -> Entry {
      switch coverage {
      case .leaf(let command, let lifecycleOverride, let note, let also):
        let found = try index.leaf(command)
        guard case .executable = found.leaf.kind else {
          throw Failure("daemon method \(method) is fronted by a non-executable leaf \(command)")
        }
        var equivalents: [String] = []
        for alias in also {
          let aliasLeaf = try index.leaf(alias)
          guard case .executable = aliasLeaf.leaf.kind, aliasLeaf.leaf.lifecycle != .current else {
            throw Failure("daemon method \(method) names \(alias) as a compatibility spelling, but it is current")
          }
          equivalents.append(targetCommand(path: aliasLeaf.path, leaf: aliasLeaf.leaf))
        }
        return Entry(
          feature: method,
          source: "daemon:\(method)",
          classification: classification(path: found.path, leaf: found.leaf),
          targetClassification: classification(path: found.path, leaf: found.leaf),
          lifecycle: lifecycleOverride ?? lifecycle(of: found.leaf),
          targetCommand: targetCommand(path: found.path, leaf: found.leaf),
          equivalentCommands: equivalents,
          conformanceFixture: fixture(for: found.leaf),
          requiredPlatforms: requiredPlatforms(path: found.path, leaf: found.leaf),
          note: note,
          referencedLeaves: [command] + also)
      case .plumbing(let behind, let note):
        let found = try index.leaf(behind)
        return Entry(
          feature: method,
          source: "daemon:\(method)",
          classification: ProductCoverageClassification.internal.rawValue,
          targetClassification: ProductCoverageClassification.internal.rawValue,
          lifecycle: lifecycle(of: found.leaf),
          targetCommand: targetCommand(path: found.path, leaf: found.leaf),
          conformanceFixture: fixture(for: found.leaf),
          requiredPlatforms: requiredPlatforms(path: found.path, leaf: found.leaf),
          note: note,
          referencedLeaves: [behind])
      case .refused(let command, let note):
        let found = try index.leaf(command)
        guard case .refused = found.leaf.kind else {
          throw Failure("daemon method \(method) is marked refused but \(command) is not a refused leaf")
        }
        return Entry(
          feature: method,
          source: "daemon:\(method)",
          classification: ProductCoverageClassification.refused.rawValue,
          targetClassification: ProductCoverageClassification.refused.rawValue,
          lifecycle: lifecycle(of: found.leaf),
          targetCommand: targetCommand(path: found.path, leaf: found.leaf),
          conformanceFixture: fixture(for: found.leaf),
          requiredPlatforms: requiredPlatforms(path: found.path, leaf: found.leaf),
          note: note,
          referencedLeaves: [command])
      }
    }

    private static func validate(_ entries: [Entry], index: LeafIndex) throws {
      var features: Set<String> = []
      let classifications = Set(classificationVocabulary)
      let lifecycles = Set(lifecycleVocabulary)
      for entry in entries {
        guard features.insert(entry.feature).inserted else {
          throw Failure("feature \(entry.feature) is covered twice")
        }
        guard classifications.contains(entry.classification),
          classifications.contains(entry.targetClassification)
        else { throw Failure("feature \(entry.feature) uses an unknown classification") }
        guard lifecycles.contains(entry.lifecycle) else {
          throw Failure("feature \(entry.feature) uses an unknown lifecycle \(entry.lifecycle)")
        }
        guard entry.classification == entry.targetClassification
          || entry.classification == ProductCoverageClassification.blocked.rawValue
        else {
          throw Failure("feature \(entry.feature) claims a target it has not reached")
        }
        for pattern in [entry.targetCommand].compactMap({ $0 }) + entry.equivalentCommands {
          _ = try index.resolve(pattern: pattern)
        }
        for command in entry.referencedLeaves { _ = try index.leaf(command) }
      }
      let referenced = Set(entries.flatMap(\.referencedLeaves))
      for entry in index.ordered where !referenced.contains(entry.leaf.canonicalCommand) {
        throw Failure("leaf \(entry.leaf.canonicalCommand) is not covered")
      }
    }

    private static func document(for entries: [Entry]) -> JSONValue {
      var byClassification: [String: Int64] = [:]
      var bySource: [String: Int64] = [:]
      for entry in entries {
        byClassification[entry.classification, default: 0] += 1
        let kind = String(entry.source.prefix { $0 != ":" })
        bySource[kind, default: 0] += 1
      }
      let blocked = entries
        .filter { $0.classification == ProductCoverageClassification.blocked.rawValue }
        .map { JSONValue.string($0.feature) }
      return .object([
        "schemaVersion": .string(featureCoverageSchemaVersion),
        "bundleVersion": .string(CLIProductVersion.machineContract),
        "cliVersion": .string(CLIProductVersion.product),
        "catalogDigest": .string(RuntimeOperationCatalog.catalogDigest),
        "commandRegistrySchemaVersion": .string(CLICommandRegistry.schemaVersion),
        "appCapabilityRegistrySchemaVersion": .string(AppProductCapabilityRegistry.schemaVersion),
        "classificationVocabulary": .array(classificationVocabulary.map(JSONValue.string)),
        "lifecycleVocabulary": .array(lifecycleVocabulary.map(JSONValue.string)),
        "platformVocabulary": .array(platformVocabulary.map(JSONValue.string)),
        "summary": .object([
          "entries": .integer(Int64(entries.count)),
          "byClassification": .object(byClassification.mapValues(JSONValue.integer)),
          "bySource": .object(bySource.mapValues(JSONValue.integer)),
          "blocked": .array(blocked),
          "fullFunction": .bool(blocked.isEmpty),
        ]),
        "entries": .array(entries.map(\.document)),
      ])
    }
  }

  // MARK: Argv fixtures

  enum ArgvFixtures {
    static func sample(for grammar: CLIValueGrammar) -> String {
      switch grammar {
      case .opaque: return "sample"
      case .positiveInteger(let range): return String(range.lowerBound)
      case .nonNegativeInteger(let range): return String(range.lowerBound)
      case .enumeration(let values): return values.first ?? "sample"
      case .hexDigest(let length): return String(repeating: "0", count: length)
      case .controlRequestID: return fixtureControlRequestID
      case .duration(let maximumMilliseconds): return maximumMilliseconds >= 1000 ? "1s" : "1ms"
      }
    }

    static func validArgv(path: [String], leaf: CLILeafSpec) -> [String] {
      var argv = path
      var present: Set<String> = []
      func add(_ option: CLIOptionSpec) {
        argv.append(option.name)
        present.insert(option.name)
        if case .value(_, let grammar) = option.form { argv.append(sample(for: grammar)) }
      }
      for option in leaf.options where option.isRequired && option.isPublished { add(option) }
      for group in leaf.requiresExactlyOneOf where !group.contains(where: present.contains) {
        if let option = leaf.options.first(where: { group.contains($0.name) }) { add(option) }
      }
      for positional in leaf.positionals where positional.isRequired {
        argv.append(sample(for: positional.grammar))
      }
      return argv
    }

    static func outcome(_ result: Result<CLIInvocation, CLIRegistryError>) -> JSONValue {
      switch result {
      case .success(let invocation):
        switch invocation {
        case .rootHelp:
          return .object(["outcome": .string("rootHelp")])
        case .nodeHelp(let node):
          return .object(["outcome": .string("nodeHelp"), "node": .string(node.token)])
        case .leafHelp(_, let leaf):
          return .object(["outcome": .string("leafHelp"), "command": .string(leaf.canonicalCommand)])
        case .version(let mode):
          return .object(["outcome": .string("version"), "outputMode": .string(mode.rawValue)])
        case .commands(let mode):
          return .object(["outcome": .string("commands"), "outputMode": .string(mode.rawValue)])
        case .completion(let shell):
          return .object(["outcome": .string("completion"), "shell": .string(shell)])
        case .dispatch(_, let leaf, let handlerArguments):
          return .object([
            "outcome": .string("dispatch"),
            "command": .string(leaf.canonicalCommand),
            "handlerArguments": .array(handlerArguments.map(JSONValue.string)),
          ])
        }
      case .failure(let error):
        var fields: [String: JSONValue] = [
          "outcome": .string("failure"),
          "code": .string(error.code.rawValue),
          "category": .string(error.code.category.machineCategory),
          "exitCode": .integer(Int64(error.exitCode)),
        ]
        if let command = error.command { fields["command"] = .string(command) }
        if error.lifecycle != .current { fields["lifecycleStatus"] = .string(error.lifecycle.rawValue) }
        if let replacement = error.replacementArgvPattern {
          fields["replacementArgvPattern"] = .string(replacement)
        }
        return .object(fields)
      }
    }

    static func document(path: [String], leaf: CLILeafSpec) throws -> JSONValue {
      let valid = validArgv(path: path, leaf: leaf)
      var cases: [(name: String, argv: [String])] = [("valid", valid), ("leafHelp", path + ["--help"])]
      if case .executable = leaf.kind {
        cases.append(("unknownOption", valid + ["--no-such-option"]))
        if let option = leaf.options.first(where: { $0.isRequired && $0.isPublished }) {
          var duplicate = valid + [option.name]
          if case .value(_, let grammar) = option.form { duplicate.append(sample(for: grammar)) }
          cases.append(("duplicateOption", duplicate))
        }
        if leaf.options.contains(where: { $0.isRequired && $0.isPublished })
          || !leaf.requiresExactlyOneOf.isEmpty
          || leaf.positionals.contains(where: \.isRequired)
        {
          cases.append(("missingRequired", path))
        }
        if leaf.options.contains(where: { $0.name == "--output" }), !leaf.outputModes.contains(.jsonl) {
          cases.append(("jsonlRefused", valid + ["--output", "jsonl"]))
        }
        if !leaf.connectsToRuntime, !leaf.options.contains(where: { $0.name == "--endpoint" }) {
          cases.append(("endpointRefused", valid + ["--endpoint", "local"]))
        }
        if let compatibility = leaf.options.first(where: { $0.stability == .macosCompatibilityOnly }),
          case .value(_, let grammar) = compatibility.form
        {
          cases.append(("macosCompatibilityOption", valid + [compatibility.name, sample(for: grammar)]))
        }
        let parsed = CLIArgumentParser.parse(valid)
        guard case .success(let invocation) = parsed else {
          throw Failure("the generated valid argv for \(leaf.canonicalCommand) is refused: \(valid)")
        }
        if case .dispatch(_, let dispatched, _) = invocation,
          dispatched.canonicalCommand != leaf.canonicalCommand
        {
          throw Failure("the generated valid argv for \(leaf.canonicalCommand) dispatches elsewhere")
        }
      }
      let rendered: [JSONValue] = cases.map { entry in
        .object([
          "name": .string(entry.name),
          "argv": .array(entry.argv.map(JSONValue.string)),
          "expected": outcome(CLIArgumentParser.parse(entry.argv)),
        ])
      }
      let kind: String
      switch leaf.kind {
      case .executable: kind = "executable"
      case .tombstone: kind = "tombstone"
      case .refused: kind = "refused"
      }
      return .object([
        "schemaVersion": .string(argvFixtureSchemaVersion),
        "cliVersion": .string(CLIProductVersion.product),
        "command": .string(leaf.canonicalCommand),
        "path": .array(path.map(JSONValue.string)),
        "kind": .string(kind),
        "lifecycleStatus": .string(FeatureCoverage.lifecycle(of: leaf)),
        "cases": .array(rendered),
      ])
    }
  }

  // MARK: Envelope fixtures

  enum EnvelopeFixtures {
    static func products() throws -> [Product] {
      let successEnvelope = CLIResultEnvelope.success(
        command: "job.status", result: SampleDocuments.jobStatus,
        controlRequestID: fixtureControlRequestID)
      let deprecatedEnvelope = CLIResultEnvelope.withLifecycle(
        CLIResultEnvelope.success(
          command: "cleanup-debt.list", result: SampleDocuments.emptySnapshotPage,
          controlRequestID: fixtureControlRequestID),
        .deprecated, replacement: "arkdeck recovery cleanup list")
      guard case .failure(let missingOption) = CLIArgumentParser.parse(["job", "status"]) else {
        throw Failure("`job status` without --job no longer fails at parse time")
      }
      guard case .failure(let removed) = CLIArgumentParser.parse(["agent", "chat"]) else {
        throw Failure("`agent chat` is no longer a tombstone")
      }
      let failureEnvelope = CLIResultEnvelope.failure(
        command: missingOption.command ?? CLIResultEnvelope.parsePhaseCommand,
        error: missingOption, controlRequestID: fixtureControlRequestID)
      let removedEnvelope = CLIResultEnvelope.withLifecycle(
        CLIResultEnvelope.failure(
          command: removed.command ?? CLIResultEnvelope.parsePhaseCommand,
          error: removed, controlRequestID: fixtureControlRequestID),
        removed.lifecycle, replacement: removed.replacementArgvPattern)
      let runtimeFailure = CLIRegistryError(
        code: .runtimeUnavailable,
        message: "the local Runtime did not answer",
        details: ["endpoint": .string("local"), "newDispatchCount": .integer(0)],
        command: "job.wait")
      let documents: [(String, String)] = [
        ("envelopes/result-success.json", CLIResultEnvelope.render(successEnvelope)),
        ("envelopes/result-deprecated-alias.json", CLIResultEnvelope.render(deprecatedEnvelope)),
        ("envelopes/result-argv-failure.json", CLIResultEnvelope.render(failureEnvelope)),
        ("envelopes/result-removed-command.json", CLIResultEnvelope.render(removedEnvelope)),
        (
          "envelopes/event-runtime-event.jsonl",
          CLIEventEnvelope.runtimeEvent(
            command: "job.watch", sequence: 1, fields: SampleDocuments.eventRow,
            controlRequestID: fixtureControlRequestID)
        ),
        (
          "envelopes/event-terminal-success.jsonl",
          CLIEventEnvelope.terminalSuccess(
            command: "job.wait", sequence: 2, result: SampleDocuments.jobStatus,
            controlRequestID: fixtureControlRequestID, lastCursor: SampleDocuments.eventCursor)
        ),
        (
          "envelopes/event-terminal-failure.jsonl",
          CLIEventEnvelope.terminalFailure(
            command: "job.wait", sequence: 1, error: runtimeFailure,
            controlRequestID: fixtureControlRequestID)
        ),
      ]
      return documents.map { Product(relativePath: $0.0, bytes: Data($0.1.utf8)) }
    }
  }

  // MARK: Sample documents (page and next-action shapes)

  enum SampleDocuments {
    static let jobID = "job-0f3c2a7e-4d1b-4c0a-9e2d-5b6a7c8d9e0f"
    static let eventCursor = "evc-1.job-0f3c2a7e.12"

    static let waitAction: JSONValue = .object([
      "kind": .string("wait"),
      "owner": .object(["kind": .string("job"), "id": .string(jobID)]),
      "resource": .object(["kind": .string("job"), "id": .string(jobID)]),
      "reasonCode": .string("job.running"),
      "retryAfter": .string("250ms"),
    ])

    static let humanAction: JSONValue = .object([
      "kind": .string("humanAction"),
      "owner": .object([
        "kind": .string("agentExecution"), "id": .string("exec-7a1d3f52-2c9e-4b8a-a1d0-3e4f5a6b7c8d"),
      ]),
      "resource": .object([
        "kind": .string("humanAction"), "id": .string("har-2b3c4d5e-6f70-4a8b-9c0d-1e2f3a4b5c6d"),
      ]),
      "reasonCode": .string("device.trustPending"),
      "resumeReference": .string("resume-9d8c7b6a-5f4e-4d3c-b2a1-0f9e8d7c6b5a"),
      "expiresAt": .string("2026-08-30T12:00:00Z"),
    ])

    static let reconcileAction: JSONValue = .object([
      "kind": .string("reconcile"),
      "owner": .object(["kind": .string("job"), "id": .string(jobID)]),
      "resource": .object(["kind": .string("job"), "id": .string(jobID)]),
      "reasonCode": .string("recovery.outcomeUnknown"),
    ])

    static let cleanupAction: JSONValue = .object([
      "kind": .string("cleanup"),
      "owner": .object(["kind": .string("job"), "id": .string(jobID)]),
      "resource": .object([
        "kind": .string("cleanupDebt"), "id": .string("debt-3c4d5e6f-7a8b-4c9d-8e0f-1a2b3c4d5e6f"),
      ]),
      "reasonCode": .string("recovery.cleanupDebt"),
    ])

    static let readResultAction: JSONValue = .object([
      "kind": .string("readResult"),
      "owner": .object(["kind": .string("job"), "id": .string(jobID)]),
      "resource": .object(["kind": .string("job"), "id": .string(jobID)]),
      "reasonCode": .string("job.resultAvailable"),
    ])

    static let nextActions: [(kind: String, document: JSONValue)] = [
      ("wait", waitAction),
      ("humanAction", humanAction),
      ("reconcile", reconcileAction),
      ("cleanup", cleanupAction),
      ("readResult", readResultAction),
    ]

    static let jobStatus: JSONValue = .object([
      "jobId": .string(jobID),
      "state": .string("running"),
      "operation": .string("observe.device@1"),
      "runtimeRevision": .string("12"),
      "nextAction": waitAction,
    ])

    static let eventRow: [String: JSONValue] = [
      "eventId": .string("evt-6c5b4a39-2817-4f0e-9d8c-7b6a5f4e3d2c"),
      "streamPosition": .string("12"),
      "runtimeRevision": .string("12"),
      "cursor": .string(eventCursor),
      "type": .string("job.stepCompleted"),
      "data": .object(["stepId": .string("observe-device"), "outcome": .string("verified")]),
    ]

    static let snapshotPage: JSONValue = .object([
      "schemaVersion": .string(pageSchemaVersion),
      "pageKind": .string("snapshot"),
      "items": .array([
        .object([
          "jobId": .string(jobID),
          "state": .string("running"),
          "createdAt": .string("2026-09-02T04:00:00Z"),
        ])
      ]),
      "order": .string("createdAtDescJobIdAsc"),
      "snapshotRevision": .string("rev-000000000012"),
      "hasMore": .bool(false),
      "nextCursor": .null,
    ])

    static let emptySnapshotPage: JSONValue = .object([
      "schemaVersion": .string(pageSchemaVersion),
      "pageKind": .string("snapshot"),
      "items": .array([]),
      "order": .string("createdAtDescJobIdAsc"),
      "snapshotRevision": .string("rev-000000000012"),
      "hasMore": .bool(false),
      "nextCursor": .null,
    ])

    static let eventStreamPage: JSONValue = .object([
      "schemaVersion": .string(pageSchemaVersion),
      "pageKind": .string("eventStream"),
      "items": .array([.object(eventRow)]),
      "order": .string("streamPositionAsc"),
      "snapshotRevision": .string("12"),
      "hasMore": .bool(false),
      "nextCursor": .string(eventCursor),
    ])

    static func products() -> [Product] {
      var products = nextActions.map { action in
        Product(
          relativePath: "next-action/\(action.kind).json",
          bytes: ContractJSON.document(action.document))
      }
      products.append(
        Product(relativePath: "next-action/null.json", bytes: ContractJSON.document(.null)))
      products.append(
        Product(relativePath: "page/snapshot.json", bytes: ContractJSON.document(snapshotPage)))
      products.append(
        Product(relativePath: "page/event-stream.json", bytes: ContractJSON.document(eventStreamPage)))
      return products
    }
  }

  // MARK: JSON Schemas

  enum Schemas {
    static let draft = "https://json-schema.org/draft/2020-12/schema"
    static let commandPattern = "^[a-z][a-z0-9-]*(\\.[a-z][a-z0-9-]*)*$"
    static let controlRequestIDPattern = "^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$"
    static let durationPattern = "^[1-9][0-9]*(ms|s|m|h)$"
    static let decimalPositionPattern = "^[1-9][0-9]*$"

    static func strings(_ values: [String]) -> JSONValue { .array(values.map(JSONValue.string)) }

    static func header(_ title: String, description: String) -> [String: JSONValue] {
      [
        "$schema": .string(draft),
        "$comment": .string(generatedNotice),
        "title": .string(title),
        "description": .string(description),
        "x-arkdeck-bundleVersion": .string(CLIProductVersion.machineContract),
        "x-arkdeck-cliVersion": .string(CLIProductVersion.product),
      ]
    }

    static let errorObject: JSONValue = .object([
      "type": .string("object"),
      "required": strings(["code", "message", "controlRequestRetryable", "attentionRequired"]),
      "properties": .object([
        "code": .object(["enum": strings(CLIErrorCode.allCases.map(\.rawValue))]),
        "message": .object(["type": .string("string")]),
        "controlRequestRetryable": .object(["type": .string("boolean")]),
        "attentionRequired": .object(["type": .string("boolean")]),
        "details": .object(["type": .string("object")]),
      ]),
      "additionalProperties": .bool(false),
    ])

    static let lifecycleObject: JSONValue = .object([
      "type": .string("object"),
      "required": strings(["status", "replacementArgvPattern", "removalVersion"]),
      "properties": .object([
        "status": .object(["enum": strings(["deprecated", "legacy"])]),
        "replacementArgvPattern": .object(["type": strings(["string", "null"])]),
        "removalVersion": .object(["type": strings(["string", "null"])]),
      ]),
      "additionalProperties": .bool(false),
    ])

    static var result: JSONValue {
      var fields = header(
        CLIResultEnvelope.schemaVersion,
        description: "The single result document a machine-mode invocation writes to stdout (§8.1, §8.2).")
      fields["type"] = .string("object")
      fields["required"] = strings(["schemaVersion", "command", "ok", "meta"])
      fields["properties"] = .object([
        "schemaVersion": .object(["const": .string(CLIResultEnvelope.schemaVersion)]),
        "command": .object(["type": .string("string"), "pattern": .string(commandPattern)]),
        "ok": .object(["type": .string("boolean")]),
        "result": .object([:]),
        "error": .object(["$ref": .string("#/$defs/error")]),
        "meta": .object(["$ref": .string("#/$defs/meta")]),
      ])
      fields["additionalProperties"] = .bool(false)
      fields["oneOf"] = .array([
        .object([
          "properties": .object(["ok": .object(["const": .bool(true)])]),
          "required": strings(["result"]),
          "not": .object(["required": strings(["error"])]),
        ]),
        .object([
          "properties": .object(["ok": .object(["const": .bool(false)])]),
          "required": strings(["error"]),
          "not": .object(["required": strings(["result"])]),
        ]),
      ])
      fields["$defs"] = .object([
        "error": errorObject,
        "lifecycle": lifecycleObject,
        "meta": .object([
          "type": .string("object"),
          "required": strings(["controlRequestId", "cliVersion"]),
          "properties": .object([
            "controlRequestId": .object([
              "type": .string("string"), "pattern": .string(controlRequestIDPattern),
            ]),
            "cliVersion": .object(["type": .string("string")]),
            "controlProtocolVersion": .object([
              "const": .string(CLIProductVersion.controlProtocolVersion)
            ]),
            "lifecycle": .object(["$ref": .string("#/$defs/lifecycle")]),
          ]),
          "additionalProperties": .bool(false),
        ]),
        "errorRegistryVersion": .object(["const": .string(CLIErrorRegistryVersion.current)]),
      ])
      return .object(fields)
    }

    static let eventItem: JSONValue = .object([
      "type": .string("object"),
      "required": strings(["eventId", "streamPosition", "cursor", "type"]),
      "properties": .object([
        "eventId": .object(["type": .string("string"), "minLength": .integer(1)]),
        "streamPosition": .object([
          "type": .string("string"), "pattern": .string(decimalPositionPattern),
        ]),
        "runtimeRevision": .object(["type": .string("string")]),
        "cursor": .object(["type": .string("string"), "minLength": .integer(1)]),
        "type": .object(["type": .string("string"), "minLength": .integer(1)]),
        "data": .object([:]),
      ]),
    ])

    static var page: JSONValue {
      var fields = header(
        pageSchemaVersion,
        description: "The fixed page shape every list and events result uses (§7.3).")
      fields["type"] = .string("object")
      fields["required"] = strings([
        "schemaVersion", "pageKind", "items", "order", "snapshotRevision", "hasMore", "nextCursor",
      ])
      fields["properties"] = .object([
        "schemaVersion": .object(["const": .string(pageSchemaVersion)]),
        "pageKind": .object(["enum": strings(["snapshot", "eventStream"])]),
        "items": .object(["type": .string("array")]),
        "order": .object(["type": .string("string"), "minLength": .integer(1)]),
        "snapshotRevision": .object(["type": .string("string")]),
        "hasMore": .object(["type": .string("boolean")]),
        "nextCursor": .object(["type": strings(["string", "null"])]),
      ])
      fields["additionalProperties"] = .bool(false)
      fields["allOf"] = .array([
        .object([
          "if": .object(["properties": .object(["pageKind": .object(["const": .string("eventStream")])])]),
          "then": .object([
            "properties": .object([
              "order": .object(["const": .string("streamPositionAsc")]),
              "nextCursor": .object(["type": .string("string"), "minLength": .integer(1)]),
              "items": .object(["items": .object(["$ref": .string("#/$defs/eventItem")])]),
            ])
          ]),
        ]),
        .object([
          "if": .object([
            "properties": .object([
              "pageKind": .object(["const": .string("snapshot")]),
              "hasMore": .object(["const": .bool(false)]),
            ])
          ]),
          "then": .object(["properties": .object(["nextCursor": .object(["type": .string("null")])])]),
        ]),
        .object([
          "if": .object(["properties": .object(["hasMore": .object(["const": .bool(true)])])]),
          "then": .object([
            "properties": .object(["nextCursor": .object(["type": .string("string"), "minLength": .integer(1)])])
          ]),
        ]),
      ])
      fields["$defs"] = .object(["eventItem": eventItem])
      return .object(fields)
    }

    static var event: JSONValue {
      var fields = header(
        CLIEventEnvelope.schemaVersion,
        description: "One JSONL line of a streaming invocation: a Runtime event or the single terminal frame (§8.3).")
      let common: [String: JSONValue] = [
        "schemaVersion": .object(["const": .string(CLIEventEnvelope.schemaVersion)]),
        "sequence": .object(["type": .string("integer"), "minimum": .integer(1)]),
        "type": .object(["type": .string("string"), "minLength": .integer(1)]),
        "command": .object(["type": .string("string"), "pattern": .string(commandPattern)]),
        "controlRequestId": .object([
          "type": .string("string"), "pattern": .string(controlRequestIDPattern),
        ]),
      ]
      var terminalProperties = common
      terminalProperties["type"] = .object(["const": .string("terminal")])
      terminalProperties["ok"] = .object(["type": .string("boolean")])
      terminalProperties["exitCode"] = .object([
        "type": .string("integer"), "minimum": .integer(0), "maximum": .integer(255),
      ])
      terminalProperties["lastCursor"] = .object(["type": strings(["string", "null"])])
      terminalProperties["result"] = .object([:])
      terminalProperties["error"] = .object(["$ref": .string("#/$defs/error")])
      var eventProperties = common
      for (key, value) in eventItemProperties { eventProperties[key] = value }
      fields["type"] = .string("object")
      fields["required"] = strings(["schemaVersion", "sequence", "type", "command", "controlRequestId"])
      fields["oneOf"] = .array([
        .object(["$ref": .string("#/$defs/terminalFrame")]),
        .object(["$ref": .string("#/$defs/runtimeEventFrame")]),
      ])
      fields["$defs"] = .object([
        "error": errorObject,
        "terminalFrame": .object([
          "type": .string("object"),
          "required": strings([
            "schemaVersion", "sequence", "type", "command", "controlRequestId", "ok", "exitCode",
            "lastCursor",
          ]),
          "properties": .object(terminalProperties),
          "additionalProperties": .bool(false),
          "oneOf": .array([
            .object([
              "properties": .object(["ok": .object(["const": .bool(true)])]),
              "required": strings(["result"]),
              "not": .object(["required": strings(["error"])]),
            ]),
            .object([
              "properties": .object(["ok": .object(["const": .bool(false)])]),
              "required": strings(["error"]),
              "not": .object(["required": strings(["result"])]),
            ]),
          ]),
        ]),
        "runtimeEventFrame": .object([
          "type": .string("object"),
          "required": strings([
            "schemaVersion", "sequence", "type", "command", "controlRequestId", "eventId",
            "streamPosition", "cursor",
          ]),
          "properties": .object(eventProperties),
          "not": .object(["properties": .object(["type": .object(["const": .string("terminal")])])]),
        ]),
      ])
      return .object(fields)
    }

    private static var eventItemProperties: [String: JSONValue] {
      guard case .object(let fields) = eventItem, case .object(let properties)? = fields["properties"]
      else { return [:] }
      return properties
    }

    static func ownerObject(kinds: [String]) -> JSONValue {
      .object([
        "type": .string("object"),
        "required": strings(["kind", "id"]),
        "properties": .object([
          "kind": .object(["enum": strings(kinds)]),
          "id": .object(["type": .string("string"), "minLength": .integer(1)]),
        ]),
        "additionalProperties": .bool(false),
      ])
    }

    /// One closed branch of the §7.3 union.
    static func branch(
      kind: String, ownerKinds: [String], resourceKinds: [String], reasonCodes: [String]?,
      extra: [String: JSONValue], required: [String], resourceMirrorsOwner: Bool
    ) -> JSONValue {
      var properties: [String: JSONValue] = [
        "kind": .object(["const": .string(kind)]),
        "owner": ownerObject(kinds: ownerKinds),
        "resource": ownerObject(kinds: resourceKinds),
        "reasonCode": reasonCodes.map { .object(["enum": strings($0)]) }
          ?? .object(["type": .string("string"), "minLength": .integer(1)]),
      ]
      for (key, value) in extra { properties[key] = value }
      var fields: [String: JSONValue] = [
        "type": .string("object"),
        "required": strings(["kind", "owner", "resource", "reasonCode"] + required),
        "properties": .object(properties),
        "additionalProperties": .bool(false),
      ]
      if resourceMirrorsOwner {
        fields["allOf"] = .array(
          ownerKinds.map { ownerKind in
            .object([
              "if": .object([
                "properties": .object([
                  "owner": .object(["properties": .object(["kind": .object(["const": .string(ownerKind)])])])
                ])
              ]),
              "then": .object([
                "properties": .object([
                  "resource": .object(["properties": .object(["kind": .object(["const": .string(ownerKind)])])])
                ])
              ]),
            ])
          })
      }
      return .object(fields)
    }

    static var nextAction: JSONValue {
      var fields = header(
        nextActionSchemaVersion,
        description: "The closed nextAction union shared by job status and agent status; null when nothing is pending (§7.3).")
      let executionOwners = ["job", "agentExecution", "controlAction"]
      fields["oneOf"] = .array([
        .object(["type": .string("null")]),
        .object(["$ref": .string("#/$defs/wait")]),
        .object(["$ref": .string("#/$defs/humanAction")]),
        .object(["$ref": .string("#/$defs/reconcile")]),
        .object(["$ref": .string("#/$defs/cleanup")]),
        .object(["$ref": .string("#/$defs/readResult")]),
      ])
      fields["$defs"] = .object([
        "wait": branch(
          kind: "wait", ownerKinds: executionOwners, resourceKinds: executionOwners,
          reasonCodes: ["job.running", "agent.orchestrationPending", "lifecycle.pending"],
          extra: ["retryAfter": .object(["type": .string("string"), "pattern": .string(durationPattern)])],
          required: ["retryAfter"], resourceMirrorsOwner: true),
        "humanAction": branch(
          kind: "humanAction", ownerKinds: executionOwners, resourceKinds: ["humanAction"],
          reasonCodes: nil,
          extra: [
            "resumeReference": .object(["type": .string("string"), "minLength": .integer(1)]),
            "expiresAt": .object([
              "type": strings(["string", "null"]), "format": .string("date-time"),
            ]),
          ],
          required: ["resumeReference", "expiresAt"], resourceMirrorsOwner: false),
        "reconcile": branch(
          kind: "reconcile", ownerKinds: ["job", "controlAction"], resourceKinds: ["job", "controlAction"],
          reasonCodes: ["recovery.outcomeUnknown", "lifecycle.outcomeUnknown"],
          extra: [:], required: [], resourceMirrorsOwner: true),
        "cleanup": branch(
          kind: "cleanup", ownerKinds: ["job"], resourceKinds: ["cleanupDebt"],
          reasonCodes: ["recovery.cleanupDebt"], extra: [:], required: [],
          resourceMirrorsOwner: false),
        "readResult": branch(
          kind: "readResult", ownerKinds: ["job"], resourceKinds: ["job"],
          reasonCodes: ["job.resultAvailable"], extra: [:], required: [],
          resourceMirrorsOwner: false),
      ])
      return .object(fields)
    }

    static var controlPlane: JSONValue {
      var fields = header(
        controlPlaneSchemaVersion,
        description: "The local control-plane request and response frames the CLI exchanges with the Runtime, and the closed method set it may name.")
      let methods = ArkDeckControlProtocol.methods.sorted()
      let methodTable: [JSONValue] = methods.map { method in
        .object([
          "method": .string(method),
          "published": .bool(true),
        ])
      }
      fields["oneOf"] = .array([
        .object(["$ref": .string("#/$defs/request")]),
        .object(["$ref": .string("#/$defs/response")]),
      ])
      fields["x-arkdeck-currentProtocolVersion"] = .string(ArkDeckControlProtocol.currentVersion)
      fields["x-arkdeck-contractIdentity"] = .string(ArkDeckControlProtocol.contractIdentity)
      fields["x-arkdeck-methods"] = .array(methodTable)
      fields["$defs"] = .object([
        "request": .object([
          "type": .string("object"),
          "required": strings(["protocolVersion", "contractIdentity", "id", "method"]),
          "properties": .object([
            "protocolVersion": .object(["const": .string(ArkDeckControlProtocol.currentVersion)]),
            "contractIdentity": .object(["const": .string(ArkDeckControlProtocol.contractIdentity)]),
            "id": .object(["type": .string("string"), "minLength": .integer(1)]),
            "method": .object(["enum": strings(methods)]),
            "params": .object(["type": .string("object")]),
          ]),
          "additionalProperties": .bool(false),
        ]),
        "response": .object([
          "type": .string("object"),
          "required": strings(["id", "ok"]),
          "properties": .object([
            "id": .object(["type": .string("string"), "minLength": .integer(1)]),
            "ok": .object(["type": .string("boolean")]),
            "result": .object([:]),
            "error": .object(["$ref": .string("#/$defs/wireError")]),
          ]),
          "additionalProperties": .bool(false),
          "oneOf": .array([
            .object([
              "properties": .object(["ok": .object(["const": .bool(true)])]),
              "required": strings(["result"]),
              "not": .object(["required": strings(["error"])]),
            ]),
            .object([
              "properties": .object(["ok": .object(["const": .bool(false)])]),
              "required": strings(["error"]),
              "not": .object(["required": strings(["result"])]),
            ]),
          ]),
        ]),
        "wireError": .object([
          "type": .string("object"),
          "required": strings(["code", "message"]),
          "properties": .object([
            "code": .object(["type": .string("string"), "minLength": .integer(1)]),
            "message": .object(["type": .string("string")]),
            "details": .object(["type": .string("object")]),
          ]),
          "additionalProperties": .bool(false),
        ]),
      ])
      return .object(fields)
    }
  }
}

// MARK: - Deterministic renderers

/// Pretty JSON with keys in `arkdeck.cli.canonical-json/1` order (UTF-16 code
/// unit), two-space indentation and one trailing LF. Scalars are rendered by
/// the canonical encoder so a port re-encoding a product reproduces it.
enum ContractJSON {
  static func document(_ value: JSONValue) -> Data {
    var out = ""
    render(value, indent: 0, into: &out)
    out += "\n"
    return Data(out.utf8)
  }

  static func scalar(_ value: JSONValue) -> String {
    (try? CLICanonicalJSON.canonicalString(value)) ?? "null"
  }

  static func sortedKeys(_ fields: [String: JSONValue]) -> [String] {
    fields.keys.sorted { $0.utf16.lexicographicallyPrecedes($1.utf16) }
  }

  private static func render(_ value: JSONValue, indent: Int, into out: inout String) {
    let pad = String(repeating: "  ", count: indent)
    switch value {
    case .object(let fields):
      guard !fields.isEmpty else { out += "{}"; return }
      out += "{\n"
      let keys = sortedKeys(fields)
      for (offset, key) in keys.enumerated() {
        out += pad + "  " + scalar(.string(key)) + ": "
        render(fields[key]!, indent: indent + 1, into: &out)
        out += offset == keys.count - 1 ? "\n" : ",\n"
      }
      out += pad + "}"
    case .array(let items):
      guard !items.isEmpty else { out += "[]"; return }
      out += "[\n"
      for (offset, item) in items.enumerated() {
        out += pad + "  "
        render(item, indent: indent + 1, into: &out)
        out += offset == items.count - 1 ? "\n" : ",\n"
      }
      out += pad + "]"
    default:
      out += scalar(value)
    }
  }
}

/// The YAML subset the bundle uses: block mappings and sequences whose every
/// scalar — keys included — is a JSON scalar. YAML 1.2 double-quoted scalars
/// share JSON's escapes, so the same canonical encoder renders both products
/// and a YAML reader and a JSON reader see the same values.
enum ContractYAML {
  static func document(_ value: JSONValue) -> Data {
    var out = "# \(CLIMachineContracts.generatedNotice)\n"
    out += lines(value).joined(separator: "\n") + "\n"
    return Data(out.utf8)
  }

  private static func isScalar(_ value: JSONValue) -> Bool {
    switch value {
    case .object(let fields): return fields.isEmpty
    case .array(let items): return items.isEmpty
    default: return true
    }
  }

  private static func scalar(_ value: JSONValue) -> String {
    switch value {
    case .object: return "{}"
    case .array: return "[]"
    default: return ContractJSON.scalar(value)
    }
  }

  static func lines(_ value: JSONValue) -> [String] {
    switch value {
    case .object(let fields):
      guard !fields.isEmpty else { return ["{}"] }
      var out: [String] = []
      for key in ContractJSON.sortedKeys(fields) {
        let child = fields[key]!
        let rendered = ContractJSON.scalar(.string(key))
        if isScalar(child) {
          out.append("\(rendered): \(scalar(child))")
        } else {
          out.append("\(rendered):")
          out += lines(child).map { "  " + $0 }
        }
      }
      return out
    case .array(let items):
      guard !items.isEmpty else { return ["[]"] }
      var out: [String] = []
      for item in items {
        if isScalar(item) {
          out.append("- \(scalar(item))")
        } else {
          let nested = lines(item)
          out.append("- " + nested[0])
          out += nested.dropFirst().map { "  " + $0 }
        }
      }
      return out
    default:
      return [scalar(value)]
    }
  }
}
