"""Synthetic journals only: no device, no daemon, no CLI image is run.

Run from `scripts`: `python -m unittest discover -s gj_record -t .`
"""

from __future__ import annotations

import base64
import hashlib
import json
import os
import subprocess
import tempfile
import unittest
from pathlib import Path

from gj_record import capture, catalog, journeys, record, redact
from gj_record.criteria import DEFECT, INCOMPLETE, NOT_STARTED, PASS

DATE = "2026-10-05"
D = "20261005"
CLI = "c" * 64
HDC = "c79518498aaf4e719733961216444e70c3eb53c8ba7006b933e6d7f2e1c6101e"
DAEMON = "d" * 64
TARGET = "TGT-0123456789ab"
IDENTITY = "e" * 64
CONNECT_KEY = "7001005458323933328a01d8"
OPERATIONS = (
    "analyzer.extract-crash-signature",
    "capture.diagnostics",
    "debug.hap",
    "deploy.native-library.app-owned",
    "flash.full-restore",
    "input.tap",
    "observe.device",
    "workspace.apply-patch",
    "workspace.build-openharmony",
    "workspace.prepare-isolated-copy",
    "workspace.sign-openharmony-hap",
)


def sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def generated(operations=OPERATIONS) -> tuple[str, str]:
    canonical = json.dumps([{"id": o, "version": 1} for o in operations], separators=(",", ":"))
    digest = sha(canonical.encode())
    text = (
        "// Generated by scripts/catalog_gen/generate.py. Do not edit.\n"
        f'pub const CATALOG_DIGEST: &str = "{digest}";\n'
        f'pub const CATALOG_CANONICAL_JSON: &str = r#"{canonical}"#;\n'
    )
    return digest, text


def fixture_inspection(*, abi="armeabi-v7a", digest=record.ROLLBACK_FIXTURE_SHA256):
    # Start with the real producer's complete current closed projection. Only
    # this synthetic journal's request/content/binding are substituted; the
    # committed contract corpus and its pins are never changed.
    source = Path(__file__).resolve().parents[2] / (
        "Packages/ArkDeckKit/Tests/ArkDeckContractTests/Fixtures/ControlFrames/artifact.import.inspection.jsonl")
    frames = [json.loads(line) for line in source.read_text(encoding="utf-8").splitlines()]
    value = next(frame["result"] for frame in frames if frame.get("ok") is True
                 and frame["result"]["import"]["metadata"]["kind"] == "native-library")
    imported = value["import"]
    request = f"gj3-{D}-fixture"
    imported["importRequestId"] = request
    metadata, receipt = imported["metadata"], imported["receipt"]
    for fields in (metadata, receipt):
        fields.update(importRequestId=request, targetId=TARGET, bindingRevision="1",
                      name="libarkdeck_gj-rollback-ghost.signed.so")
    metadata["sha256"] = receipt["artifactDigest"] = digest
    imported["metadataFingerprint"] = sha(json.dumps(metadata, sort_keys=True, separators=(",", ":")).encode())
    receipt["validation"].update(abi=abi, elfClassBits=32 if abi == "armeabi-v7a" else 64,
                                machine=40 if abi == "armeabi-v7a" else 183)
    return value


def git(repo: Path, *args: str) -> str:
    return subprocess.run(
        ["git", "-C", str(repo), *args], check=True, capture_output=True, text=True
    ).stdout.strip()


class Repository:
    """A throwaway repository whose `main` publishes a synthetic Catalog."""

    def __init__(self, root: Path):
        self.path = root / "repo"
        self.path.mkdir()
        git(self.path, "init", "-q", "-b", "main")
        git(self.path, "config", "user.email", "t@example.invalid")
        git(self.path, "config", "user.name", "t")
        git(self.path, "config", "commit.gpgsign", "false")
        self.commits = 0
        self.digest, text = generated()
        self.revision = self.commit(text)

    def commit(self, text: str) -> str:
        path = self.path / catalog.GENERATED_RUST
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        git(self.path, "add", "-A")
        # Strictly increasing commit dates. One suite run on Windows saw an
        # ancestor reported off `main` (not reproduced in 15 tries alone);
        # git's ancestry walk uses commit dates, so same-second commits are
        # ruled out rather than relied on.
        self.commits += 1
        stamp = f"2026-10-05T00:00:{self.commits:02d}Z"
        environment = {**os.environ, "GIT_AUTHOR_DATE": stamp, "GIT_COMMITTER_DATE": stamp}
        subprocess.run(["git", "-C", str(self.path), "commit", "-q", "-m", "catalog"],
                       check=True, capture_output=True, env=environment)
        return git(self.path, "rev-parse", "HEAD")


class Journal:
    """Writes what `capture` would have written, envelope by envelope."""

    def __init__(self, out: Path, digest: str):
        self.out = out
        self.digest = digest
        out.mkdir(parents=True, exist_ok=True)
        self.sequence = 0
        self.artifacts = 0

    def step(self, arguments, envelope, exit_code=0, **extra) -> Path:
        self.sequence += 1
        name = f"{self.sequence:04d}-s.json"
        data = json.dumps(envelope).encode()
        (self.out / name).write_bytes(data)
        entry = {
            "schemaVersion": capture.ENTRY_SCHEMA,
            "sequence": self.sequence,
            "step": "s",
            "arguments": list(arguments) + ["--output", "json"],
            "cliExecutableSHA256": CLI,
            "exitCode": exit_code,
            "startedAtUtc": "2026-10-05T01:00:00.000000Z",
            "finishedAtUtc": "2026-10-05T01:00:01.000000Z",
            "stdoutFile": name,
            "stdoutSHA256": sha(data),
            "host": {"system": "Windows", "release": "11", "version": "10.0.26200"},
        }
        entry.update(extra)
        with open(self.out / capture.JOURNAL, "a", encoding="utf-8") as handle:
            handle.write(json.dumps(entry) + "\n")
        return self.out / name

    def ok(self, command, arguments, result, **extra):
        envelope = {"schemaVersion": "arkdeck.cli.result/1", "command": command, "ok": True,
                    "result": result, "meta": {"controlRequestId": "x", "cliVersion": "0.1.0"}}
        return self.step(arguments, envelope, **extra)

    def error(self, command, arguments, code, message, details, exit_code):
        envelope = {"schemaVersion": "arkdeck.cli.result/1", "command": command, "ok": False,
                    "error": {"code": code, "message": message, "details": details},
                    "meta": {"controlRequestId": "x", "cliVersion": "0.1.0"}}
        return self.step(arguments, envelope, exit_code=exit_code)

    # -- fixed facts ---------------------------------------------------------

    def facts(self, *, root_kind="account", operations=OPERATIONS):
        self.ok("version", ["--version"], {"buildIdentity": f"sha256:{CLI}"})
        self.ok("runtime.health", ["runtime", "health"], {"catalogDigest": self.digest, "status": "ok"})
        self.ok("operation.list", ["operation", "list"], [
            {"reference": f"{o}@1", "canonicalReference": f"{o}@1", "aliasFor": None,
             "availability": "available", "reasonCodes": []} for o in operations
        ])
        self.ok("runtime.service.status", ["runtime", "service", "status"], {
            "daemonService": {"startMode": "clientStarted", "daemonPath": "C:\\Users\\someone\\rc\\arkdeck-agentd.exe",
                              "daemonImage": {"verified": True, "pin": "signer"},
                              "stateRoot": {"kind": root_kind, "path": "C:\\Users\\someone\\AppData\\Local\\ArkDeck\\Agentd"}},
            "daemonHealth": {"catalogDigest": self.digest, "status": "ok"},
        }, daemonImageSHA256=DAEMON)
        self.ok("runtime.hdc.status", ["runtime", "hdc", "status"], {
            "availability": "available", "executableSHA256": HDC, "configuredExecutableSHA256": HDC,
            "clientVersion": "3.2.0g", "executablePath": "C:\\DevEco\\hdc.exe", "ownership": "arkDeckManaged",
        })
        self.ok("device.candidates", ["device", "candidates"], {
            "observations": [{"candidateKey": CONNECT_KEY, "displayName": "DAYU200 at desk"}]})
        self.target_show()

    def target_show(self, revision=1):
        self.ok("target.show", ["target", "show", "--target", TARGET], {
            "targetId": TARGET, "bindingRevision": revision, "connectKey": CONNECT_KEY,
            "stablePhysicalIdentitySha256": IDENTITY})

    # -- Jobs ----------------------------------------------------------------

    def evidence(self, job, operation, terminal="succeeded", kinds=None, **observation):
        return {
            "schemaVersion": "arkdeck.job-evidence/1", "jobId": job, "operationReference": operation,
            "catalogDigest": self.digest, "targetId": TARGET, "bindingRevision": 1, "executionMode": "execute",
            "terminalState": terminal, "outcomeUnknown": False, "blockers": [],
            "status": "verified" if terminal == "succeeded" else "blocked", "inventoryAvailable": True,
            "missingRequiredArtifacts": [],
            "actualEffect": "readOnly", "actualStepKinds": kinds or ["probeDevice"],
            "startedAtUtc": "2026-10-05T01:00:00Z", "finishedAtUtc": "2026-10-05T01:00:02Z",
            "observation": {"toolSha256": HDC, "targetId": TARGET, "bindingRevision": 1, **observation},
        }

    def job(self, execution, operation, artifacts, *, terminal="succeeded", timeline=None, kinds=None,
            observation=None, read=True, corrupt=None, settle=True, target=True, inputs=None):
        job = f"job-{sha(execution.encode())[:32]}"
        evidence = self.evidence(job, operation, terminal, kinds, **(observation or {}))
        state = "completed" if terminal == "succeeded" else "failed"
        arguments = ["agent", "run", "--operation", operation, "--execution-id", execution]
        if target:
            arguments += ["--target", TARGET]
        if settle:
            self.ok("agent.run", arguments, {
                "executionId": execution, "operation": operation, "state": state, "jobId": job,
                "jobState": terminal, "outcomeUnknown": False, "targetId": TARGET, "bindingRevision": 1,
                "catalogDigest": self.digest, "evidence": evidence, "humanAction": None, "nextAction": None,
                "job": {"jobId": job, "outstandingResidueCount": 0, "state": terminal}})
        rows = []
        for name, data in artifacts.items():
            self.artifacts += 1
            identifier = f"ART-{self.artifacts:04d}"
            rows.append({"artifactId": identifier, "name": name, "sha256": sha(data), "bytesVerified": True,
                         "byteCount": str(len(data)), "status": "published"})
        self.ok("job.result", ["job", "result", "--job", job], {
            "job": {"jobId": job, "outstandingResidueCount": 0, "executionMode": "execute", "state": terminal},
            "evidence": evidence, "artifacts": rows})
        if timeline is not None:
            self.ok("job.show", ["job", "show", "--job", job], {
                "job": {"jobId": job}, "catalogDigest": self.digest, "actualStepKinds": kinds,
                "request": {"inputs": inputs or {}},
                "timeline": {"kind": "inline", "entries": timeline}})
        if read:
            for row, (name, data) in zip(rows, artifacts.items()):
                served = data
                digest = row["sha256"] if name != corrupt else sha(b"other")
                self.ok("artifact.read", ["artifact", "read", "--job", job, "--artifact", row["artifactId"]], {
                    "artifactId": row["artifactId"], "artifactDigest": digest, "base64": base64.b64encode(served).decode(),
                    "byteCount": len(served), "offset": 0, "eof": True, "nextOffset": len(served),
                    "totalByteCount": len(served)})
        return job

    # -- Journeys --------------------------------------------------------------

    def gj1(self, *, har_exit=75, capture=True, resolved="resolvedByFreshProbe"):
        observe = self.job(f"gj1-{D}", "observe.device@1", {
            "device-facts.json": b"{}", "tool-facts.json": b"{}", "binding-snapshot.json": b"{}"})
        self.ok("runtime.service.verify", ["runtime", "service", "verify", "--job", observe], {"verified": True})
        jobs = [observe]
        if capture:
            jobs.append(self.job(f"gj1-{D}-capture", "capture.diagnostics@1", {
                "hilog.txt": b"log line", "ui-dump.json": b"{}",
                "capture-summary.json": json.dumps({"completeness": "complete", "missingRequired": []}).encode()}))
        self.ok("runtime.service.restart", ["runtime", "service", "restart"], {"restarted": True})
        for job in jobs:
            self.ok("job.show", ["job", "show", "--job", job], {"job": {"jobId": job}, "catalogDigest": self.digest,
                                                                "timeline": {"kind": "inline", "entries": []}})
            self.ok("job.result", ["job", "result", "--job", job], self._reread(job))
        self.har(har_exit, resolved)

    def _reread(self, job):
        # The same answer the Job gave before the restart.
        for entry in reversed(json.loads("[" + ",".join(
                (self.out / capture.JOURNAL).read_text().splitlines()) + "]")):
            data = json.loads((self.out / entry["stdoutFile"]).read_text())
            if data.get("command") == "job.result" and data["result"]["job"]["jobId"] == job:
                return data["result"]
        raise AssertionError(job)

    def har(self, exit_code=75, resolved="resolvedByFreshProbe"):
        execution = f"gj1-{D}-har"
        action = {"actionId": "har-1", "category": "physicalConnection", "status": "waiting",
                  "newDispatchCount": 0, "resumeReference": "resume-1", "reasonCode": "device.notObserved"}
        self.error("agent.run", ["agent", "run", "--operation", "observe.device@1", "--execution-id", execution],
                   "humanActionRequired", "connect the device",
                   {"execution": {"executionId": execution, "state": "waitingForHuman", "humanAction": action,
                                  "nextAction": {"kind": "humanAction", "resumeReference": "resume-1"},
                                  "candidates": [{"candidateKey": CONNECT_KEY}]}}, exit_code)
        self.ok("agent.status", ["agent", "status", "--execution-id", execution], {
            "executionId": execution, "operation": "observe.device@1", "state": "waitingForHuman", "jobId": None,
            "catalogDigest": self.digest, "humanAction": action,
            "nextAction": {"kind": "humanAction", "resumeReference": "resume-1"}})
        self.ok("human-action.show", ["human-action", "show", "--human-action", "har-1"], dict(action))
        job = self.job(execution, "observe.device@1", {"device-facts.json": b"{}"}, settle=False)
        self.ok("agent.resume", ["agent", "resume", "--resume-reference", "resume-1"], {
            "executionId": execution, "operation": "observe.device@1", "state": "completed", "jobId": job,
            "jobState": "succeeded", "catalogDigest": self.digest, "humanAction": None, "nextAction": None,
            "evidence": self.evidence(job, "observe.device@1")})
        self.ok("human-action.show", ["human-action", "show", "--human-action", "har-1"], {
            **action, "status": resolved})
        self.target_show()


class Case(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory()
        root = Path(self.temporary.name)
        self.repo = Repository(root)
        self.out = root / "out"
        self.journal = Journal(self.out, self.repo.digest)

    def tearDown(self):
        self.temporary.cleanup()

    def assemble(self, names=("GJ-1",), revision=None, attempt=None):
        return record.assemble(
            self.out, date=DATE, runtime_source_revision=revision or self.repo.revision,
            protected_main="main", repository=self.repo.path, names=list(names), attempt=attempt)

    def journey(self, document, name="GJ-1"):
        return next(j for j in document["journeys"] if j["goldenJourney"] == name)

    def refused(self, pattern, **kwargs):
        with self.assertRaisesRegex(record.AssemblyError, pattern):
            self.assemble(**kwargs)


class GoldenJourneyOneTests(Case):
    def test_a_complete_journey_passes_on_runtime_facts_alone(self):
        self.journal.facts()
        self.journal.gj1()
        document = self.assemble()
        journey = self.journey(document)
        self.assertEqual(journey["state"], PASS, journey.get("firstFailingCriterion"))
        self.assertEqual(journey["executionIDs"], [f"gj1-{D}", f"gj1-{D}-capture", f"gj1-{D}-har"])
        self.assertEqual(len(journey["jobs"]), 3)
        self.assertEqual(journey["runtimeExecutableSHA256"], DAEMON)
        self.assertEqual(journey["hdcExecutableSHA256"], HDC)
        self.assertEqual(journey["targetID"], TARGET)
        har = journey["jobs"][2]
        self.assertEqual(har["humanActions"], [
            {"actionId": "har-1", "category": "physicalConnection", "status": "resolvedByFreshProbe"}])
        self.assertTrue(all(c["holds"] for c in journey["criteria"]))
        self.assertTrue(all(c["sources"] for c in journey["criteria"] if "Artifact" in c["criterion"]))
        coverage = document["operationRealDeviceCoverage"]
        states = {o["operationReference"]: o["state"] for o in coverage["operations"]}
        self.assertEqual(states["observe.device@1"], "realDevicePass")
        self.assertEqual(states["input.tap@1"], "notExercised")
        self.assertEqual(coverage["canonicalOperationCount"], len(OPERATIONS))
        text = record.render(document)
        for secret in (CONNECT_KEY, "someone", "C:\\", "DAYU200 at desk"):
            self.assertNotIn(secret, text)

    def test_a_journey_nothing_was_captured_for_is_not_started(self):
        self.journal.facts()
        journey = self.journey(self.assemble(names=("GJ-1", "GJ-2")), "GJ-2")
        self.assertEqual(journey["state"], NOT_STARTED)

    def test_a_missing_step_leaves_the_journey_implementing(self):
        self.journal.facts()
        self.journal.gj1(capture=False)
        journey = self.journey(self.assemble())
        self.assertEqual(journey["state"], INCOMPLETE)
        self.assertEqual(journey["firstFailingCriterion"]["criterion"], f"gj1-{D}-capture: execution")

    def test_a_human_action_that_did_not_exit_75_is_a_defect(self):
        self.journal.facts()
        self.journal.gj1(har_exit=69)
        journey = self.journey(self.assemble())
        self.assertEqual(journey["state"], DEFECT)
        self.assertEqual(journey["firstFailingCriterion"]["criterion"], f"gj1-{D}-har: exit code")
        self.assertEqual(journey["firstFailingCriterion"]["raw"], 69)

    def test_an_action_that_expired_instead_of_resolving_is_a_defect(self):
        self.journal.facts()
        self.journal.gj1(resolved="expired")
        failing = self.journey(self.assemble())["firstFailingCriterion"]
        self.assertEqual(failing["criterion"], f"gj1-{D}-har: action status after resume")
        self.assertEqual(failing["raw"], "expired")

    def test_an_artifact_whose_bytes_do_not_match_its_digest_fails(self):
        self.journal.facts()
        self.journal.job(f"gj1-{D}", "observe.device@1", {
            "device-facts.json": b"{}", "tool-facts.json": b"{}", "binding-snapshot.json": b"{}"},
            corrupt="tool-facts.json")
        journey = self.journey(self.assemble())
        self.assertEqual(journey["state"], DEFECT)
        self.assertIn("tool-facts.json read whole and digest-checked", journey["firstFailingCriterion"]["criterion"])


class RefusalTests(Case):
    def test_a_development_root_is_rehearsal_never_evidence(self):
        self.journal.facts(root_kind="development")
        self.journal.gj1()
        self.refused("'development' state root")

    def test_a_simulated_or_plan_only_job_is_refused(self):
        self.journal.facts()
        self.journal.gj1()
        self.journal.ok("job.plan", ["job", "plan", "--operation", "observe.device@1"], {"executionMode": "planOnly"})
        self.refused("plan-only")

    def test_a_simulated_execution_mode_is_refused(self):
        self.journal.facts()
        self.journal.ok("job.result", ["job", "result", "--job", "job-x"], {
            "job": {"jobId": "job-x"}, "evidence": {"executionMode": "simulated", "catalogDigest": self.repo.digest},
            "artifacts": []})
        self.refused("'simulated' Job")

    def test_a_job_on_another_catalog_digest_is_stale(self):
        self.journal.facts()
        self.journal.digest = "f" * 64
        self.journal.job(f"gj1-{D}", "observe.device@1", {})
        self.refused("answers on Catalog f{64}")

    def test_a_runtime_built_before_mains_catalog_moved_is_stale(self):
        self.journal.facts()
        old = self.repo.revision
        self.repo.commit(generated(OPERATIONS + ("input.swipe",))[1])
        self.refused("its results are stale", revision=old)

    def test_a_revision_off_protected_main_is_refused(self):
        self.journal.facts()
        git(self.repo.path, "checkout", "-q", "-b", "side")
        side = self.repo.commit(generated()[1] + "// side\n")
        git(self.repo.path, "checkout", "-q", "main")
        self.refused("is not on main", revision=side)

    def test_an_edited_output_is_refused(self):
        self.journal.facts()
        path = self.journal.ok("job.result", ["job", "result", "--job", "job-x"], {"job": {}, "evidence": {}})
        path.write_bytes(path.read_bytes() + b" ")
        self.refused("not the output the journal recorded")

    def test_a_job_observed_through_another_hdc_is_refused(self):
        self.journal.facts()
        self.journal.job(f"gj1-{D}", "observe.device@1", {}, observation={"toolSha256": "0" * 64})
        self.refused("observed through HDC 0{64}")

    def test_a_cli_image_other_than_the_one_that_ran_is_refused(self):
        self.journal.facts()
        self.journal.ok("version", ["--version"], {"buildIdentity": "sha256:" + "1" * 64})
        self.refused("different CLI image")

    def test_an_operation_list_from_another_catalog_is_refused(self):
        self.journal.facts(operations=OPERATIONS[:-1])
        self.refused("canonical operation set")

    def test_a_record_carrying_a_connect_key_is_refused(self):
        with self.assertRaisesRegex(redact.RedactionError, "identifying literal"):
            redact.check(f'{{"notes": "{CONNECT_KEY}"}}', {CONNECT_KEY})
        for text in ('"C:\\\\x"', '"/Users/me"', '"192.168.0.2:8710"', '"%LOCALAPPDATA%"'):
            with self.assertRaises(redact.RedactionError, msg=text):
                redact.check(text, set())


class LaterJourneyTests(Case):
    def complete_gj2(self, execution):
        self.journal.facts()
        timeline = [
            'host-step verify-hap-artifact',
            'verified send-hap ["stagedAt"]',
            'dispatched install-hap; awaiting readback',
            'verified package-readback ["bundleName", "deployedArtifactSha256", "installed"]',
            'dispatched start-ability; awaiting readback',
            'verified process-readback ["bundleName", "running"]',
            'verified stop-ability ["stopped"]',
            'verified cleanup-remote-staging ["cleaned"]',
        ]
        self.journal.job(execution, "debug.hap@1", {"install-readback.json": b"{}", "process-readback.json": b"{}"},
                         timeline=timeline)
        self.journal.job(execution + "-capture", "capture.diagnostics@1", {
            "hilog.txt": b"l", "ui-dump.json": b"{}", "trace.htrace": b"t",
            "capture-summary.json": json.dumps({"completeness": "complete", "missingRequired": []}).encode()})
    def test_gj2_reads_the_debug_steps_and_the_app_scoped_capture(self):
        self.complete_gj2(f"gj2-{D}")
        journey = self.journey(self.assemble(names=("GJ-2",)), "GJ-2")
        self.assertEqual(journey["state"], PASS, journey.get("firstFailingCriterion"))

    def test_new_attempt_never_uses_an_original_success(self):
        self.complete_gj2(f"gj2-{D}")
        journey = self.journey(self.assemble(names=("GJ-2",), attempt=2), "GJ-2")
        self.assertEqual(journey["state"], NOT_STARTED)
        self.assertEqual(journey["executionIDs"], [])

    def test_independent_attempt_requires_the_same_whole_artifacts_and_criteria(self):
        self.complete_gj2(f"gj2-{D}-attempt2")
        journey = self.journey(self.assemble(names=("GJ-2",), attempt=2), "GJ-2")
        self.assertEqual(journey["state"], PASS, journey.get("firstFailingCriterion"))
        self.assertEqual(journey["executionIDs"], [f"gj2-{D}-attempt2", f"gj2-{D}-attempt2-capture"])
        artifact = next(path for path in self.out.glob("*.json")
                        if b'"command": "artifact.read"' in path.read_bytes())
        artifact.write_bytes(artifact.read_bytes() + b" ")
        self.refused("not the output the journal recorded", names=("GJ-2",), attempt=2)

    def test_invalid_attempt_is_refused_before_reading_a_run(self):
        for attempt in (0, -1, 1000, True, "2"):
            with self.subTest(attempt=attempt), self.assertRaisesRegex(record.AssemblyError, "--attempt"):
                self.assemble(names=("GJ-2",), attempt=attempt)

    def test_gj2_without_package_readback_is_a_defect(self):
        self.journal.facts()
        self.journal.job(f"gj2-{D}", "debug.hap@1", {"install-readback.json": b"{}", "process-readback.json": b"{}"},
                         timeline=['failed package-readback: x'])
        journey = self.journey(self.assemble(names=("GJ-2",)), "GJ-2")
        self.assertEqual(journey["state"], DEFECT)
        self.assertEqual(journey["firstFailingCriterion"]["criterion"], f"gj2-{D}: send-hap verified")

    def gj3(self, *, fixture_abi="armeabi-v7a", fixture_sha256=record.ROLLBACK_FIXTURE_SHA256,
            fixture=True, published=True, lease=None, fixture_transform=None):
        self.journal.facts()
        forward = [
            "verify-elf-locally abi=armeabi-v7a buildId=ab sha256=" + "1" * 64,
            "hash-library abi=armeabi-v7a buildId=ab sha256=" + "1" * 64,
            "dispatched send-to-staging; awaiting readback",
            'verified verify-remote-staging ["buildId", "remoteByteCount", "remoteSha256"]',
            'verified backup-current-version ["backupPath", "backupSha256"]',
            'verified atomic-publish ["buildId", "publishedSha256"]',
            'verified restart-target ["stopped"]',
            'verified start-target ["processIds", "started"]',
            'verified verify-loaded-library ["abi", "loaderVerified", "publishedSha256"]',
        ]
        self.journal.job(f"gj3-{D}", "deploy.native-library.app-owned@1", {
            "publish-report.json": b"{}",
            "verification-report.json": b'{"loaderVerified": "true", "abi": "armeabi-v7a"}'},
            timeline=forward)
        if fixture:
            inspection = fixture_inspection(abi=fixture_abi, digest=fixture_sha256)
            if lease is None:
                lease = inspection["import"]["receipt"]["lease"]
            if fixture_transform is not None:
                changed = fixture_transform(inspection)
                if changed is not None:
                    inspection = changed
            self.journal.ok("artifact.import.inspect", ["artifact", "import", "inspect", "--import-request-id",
                                                        f"gj3-{D}-fixture"], inspection)
        rollback = [
            'verified atomic-publish ["buildId", "publishedSha256"]',
            "failed start-target: nativeTargetNotRunning: did not start",
            'verified rollback-native-library ["processIds", "restored", "restoredSha256"]',
            "native deployment failure restored previous library",
        ]
        if not published:
            rollback = rollback[1:]
        self.journal.job(f"gj3-{D}-rollback", "deploy.native-library.app-owned@1", {}, terminal="failed",
                         timeline=rollback, inputs={"libraryArtifactLease": lease})
        return self.journey(self.assemble(names=("GJ-3",)), "GJ-3")

    def test_gj3_needs_the_loader_verification_and_a_real_rollback(self):
        journey = self.gj3()
        self.assertEqual(journey["state"], PASS, journey.get("firstFailingCriterion"))
        held = {c["criterion"] for c in journey["criteria"]}
        self.assertIn(f"gj3-{D}-rollback: fixture ABI is the Target's loaded ABI", held)

    def test_g3_a_fixture_for_another_abi_does_not_apply(self):
        failing = self.gj3(fixture_abi="arm64-v8a")["firstFailingCriterion"]
        self.assertEqual(failing["criterion"], f"gj3-{D}-rollback: fixture ABI is the Target's loaded ABI")
        self.assertEqual(failing["raw"], "arm64-v8a")

    def test_g3_a_fixture_other_than_the_pinned_one_does_not_apply(self):
        failing = self.gj3(fixture_sha256="0" * 64)["firstFailingCriterion"]
        self.assertEqual(failing["criterion"], f"gj3-{D}-rollback: fixture is the pinned rollback fixture")

    def test_g3_replacement_ghost_has_the_same_complete_rollback_requirements(self):
        journey = self.gj3(fixture_sha256="01d4e785ceec23a3873f67b4ec5035c0bfa469139596f88bfb96dd91dae840ae")
        self.assertEqual(journey["state"], PASS, journey.get("firstFailingCriterion"))

    def test_g3_historical_bytes_are_not_the_replacement_fixture(self):
        journey = self.gj3(fixture_sha256="260a533ae2b02e23810aa5ab6ea9c1a5cf4524b19484ede66cb4dc0b7bb86d3a")
        self.assertEqual(journey["state"], DEFECT)
        self.assertEqual(journey["firstFailingCriterion"]["criterion"],
                         f"gj3-{D}-rollback: fixture is the pinned rollback fixture")

    def test_g3_a_rollback_that_did_not_consume_the_fixture_does_not_count(self):
        failing = self.gj3(lease="lease-other")["firstFailingCriterion"]
        self.assertEqual(failing["criterion"], f"gj3-{D}-rollback: the rollback Job consumed the fixture's lease")

    def test_g3_without_the_fixture_import_the_rollback_leg_is_unverified(self):
        journey = self.gj3(fixture=False)
        self.assertEqual(journey["state"], INCOMPLETE)
        self.assertEqual(journey["firstFailingCriterion"]["criterion"], f"gj3-{D}-rollback: fixture import")

    def test_g3_bare_malformed_or_another_version_is_not_the_current_inspection(self):
        for transform in (
            lambda value: value["import"],
            lambda value: {**value, "schemaVersion": "arkdeck.import-inspection/2"},
            lambda value: {**value, "import": None},
            lambda value: {**value, "import": {**value["import"], "schemaVersion": "arkdeck.import/2"}},
            lambda value: {**value, "references": []},
            lambda value: {**value, "import": {**value["import"], "metadata": []}},
            lambda value: {**value, "import": {**value["import"], "receipt": None}},
        ):
            with self.subTest(transform=transform):
                # Each subcase needs its own synthetic capture; no changed raw
                # envelope is ever written over an earlier journal entry.
                self.journal = Journal(self.out / str(self.journal.sequence), self.repo.digest)
                self.out = self.journal.out
                journey = self.gj3(fixture_transform=transform)
                self.assertEqual(journey["state"], DEFECT)
                self.assertEqual(journey["firstFailingCriterion"]["criterion"],
                                 f"gj3-{D}-rollback: fixture inspection uses the current typed projection")

    def test_g3_receipt_identity_cannot_override_the_requested_import(self):
        for key, replacement in (
            ("importId", "imp-other"), ("importRequestId", "gj3-other-fixture"),
            ("owner", {"kind": "job", "id": "foreign"}), ("lease", "lease-v1:imp-other:ART-other"),
        ):
            with self.subTest(key=key):
                self.journal = Journal(self.out / str(self.journal.sequence), self.repo.digest)
                self.out = self.journal.out
                journey = self.gj3(fixture_transform=lambda value: value["import"]["receipt"].update({key: replacement}))
                self.assertEqual(journey["state"], DEFECT)
                self.assertEqual(journey["firstFailingCriterion"]["criterion"],
                                 f"gj3-{D}-rollback: fixture import and receipt identities match")

    def test_g3_receipt_content_and_scope_must_match_the_import(self):
        for key, replacement in (("artifactDigest", "0" * 64), ("targetId", "TGT-other"),
                                 ("bindingRevision", "2"), ("byteCount", "1"), ("name", "libother.so")):
            with self.subTest(key=key):
                self.journal = Journal(self.out / str(self.journal.sequence), self.repo.digest)
                self.out = self.journal.out
                journey = self.gj3(fixture_transform=lambda value: value["import"]["receipt"].update({key: replacement}))
                self.assertEqual(journey["state"], DEFECT)
                self.assertEqual(journey["firstFailingCriterion"]["criterion"],
                                 f"gj3-{D}-rollback: fixture receipt matches the imported content and binding")

    def test_g3_complete_inspection_for_another_forward_target_or_binding_does_not_apply(self):
        for key, replacement, criterion in (("targetId", "TGT-other", "fixture imported for this Target"),
                                             ("bindingRevision", "2", "fixture imported at this binding revision")):
            with self.subTest(key=key):
                self.journal = Journal(self.out / str(self.journal.sequence), self.repo.digest)
                self.out = self.journal.out
                def transform(value):
                    for fields in (value["import"]["metadata"], value["import"]["receipt"]):
                        fields[key] = replacement
                journey = self.gj3(fixture_transform=transform)
                self.assertEqual(journey["state"], DEFECT)
                self.assertEqual(journey["firstFailingCriterion"]["criterion"], f"gj3-{D}-rollback: {criterion}")

    def test_g3_inspection_without_elf_build_id_does_not_apply(self):
        journey = self.gj3(fixture_transform=lambda value: value["import"]["receipt"]["validation"].update(buildId=""))
        self.assertEqual(journey["state"], DEFECT)
        self.assertEqual(journey["firstFailingCriterion"]["criterion"], f"gj3-{D}-rollback: fixture has a build ID")

    def test_g3_a_different_nested_request_does_not_answer_the_captured_inspection(self):
        def transform(value):
            imported = value["import"]
            for fields in (imported, imported["metadata"], imported["receipt"]):
                fields["importRequestId"] = "gj3-other-fixture"
        journey = self.gj3(fixture_transform=transform)
        self.assertEqual(journey["state"], DEFECT)
        self.assertEqual(journey["firstFailingCriterion"]["criterion"],
                         f"gj3-{D}-rollback: fixture import and receipt identities match")

    def test_g3_a_released_fixture_keeps_its_original_receipt_applicability(self):
        def transform(value):
            value["import"].update(state="released", generation="3")
        journey = self.gj3(fixture_transform=transform)
        self.assertEqual(journey["state"], PASS, journey.get("firstFailingCriterion"))

    def test_g3_a_failure_before_publication_is_not_a_rollback(self):
        failing = self.gj3(published=False)["firstFailingCriterion"]
        self.assertEqual(failing["criterion"], f"gj3-{D}-rollback: atomic-publish verified")

    def test_gj4_reads_the_step_kinds_and_the_machine_readback(self):
        from gj_record.test_flash_image import append_journey

        self.journal.facts()
        append_journey(self.journal)
        journey = self.journey(self.assemble(names=("GJ-4",)), "GJ-4")
        self.assertEqual(journey["state"], PASS, journey.get("firstFailingCriterion"))

    def test_gj4_on_another_image_is_a_defect(self):
        self.journal.facts()
        self.journal.job(f"gj4-{D}", "flash.full-restore@1", {}, kinds=list(journeys.FLASH_STEP_KINDS),
                         observation={"firmware": "OpenHarmony-6.0", "confirmationMethod": "machineReadback"})
        failing = self.journey(self.assemble(names=("GJ-4",)), "GJ-4")["firstFailingCriterion"]
        self.assertIn("published", failing["criterion"])

    def gj5(self, *, crash_after_fix=1, ledger_changes=False, signature_change=None):
        j = self.journal

        def ledger(entries):
            fence = "*" * 20
            return ("Fault log list:\n" + fence + "\n" + "".join(f"cppcrash-app-1-2026100501000{i}\n" for i in range(entries))
                    + fence + "\n").encode() if entries else b"No fault log exist.\n"

        def liveness(state, reason):
            return json.dumps({"state": state, "reasonCode": reason}).encode()

        j.job(f"gj5-{D}-baseline", "capture.diagnostics@1", {"crash-index.txt": ledger(0)})
        j.job(f"gj5-{D}-repro", "debug.hap@1", {"install-readback.json": b"{}"})
        j.job(f"gj5-{D}-repro-capture", "capture.diagnostics@1", {
            "application-liveness.json": liveness("UNHEALTHY", "targetProcessNotRunning"), "crash-index.txt": ledger(1)})
        answer = {"schemaVersion": "1.0.0", "analyzerRef": "crash-signature@1",
                  "analyzerVersion": "arkdeck-fault-log-ledger@1", "status": "answered",
                  "entries": [{"name": "cppcrash-app-1", "kind": "cppcrash", "bundle": "app",
                               "uid": "1", "timestamp": "20261005010001"}]}
        analyzer_output = json.dumps(answer, sort_keys=True, separators=(",", ":")).encode()
        signature = {"schemaVersion": "1.0.0", "analyzerRef": answer["analyzerRef"],
                     "analyzerVersion": answer["analyzerVersion"],
                     "sourceArtifactID": f"ART-{j.artifacts:04d}", "sourceSHA256": sha(ledger(1)),
                     "sourceByteCount": len(ledger(1)), "analyzerOutputSHA256": sha(analyzer_output),
                     "analyzerOutputByteCount": len(analyzer_output), "result": answer}
        if signature_change is not None:
            signature_change(signature)
        j.job(f"gj5-{D}-analyze", "analyzer.extract-crash-signature@1", {
            "crash-signature.json": json.dumps(signature).encode()})
        j.job(f"gj5-{D}-isolate", "workspace.prepare-isolated-copy@1", {
            "isolated-workspace.json": json.dumps({"workspaceRevision": "r1"}).encode()})
        j.job(f"gj5-{D}-patch", "workspace.apply-patch@1", {
            "applied-patch.json": json.dumps({"previousWorkspaceRevision": "r1", "workspaceRevision": "r2"}).encode()})
        j.job(f"gj5-{D}-build", "workspace.build-openharmony@1", {"build.log": b"ok", "unsigned.hap": b"u"})
        j.job(f"gj5-{D}-sign", "workspace.sign-openharmony-hap@1", {"signed.hap": b"signed"})
        j.job(f"gj5-{D}-verify", "debug.hap@1", {
            "install-readback.json": json.dumps({"deployedArtifactSha256": sha(b"signed")}).encode()})
        j.job(f"gj5-{D}-verify-capture", "capture.diagnostics@1", {
            "application-liveness.json": liveness("HEALTHY", "targetProcessRunning"),
            "crash-index.txt": ledger(crash_after_fix)})
        page = {"schemaVersion": "arkdeck.cli.page/1", "hasMore": False, "nextCursor": None,
                "items": [{"jobId": "job-a"}, {"jobId": "job-b"}]}
        j.ok("job.list", ["job", "list", "--page-size", "1000"], page)
        execution = f"gj5-{D}-negative"
        j.error("agent.run", ["agent", "run", "--operation", "workspace.apply-patch@1", "--execution-id", execution],
                "admissionDenied",
                "typed plan preflight failed before authorization: workspace.revisionConflict:aaaaaaaaaaaa!=bbbbbbbbbbbb",
                {"phase": "preAdmission", "newDispatchCount": 0, "executionId": execution}, 77)
        if ledger_changes:
            page = {**page, "items": page["items"] + [{"jobId": "job-c"}]}
        j.ok("job.list", ["job", "list", "--page-size", "1000"], page)
        return self.journey(self.assemble(names=("GJ-5",)), "GJ-5")

    def test_gj5_closes_the_loop_on_runtime_facts(self):
        self.journal.facts()
        journey = self.gj5()
        self.assertEqual(journey["state"], PASS, journey.get("firstFailingCriterion"))
        self.assertEqual(len(journey["zeroDispatchChecks"]), 3)

    def test_gj5_rejects_missing_derived_signature_result(self):
        self.journal.facts()
        journey = self.gj5(signature_change=lambda value: value.pop("result"))
        self.assertEqual(journey["state"], DEFECT)
        self.assertEqual(journey["firstFailingCriterion"]["criterion"],
                         "analyze: crash signature derived Artifact wrapper")

    def test_gj5_rejects_an_invented_flat_signature_artifact(self):
        def flatten(value):
            value.clear()
            value.update(status="answered", entries=[])
        self.journal.facts()
        journey = self.gj5(signature_change=flatten)
        self.assertEqual(journey["state"], DEFECT)
        self.assertEqual(journey["firstFailingCriterion"]["criterion"],
                         "analyze: crash signature derived Artifact wrapper")

    def test_gj5_rejects_invalid_derived_signature_result(self):
        self.journal.facts()
        journey = self.gj5(signature_change=lambda value: value.update(result=[{"status": "answered"}]))
        self.assertEqual(journey["state"], DEFECT)
        self.assertEqual(journey["firstFailingCriterion"]["criterion"],
                         "analyze: crash signature derived Artifact wrapper")

    def test_gj5_rejects_wrong_derived_signature_schema(self):
        self.journal.facts()
        journey = self.gj5(signature_change=lambda value: value["result"].update(schemaVersion="2.0.0"))
        self.assertEqual(journey["state"], DEFECT)
        self.assertEqual(journey["firstFailingCriterion"]["criterion"],
                         "analyze: crash signature derived Artifact wrapper")

    def test_gj5_rejects_invalid_decoded_crash_entry(self):
        self.journal.facts()
        journey = self.gj5(signature_change=lambda value: value["result"].update(entries=[{"name": "only-name"}]))
        self.assertEqual(journey["state"], DEFECT)
        self.assertEqual(journey["firstFailingCriterion"]["criterion"],
                         "analyze: crash signature derived Artifact wrapper")

    def test_gj5_unanswered_derived_signature_keeps_original_status_criterion(self):
        self.journal.facts()
        journey = self.gj5(signature_change=lambda value: value["result"].update(status="unreadable"))
        self.assertEqual(journey["state"], DEFECT)
        self.assertEqual(journey["firstFailingCriterion"]["criterion"], "analyze: crash signature status")
        self.assertEqual(journey["firstFailingCriterion"]["raw"], "unreadable")

    def test_gj5_rejects_signature_from_another_complete_crash_source(self):
        self.journal.facts()
        journey = self.gj5(signature_change=lambda value: value.update(sourceArtifactID="ART-OTHER"))
        self.assertEqual(journey["state"], DEFECT)
        self.assertEqual(journey["firstFailingCriterion"]["criterion"],
                         "analyze: crash signature source provenance")

    def test_gj5_rejects_changed_source_digest(self):
        self.journal.facts()
        journey = self.gj5(signature_change=lambda value: value.update(sourceSHA256="0" * 64))
        self.assertEqual(journey["state"], DEFECT)
        self.assertEqual(journey["firstFailingCriterion"]["criterion"],
                         "analyze: crash signature source provenance")

    def test_gj5_rejects_boolean_source_byte_count(self):
        self.journal.facts()
        journey = self.gj5(signature_change=lambda value: value.update(sourceByteCount=True))
        self.assertEqual(journey["state"], DEFECT)
        self.assertEqual(journey["firstFailingCriterion"]["criterion"],
                         "analyze: crash signature source provenance")

    def test_gj5_with_a_new_crash_after_the_fix_is_a_defect(self):
        self.journal.facts()
        failing = self.gj5(crash_after_fix=2)["firstFailingCriterion"]
        self.assertEqual(failing["criterion"], "verify: crash-index count unchanged since the repro")
        self.assertEqual(failing["raw"], [1, 2])

    def test_gj5_negative_case_that_grew_the_ledger_is_a_defect(self):
        self.journal.facts()
        failing = self.gj5(ledger_changes=True)["firstFailingCriterion"]
        self.assertEqual(failing["criterion"], f"gj5-{D}-negative: Job count unchanged")


class PartsTests(unittest.TestCase):
    def test_the_crash_ledger_counts_entries_between_its_fences(self):
        self.assertEqual(journeys.crash_entries(b"No fault log exist.\n"), 0)
        self.assertEqual(journeys.crash_entries(b"Fault log list:\n******\na\nb\n******\n"), 2)
        self.assertIsNone(journeys.crash_entries(b"garbage"))

    def test_a_generated_catalog_that_does_not_hash_to_its_digest_is_refused(self):
        digest, text = generated()
        with self.assertRaisesRegex(catalog.CatalogError, "does not hash"):
            catalog.parse_generated(text.replace(digest, "0" * 64))
        self.assertEqual(catalog.parse_generated(text)[0], digest)

    def test_a_raw_value_that_is_not_a_plain_identifier_is_withheld(self):
        self.assertEqual(record._raw("C:\\Users\\me"), "withheld (not a plain identifier, state or count)")
        self.assertEqual(record._raw("expired"), "expired")
        self.assertEqual(record._raw([1, 2]), [1, 2])


class CaptureTests(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory()
        self.root = Path(self.temporary.name)
        self.cli = self.root / "arkdeck.exe"
        self.cli.write_bytes(b"image")
        self.repository = self.root / "repo"
        self.repository.mkdir()

    def tearDown(self):
        self.temporary.cleanup()

    def runner(self, stdout: bytes, code: int):
        calls = []

        def run(argv, **kwargs):
            calls.append((argv, kwargs))
            return subprocess.CompletedProcess(argv, code, stdout=stdout)

        return run, calls

    def test_capture_keeps_stdout_exit_code_and_order(self):
        envelope = json.dumps({"schemaVersion": "arkdeck.cli.result/1", "command": "agent.run", "ok": False}).encode()
        run, calls = self.runner(envelope, 75)
        out = self.root / "out"
        for step in ("gj1.har", "gj1.har-status"):
            entry = capture.capture(out, step, [str(self.cli), "agent", "run", "--output", "json"],
                                    repository=self.repository, quiet=True, runner=run)
        self.assertEqual(entry["sequence"], 2)
        self.assertEqual(entry["exitCode"], 75)
        self.assertEqual(entry["cliExecutableSHA256"], sha(b"image"))
        self.assertEqual((out / entry["stdoutFile"]).read_bytes(), envelope)
        self.assertEqual([e["step"] for e in capture.read_journal(out)], ["gj1.har", "gj1.har-status"])
        self.assertEqual(calls[0][1]["stdin"], subprocess.DEVNULL)
        self.assertIsInstance(calls[0][0], list)

    def test_capture_refuses_output_inside_the_repository_and_human_output(self):
        run, calls = self.runner(b"{}", 0)
        with self.assertRaisesRegex(capture.CaptureError, "inside the repository"):
            capture.capture(self.repository / "out", "s", [str(self.cli), "doctor", "--output", "json"],
                            repository=self.repository, runner=run)
        with self.assertRaisesRegex(capture.CaptureError, "--output json"):
            capture.capture(self.root / "out", "s", [str(self.cli), "doctor"], repository=self.repository, runner=run)
        self.assertEqual(calls, [])

    def test_capture_hashes_the_daemon_image_a_windows_status_names(self):
        daemon = self.root / "arkdeck-agentd.exe"
        daemon.write_bytes(b"daemon")
        envelope = json.dumps({"schemaVersion": "arkdeck.cli.result/1", "command": "runtime.service.status", "ok": True,
                               "result": {"daemonService": {"daemonPath": str(daemon)}}}).encode()
        run, _ = self.runner(envelope, 0)
        entry = capture.capture(self.root / "out", "facts.status",
                                [str(self.cli), "runtime", "service", "status", "--output", "json"],
                                repository=self.repository, quiet=True, runner=run)
        self.assertEqual(entry["daemonImageSHA256"], sha(b"daemon"))


if __name__ == "__main__":
    unittest.main()
