// Generated by Scripts/generate-control-contract.py. Do not edit.
// Source: Contracts/control-negotiation.json

package enum ArkDeckControlProtocol {
  package static let legacyVersion = "1.0.0"
  package static let targetVersion = "2.0.0"
  package static let supportedExactVersions = ["2.0.0", "1.0.0"]
  package static let bootstrapVersion = "arkdeck.control.negotiation/1"
  package static let bootstrapMethod = "protocol.negotiate"
  package static let maximumBootstrapFrameBytes = 65536
  package static let targetMethods: Set<String> = ["agent.abandon", "agent.list", "agent.resume", "agent.run", "agent.status", "artifact.export", "artifact.import.abort", "artifact.import.append", "artifact.import.begin", "artifact.import.commit", "artifact.import.inspect", "artifact.import.inspection", "artifact.import.list", "artifact.import.release", "artifact.inspect", "artifact.list", "artifact.read", "control-action.list", "control-action.reconcile", "control-action.show", "device.display-name.clear", "device.display-name.set", "device.observations", "health", "human-action.list", "human-action.resume", "human-action.show", "history.filter.delete", "history.filter.list", "history.filter.save", "job.events", "job.evidence", "job.list", "job.plan", "job.result", "job.run", "job.show", "job.status", "job.submit", "job.timeline", "recovery.flash-invocation.list", "runtime.hdc.impact-preview", "runtime.hdc.restart", "runtime.hdc.status", "target.adopt", "target.display-name.clear", "target.display-name.set", "target.show", "trace.cache.purge", "trace.cache.status"]
  package static let preBootstrapLegacyMethods: Set<String> = ["health"]
}
