// Generated by Scripts/generate-control-contract.py. Do not edit.
// Source: Contracts/control-negotiation.json

package enum ArkDeckControlProtocol {
  package static let legacyVersion = "1.0.0"
  package static let targetVersion = "2.0.0"
  package static let supportedExactVersions = ["2.0.0", "1.0.0"]
  package static let bootstrapVersion = "arkdeck.control.negotiation/1"
  package static let bootstrapMethod = "protocol.negotiate"
  package static let maximumBootstrapFrameBytes = 65536
  package static let targetMethods: Set<String> = ["agent.abandon", "agent.list", "agent.resume", "agent.run", "agent.status", "device.observations", "health", "human-action.list", "human-action.resume", "human-action.show", "job.events", "job.evidence", "job.list", "job.result", "job.show", "job.status", "job.timeline", "target.adopt"]
  package static let preBootstrapLegacyMethods: Set<String> = ["health"]
}
