// Generated by: cargo run -p arkdeck-hoststore --example flash_catalog_review
// Presentation data only; no materialized plan, availability or execution authority.
public enum FlashReviewCatalogGenerated {
  public static let json = #"""
{
  "catalogDigest": "508783acdf9e9b13d2d4a969e7e26f6fd60094a39d1cc9e02d2198e02ea13684",
  "dispatchDisposition": "notDispatched",
  "jobAdmitted": false,
  "operation": "flash.full-restore@1",
  "providerId": "arkforge",
  "schemaVersion": "arkdeck.catalog-review/1",
  "selectionInputs": {
    "verification": "full"
  },
  "stepSetDigestSHA256": "c1ab01f8c7c24649080d109c481f9c034ffb73edcc62033684ac8a59875e0b12",
  "steps": [
    {
      "binding": "none",
      "cancellation": "immediate",
      "effect": "hostOnly",
      "executionOwner": "runtimeHost",
      "kind": "verifyArtifact",
      "optional": false,
      "stepId": "verify-image-bundle"
    },
    {
      "binding": "none",
      "cancellation": "immediate",
      "effect": "hostOnly",
      "executionOwner": "runtimeHost",
      "kind": "hashFile",
      "optional": false,
      "stepId": "hash-images"
    },
    {
      "binding": "none",
      "cancellation": "immediate",
      "effect": "hostOnly",
      "executionOwner": "runtimeHost",
      "kind": "requestConfirmation",
      "optional": false,
      "stepId": "confirm-flash-intent"
    },
    {
      "binding": "confirmedDevice",
      "cancellation": "atSafeBoundary",
      "effect": "deviceMutation",
      "executionOwner": "arkforgeLane",
      "kind": "enterUpdater",
      "optional": false,
      "stepId": "enter-loader-mode"
    },
    {
      "binding": "confirmedDevice",
      "cancellation": "immediate",
      "effect": "readOnly",
      "executionOwner": "arkforgeLane",
      "kind": "waitForDisconnect",
      "optional": false,
      "stepId": "wait-loader-disconnect"
    },
    {
      "binding": "confirmedDevice",
      "cancellation": "immediate",
      "effect": "readOnly",
      "executionOwner": "arkforgeLane",
      "kind": "waitForReconnect",
      "optional": false,
      "stepId": "wait-loader-reconnect"
    },
    {
      "binding": "confirmedDevice",
      "cancellation": "immediate",
      "effect": "readOnly",
      "executionOwner": "arkforgeLane",
      "kind": "probeDevice",
      "optional": false,
      "stepId": "rebind-loader-identity"
    },
    {
      "binding": "confirmedDevice",
      "cancellation": "criticalNonInterruptible",
      "effect": "destructive",
      "executionOwner": "arkforgeLane",
      "kind": "flashPartition",
      "optional": false,
      "stepId": "flash-partitions"
    },
    {
      "binding": "confirmedDevice",
      "cancellation": "immediate",
      "effect": "readOnly",
      "executionOwner": "arkforgeLane",
      "kind": "verifyRemoteState",
      "optional": false,
      "stepId": "verify-flash-readback"
    },
    {
      "binding": "confirmedDevice",
      "cancellation": "atSafeBoundary",
      "effect": "deviceMutation",
      "executionOwner": "arkforgeLane",
      "kind": "rebootDevice",
      "optional": false,
      "stepId": "reboot-device"
    },
    {
      "binding": "confirmedDevice",
      "cancellation": "immediate",
      "effect": "readOnly",
      "executionOwner": "arkforgeLane",
      "kind": "waitForReconnect",
      "optional": false,
      "stepId": "wait-for-hdc"
    },
    {
      "binding": "confirmedDevice",
      "cancellation": "immediate",
      "effect": "readOnly",
      "executionOwner": "arkforgeLane",
      "kind": "probeDevice",
      "optional": false,
      "stepId": "rebind-and-verify-build"
    },
    {
      "binding": "confirmedDevice",
      "cancellation": "immediate",
      "effect": "readOnly",
      "executionOwner": "runtimeHost",
      "kind": "captureRemoteStdout",
      "optional": true,
      "stepId": "capture-post-flash-diagnostics"
    },
    {
      "binding": "none",
      "cancellation": "atSafeBoundary",
      "effect": "hostOnly",
      "executionOwner": "runtimeHost",
      "kind": "finalizeSession",
      "optional": false,
      "stepId": "finalize-session"
    }
  ]
}
"""#
}
