import CryptoKit
import Foundation
import XCTest

@testable import ArkDeckCore

/// `AFA-AC-2`: the Swift permit encoder must produce the same canonical CBOR
/// and the same HMAC tag as ArkForge's Rust one.
///
/// The vectors are published in
/// `openspec/changes/chg-2026-059-arkdeck-arkforge-authority/permit-vectors.md`
/// and generated by ArkForge `crates/arkforge-authority-api/tests/permit_vectors.rs`,
/// which guards them from that side. This file is the second implementation
/// they exist to catch: an encoder that is merely self-consistent authorizes
/// writes ArkForge will refuse, or — far worse — encodes a permit that decodes
/// cleanly and verifies against bytes the authority never meant to sign.
///
/// The digest of the signing body is asserted rather than the body itself
/// because the body is several hundred bytes; a differing digest is exactly
/// the signal, and ArkForge's test can print the full body for a byte-by-byte
/// comparison when one is needed.
final class ArkForgeStepPermitContractTests: XCTestCase {
  private static let pairingSecret = Array("arkforge-arkdeck-permit-vector-secret".utf8)
  private static let pairingEpoch = ArkForgePairingEpoch(1)

  private func digest(_ preimage: String) -> [UInt8] {
    Array(SHA256.hash(data: Data(preimage.utf8)))
  }

  private func hex(_ bytes: [UInt8]) -> String {
    SHA256Hex.lowercaseHex(bytes)
  }

  /// Every field the vector document fixes, so each case varies only the three
  /// values the table varies.
  private func vectorPermit(
    stepID: String, attemptID: String, privateActionPreimage: String
  ) -> ArkForgeStepPermit {
    ArkForgeStepPermit(
      permitID: "PERMIT-" + stepID,
      authorityNamespace: "arkdeck",
      controllerSessionID: "SESSION-VECTOR",
      jobID: "JOB-VECTOR",
      planID: "PLAN-VECTOR",
      planDigest: digest("plan-vector"),
      stepID: stepID,
      attemptID: attemptID,
      publicStepDigest: digest("public-step-vector"),
      privateActionDigest: digest(privateActionPreimage),
      effectSetDigest: digest("effect-set-vector"),
      authorityBinding: ArkForgeAuthorityBinding(
        authorityNamespace: "arkdeck",
        bindingID: "BINDING-VECTOR",
        bindingRevision: 3,
        stableIdentityDigest: digest("stable-identity-vector")),
      admittedDeviceFactsDigest: digest("admitted-facts-vector"),
      issuedAtEpochMs: 1_770_000_000_000,
      expiresAtEpochMs: 1_770_000_060_000,
      singleUse: true)
  }

  func testPublishedVectorsReproduceArkForgeBytes() {
    let vectors:
      [(step: String, attempt: String, preimage: String, bodyDigest: String, tag: String)] = [
        (
          "STEP-ENSURE-MODE", "ATTEMPT-1", "enter-loader",
          "bae9c1e8d669e6850eb967524885bed0632b6adbb9de5fb3bea971250fb5cd51",
          "d0a4dbc07944f6a802a4f157574f89ddc1cca5f9eb89c7b5c26d99884ea37ae0"
        ),
        (
          "STEP-WRITE-SYSTEM", "ATTEMPT-1", "write-partition:system",
          "fbdfcab7a865c5ae6400ab64594c1780e71a06a47da43ab6232674e1cdaa2d2e",
          "db38ba9d9a8fbac7840a89b6a9434938b25ed18bc357b4f27e39751d21be1523"
        ),
        (
          "STEP-RESET", "ATTEMPT-2", "reset-device",
          "cea82597e94d8a47092ef11c7ff91af63e6d9a890292f5407eeeab60960d65f8",
          "86805a7585615edaed931ac3ac005e445529ba5de7495292d6fae10e2d9029ec"
        ),
      ]

    let secret = ArkForgePairingSecret(
      secret: Self.pairingSecret, epoch: Self.pairingEpoch)

    for vector in vectors {
      let permit = vectorPermit(
        stepID: vector.step, attemptID: vector.attempt,
        privateActionPreimage: vector.preimage)
      let body = permit.signingBody

      XCTAssertEqual(
        SHA256Hex.string(of: body), vector.bodyDigest,
        "\(vector.step): canonical CBOR body differs from ArkForge's. The usual causes are "
          + "map keys sorted by text instead of encoded bytes, or an integer not in shortest form."
      )

      let signed = ArkForgeSignedPermit(permit: permit, secret: secret)
      XCTAssertEqual(hex(signed.integrityTag), vector.tag, "\(vector.step): HMAC tag differs")
      XCTAssertEqual(signed.signingBody, body, "the signed bytes must be the body, unmodified")
      XCTAssertEqual(signed.pairingEpoch, Self.pairingEpoch)
    }
  }

  func testTheTagDoesNotCoverItself() {
    // A body carrying its own tag would be signing a claim about itself. The
    // permit type has no tag field at all, so this asserts the absence stays
    // structural rather than a convention someone can undo.
    let permit = vectorPermit(
      stepID: "STEP-ENSURE-MODE", attemptID: "ATTEMPT-1", privateActionPreimage: "enter-loader")
    let encoded = String(decoding: permit.signingBody, as: UTF8.self)
    XCTAssertFalse(encoded.contains("integrityTag"))
    XCTAssertFalse(encoded.contains("pairingEpoch"))
  }

  func testRetransmissionReplaysBytesRatherThanRederiving() {
    // ArkForge refuses a second permit for the same permitID. What must be
    // replayed is the stored byte sequence: re-deriving is how two byte
    // sequences claiming to be "the same permit" get created, which is the
    // ambiguity the integrity tag exists to remove.
    let secret = ArkForgePairingSecret(secret: Self.pairingSecret, epoch: Self.pairingEpoch)
    let permit = vectorPermit(
      stepID: "STEP-WRITE-SYSTEM", attemptID: "ATTEMPT-1",
      privateActionPreimage: "write-partition:system")

    let first = ArkForgeSignedPermit(permit: permit, secret: secret)
    let second = ArkForgeSignedPermit(permit: permit, secret: secret)
    XCTAssertEqual(first.signingBody, second.signingBody)
    XCTAssertEqual(first.integrityTag, second.integrityTag)
    XCTAssertEqual(first, second, "the same permit and secret must be one signed value")
  }

  func testADifferentSecretOrEpochProducesADifferentTag() {
    let permit = vectorPermit(
      stepID: "STEP-RESET", attemptID: "ATTEMPT-2", privateActionPreimage: "reset-device")
    let real = ArkForgePairingSecret(secret: Self.pairingSecret, epoch: Self.pairingEpoch)
    var otherBytes = Self.pairingSecret
    otherBytes[0] ^= 0x01
    let other = ArkForgePairingSecret(secret: otherBytes, epoch: Self.pairingEpoch)

    XCTAssertNotEqual(
      ArkForgeSignedPermit(permit: permit, secret: real).integrityTag,
      ArkForgeSignedPermit(permit: permit, secret: other).integrityTag)

    // The epoch travels beside the tag rather than inside the body, so a
    // rotated epoch changes the envelope, not the signed bytes. ArkForge
    // rejects a stale epoch before it looks at the tag.
    let rotated = ArkForgePairingSecret(
      secret: Self.pairingSecret, epoch: ArkForgePairingEpoch(2))
    let rotatedPermit = ArkForgeSignedPermit(permit: permit, secret: rotated)
    XCTAssertEqual(rotatedPermit.signingBody, permit.signingBody)
    XCTAssertEqual(rotatedPermit.pairingEpoch.value, 2)
  }

  func testTheSecretNeverPrintsItself() {
    // A secret that lands in a log line or an error description is a secret on
    // disk. The type has no accessor for its bytes and both string
    // conversions are overridden.
    let secret = ArkForgePairingSecret(secret: Self.pairingSecret, epoch: Self.pairingEpoch)
    let rendered = "\(secret)" + String(reflecting: secret)
    XCTAssertFalse(rendered.contains("arkforge-arkdeck-permit-vector-secret"))
    XCTAssertTrue(rendered.contains("epoch: 1"))
  }

  // MARK: - the encoder's own rules

  func testMapKeysSortByEncodedBytesNotByText() {
    // RFC 8949 §4.2.1. "z" (one byte of text, head 0x61) encodes shorter than
    // "aa" (0x62), so it sorts first — the opposite of Swift's string order.
    // Getting this wrong is the single most likely reason a second
    // implementation disagrees, so it is asserted directly rather than only
    // through the vectors.
    let encoded = CanonicalCBOR.encoded(
      .map([("aa", .unsigned(1)), ("z", .unsigned(2))]))
    XCTAssertEqual(encoded, [0xa2, 0x61, 0x7a, 0x02, 0x62, 0x61, 0x61, 0x01])
    XCTAssertEqual(
      encoded, CanonicalCBOR.encoded(.map([("z", .unsigned(2)), ("aa", .unsigned(1))])),
      "listing order must not reach the encoding")
  }

  func testIntegersUseShortestForm() {
    XCTAssertEqual(CanonicalCBOR.encoded(.unsigned(0)), [0x00])
    XCTAssertEqual(CanonicalCBOR.encoded(.unsigned(23)), [0x17])
    XCTAssertEqual(CanonicalCBOR.encoded(.unsigned(24)), [0x18, 0x18])
    XCTAssertEqual(CanonicalCBOR.encoded(.unsigned(255)), [0x18, 0xff])
    XCTAssertEqual(CanonicalCBOR.encoded(.unsigned(256)), [0x19, 0x01, 0x00])
    XCTAssertEqual(CanonicalCBOR.encoded(.unsigned(65_536)), [0x1a, 0x00, 0x01, 0x00, 0x00])
    XCTAssertEqual(
      CanonicalCBOR.encoded(.unsigned(4_294_967_296)),
      [0x1b, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00])
  }

  func testBoolsAreSimpleValuesNotIntegers() {
    // A bool encoded as 0/1 decodes as an integer on the Rust side, and
    // `from_canonical_bytes` requires a Bool for `singleUse` — so this failure
    // mode shows up as "malformed permit", not as a wrong write. Asserted here
    // so the cause is named rather than inferred.
    XCTAssertEqual(CanonicalCBOR.encoded(.bool(true)), [0xf5])
    XCTAssertEqual(CanonicalCBOR.encoded(.bool(false)), [0xf4])
  }

  func testTextAndBytesAreDistinctMajorTypes() {
    // A 32-byte digest sent as hex text is 64 bytes of major type 3 where
    // ArkForge expects 32 bytes of major type 2.
    XCTAssertEqual(CanonicalCBOR.encoded(.text("a")), [0x61, 0x61])
    XCTAssertEqual(CanonicalCBOR.encoded(.bytes([0x61])), [0x41, 0x61])
  }

  func testTextIsEncodedAsUTF8WithoutNormalisation() {
    // NFC/NFD normalisation would silently change the bytes of any non-ASCII
    // identifier. Neither side normalises, so neither may.
    let composed = "\u{00e9}"  // é
    let decomposed = "e\u{0301}"
    XCTAssertNotEqual(
      CanonicalCBOR.encoded(.text(composed)), CanonicalCBOR.encoded(.text(decomposed)))
    XCTAssertEqual(CanonicalCBOR.encoded(.text(composed)), [0x62, 0xc3, 0xa9])
  }
}
