import ArkDeckCore
import ArkDeckWorkflows
import Foundation
import XCTest

@testable import ArkDeckCLI

/// The §14 machine-contract bundle is a projection of this build, and the
/// committed copy must be exactly that projection. These tests hold the
/// published files to the binary, replay the argv fixtures through the
/// parser, and check that the schemas pin the values the implementation
/// actually uses — so a registry change that forgets to regenerate the bundle,
/// or a bundle edited by hand, fails here rather than in a port.
final class CLIMachineContractTests: XCTestCase {
  private static let repositoryRoot: URL = {
    var url = URL(filePath: #filePath)
    for _ in 0..<5 { url.deleteLastPathComponent() }
    return url
  }()
  private static let contractsDirectory = repositoryRoot.appending(path: "openspec/contracts")
  private static let fixturesDirectory = repositoryRoot.appending(
    path: "Packages/ArkDeckKit/Tests/ArkDeckContractTests/Fixtures/CLI")
  private static let regenerate =
    "regenerate with `arkdeck maintainer contracts export --contracts-directory openspec/contracts "
    + "--fixtures-directory Packages/ArkDeckKit/Tests/ArkDeckContractTests/Fixtures/CLI`"

  // MARK: Drift

  func testPublishedBundleMatchesThisBuild() throws {
    let report = try CLIMachineContracts.check(
      contractsDirectory: Self.contractsDirectory, fixturesDirectory: Self.fixturesDirectory)
    XCTAssertTrue(
      report.isClean,
      "the committed machine contracts drifted from this build — drifted: \(report.drifted), "
        + "missing: \(report.missing), unexpected: \(report.unexpected); \(Self.regenerate)")
    XCTAssertEqual(
      report.checked,
      CLIMachineContracts.contractRelativePaths.count + (try CLIMachineContracts.fixtureProducts()).count)
  }

  func testProductsAreDeterministic() throws {
    XCTAssertEqual(try CLIMachineContracts.contractProducts(), try CLIMachineContracts.contractProducts())
    XCTAssertEqual(try CLIMachineContracts.fixtureProducts(), try CLIMachineContracts.fixtureProducts())
    XCTAssertEqual(
      try CLIMachineContracts.contractProducts().map(\.relativePath),
      CLIMachineContracts.contractRelativePaths)
  }

  func testJSONProductsParseAndYAMLProductsRoundTrip() throws {
    for product in try CLIMachineContracts.contractProducts() + CLIMachineContracts.fixtureProducts() {
      if product.relativePath.hasSuffix(".json") {
        XCTAssertNoThrow(
          try JSONSerialization.jsonObject(with: product.bytes, options: [.fragmentsAllowed]),
          "\(product.relativePath) is not JSON")
        XCTAssertTrue(product.text.hasSuffix("\n"), "\(product.relativePath) lacks its trailing LF")
        XCTAssertFalse(product.text.hasSuffix("\n\n"), "\(product.relativePath) ends with a blank line")
      } else if product.relativePath.hasSuffix(".jsonl") {
        let lines = product.text.split(separator: "\n", omittingEmptySubsequences: false)
        XCTAssertEqual(lines.count, 2, "\(product.relativePath) must be one line plus its delimiter")
        XCTAssertNoThrow(try JSONSerialization.jsonObject(with: Data(lines[0].utf8)))
      }
    }
    let yamlDocuments: [(String, JSONValue)] = [
      ("cli-command-registry.yaml", CLIMachineContracts.commandRegistryDocument()),
      ("cli-error-registry.yaml", CLIMachineContracts.errorRegistryDocument()),
      ("app-product-capability-registry.yaml", CLIMachineContracts.appRegistryDocument()),
    ]
    let products = Dictionary(
      uniqueKeysWithValues: try CLIMachineContracts.contractProducts().map { ($0.relativePath, $0) })
    for (name, document) in yamlDocuments {
      let product = try XCTUnwrap(products[name])
      XCTAssertTrue(product.text.hasPrefix("# Generated by `arkdeck maintainer contracts export`"))
      let parsed = try YAMLSubset.parse(product.text)
      XCTAssertEqual(parsed, document, "\(name) does not read back as the document it was rendered from")
    }
  }

  // MARK: Feature coverage (§14, §18)

  func testFeatureCoverageIsClosedAndDeclaresFullFunction() throws {
    let coverage = try CLIMachineContracts.FeatureCoverage.build()
    let features = Dictionary(uniqueKeysWithValues: coverage.entries.map { ($0.feature, $0) })
    XCTAssertEqual(features.count, coverage.entries.count, "feature ids must be unique")

    for method in CLIControlMethodRegistry.classifiedMethods {
      XCTAssertNotNil(features[method], "daemon method \(method) has no coverage entry")
    }
    XCTAssertEqual(features[ArkDeckControlProtocol.bootstrapMethod]?.classification, "internal")
    for descriptor in RuntimeOperationCatalog.operations {
      XCTAssertNotNil(features[descriptor.reference], "Catalog operation \(descriptor.reference) is uncovered")
    }
    for capability in AppProductCapabilityRegistry.capabilities {
      let entry = try XCTUnwrap(features[capability.id], "App capability \(capability.id) is uncovered")
      XCTAssertEqual(entry.classification, capability.classification.rawValue)
      XCTAssertEqual(entry.owner, capability.owner)
    }
    let referenced = Set(coverage.entries.flatMap(\.referencedLeaves))
    for (_, leaf) in CLICommandRegistry.allLeaves() {
      XCTAssertTrue(referenced.contains(leaf.canonicalCommand), "leaf \(leaf.canonicalCommand) is uncovered")
    }

    // Spot facts a reader of the table relies on.
    XCTAssertEqual(features["job.evidence"]?.classification, "direct")
    XCTAssertEqual(features["job.evidence"]?.targetCommand, "arkdeck job evidence --job <job-id>")
    XCTAssertEqual(features["job.evidence"]?.conformanceFixture, "argv/job.evidence.json")
    XCTAssertEqual(features["capability.draft"]?.classification, "refused")
    XCTAssertEqual(features["artifact.import.append"]?.classification, "internal")
    XCTAssertEqual(features["session.list"]?.classification, "local")
    XCTAssertEqual(features["runtime.hdc-status"]?.lifecycle, "legacy")
    XCTAssertEqual(features["agent.chat"]?.lifecycle, "removed")
    XCTAssertEqual(features["agent.chat"]?.classification, "refused")
    XCTAssertEqual(features["observe.device@1"]?.classification, "direct")
    XCTAssertEqual(features["observe.device@1"]?.targetCommand, "arkdeck target observe")
    XCTAssertEqual(features["app.settings.servers"]?.classification, "platformService")
    XCTAssertEqual(features["app.design.components"]?.classification, "presentation")

    let generic = coverage.entries.filter { $0.classification == "generic" }
    for entry in generic {
      XCTAssertTrue(entry.source.hasPrefix("catalog:"))
      XCTAssertEqual(
        entry.targetCommand,
        "arkdeck job submit --operation \(entry.feature) --inputs-file <path>")
    }
    XCTAssertTrue(
      coverage.entries.filter { $0.classification == "blocked" }.isEmpty,
      "§18 full function requires no blocked entry")
    guard case .object(let document) = coverage.document,
      case .object(let summary)? = document["summary"]
    else { return XCTFail("coverage document has no summary") }
    XCTAssertEqual(summary["fullFunction"], .bool(true))
    XCTAssertEqual(summary["entries"], .integer(Int64(coverage.entries.count)))
  }

  func testCoverageVocabulariesAreClosed() throws {
    let coverage = try CLIMachineContracts.FeatureCoverage.build()
    let classifications = Set(ProductCoverageClassification.allCases.map(\.rawValue))
    let lifecycles = Set(CLIMachineContracts.FeatureCoverage.lifecycleVocabulary)
    for entry in coverage.entries {
      XCTAssertTrue(classifications.contains(entry.classification), entry.feature)
      XCTAssertTrue(lifecycles.contains(entry.lifecycle), entry.feature)
      XCTAssertEqual(entry.classification, entry.targetClassification, entry.feature)
      XCTAssertFalse(entry.requiredPlatforms.isEmpty, entry.feature)
      XCTAssertEqual(entry.requiredPlatforms.first, "macos", entry.feature)
      if let fixture = entry.conformanceFixture {
        XCTAssertTrue(fixture.hasPrefix("argv/"), entry.feature)
      }
    }
  }

  // MARK: Argv fixtures

  func testCommittedArgvFixturesReplayThroughTheParser() throws {
    let argvDirectory = Self.fixturesDirectory.appending(path: "argv")
    let files = try FileManager.default.contentsOfDirectory(atPath: argvDirectory.path)
      .filter { $0.hasSuffix(".json") }.sorted()
    XCTAssertEqual(files.count, CLICommandRegistry.allLeaves().count, Self.regenerate)
    var replayed = 0
    for file in files {
      let data = try Data(contentsOf: argvDirectory.appending(path: file))
      let fixture = try JSONValueBridge.value(from: data)
      guard case .object(let fields) = fixture,
        case .string(let command)? = fields["command"],
        case .string(let kind)? = fields["kind"],
        case .array(let cases)? = fields["cases"]
      else { return XCTFail("\(file) is not an argv fixture") }
      XCTAssertEqual(fields["schemaVersion"], .string(CLIMachineContracts.argvFixtureSchemaVersion))
      XCTAssertEqual(file, "\(command).json")
      for entry in cases {
        guard case .object(let entryFields) = entry,
          case .string(let name)? = entryFields["name"],
          case .array(let argvValues)? = entryFields["argv"],
          let expected = entryFields["expected"]
        else { return XCTFail("\(file) has a malformed case") }
        let argv = argvValues.compactMap { value -> String? in
          if case .string(let text) = value { return text }
          return nil
        }
        let parsed = CLIArgumentParser.parse(argv)
        let actual = CLIMachineContracts.ArgvFixtures.outcome(parsed)
        XCTAssertEqual(
          try CLICanonicalJSON.canonicalString(actual),
          try CLICanonicalJSON.canonicalString(expected),
          "\(file) case \(name): \(argv); \(Self.regenerate)")
        replayed += 1
        guard name == "valid" else { continue }
        switch (kind, parsed) {
        case ("executable", .success(.dispatch(_, let leaf, _))):
          XCTAssertEqual(leaf.canonicalCommand, command)
        case ("executable", .success):
          break  // help/commands/completion answer without dispatching
        case ("tombstone", .failure(let error)):
          XCTAssertEqual(error.code, .commandRemoved, file)
        case ("refused", .failure(let error)):
          XCTAssertEqual(error.code.category, .usage, file)
        default:
          XCTFail("\(file): the valid case of a \(kind) leaf produced an unexpected outcome")
        }
      }
    }
    XCTAssertGreaterThan(replayed, files.count * 2)
  }

  func testGeneratedValidArgvNeverUsesAnUnpublishedOption() throws {
    for (path, leaf) in CLICommandRegistry.allLeaves() {
      let argv = CLIMachineContracts.ArgvFixtures.validArgv(path: path, leaf: leaf)
      for option in leaf.options where !option.isPublished {
        XCTAssertFalse(argv.contains(option.name), "\(leaf.canonicalCommand) fixture uses \(option.name)")
      }
    }
  }

  // MARK: Envelopes and sample documents

  func testEnvelopeFixturesAreTheRenderedEnvelopes() throws {
    let success = try JSONValueBridge.value(
      from: Data(contentsOf: Self.fixturesDirectory.appending(path: "envelopes/result-success.json")))
    guard case .object(let fields) = success, case .object(let meta)? = fields["meta"] else {
      return XCTFail("result-success.json is not an envelope")
    }
    XCTAssertEqual(fields["schemaVersion"], .string(CLIResultEnvelope.schemaVersion))
    XCTAssertEqual(fields["ok"], .bool(true))
    XCTAssertEqual(fields["command"], .string("job.status"))
    XCTAssertEqual(meta["controlRequestId"], .string(CLIMachineContracts.fixtureControlRequestID))
    XCTAssertEqual(meta["cliVersion"], .string(CLIProductVersion.product))

    // §12: a tombstone answers `commandRemoved` and carries its lifecycle and
    // exact replacement in `error.details`, not in `meta.lifecycle` (which is
    // reserved for spellings that still run).
    let removed = try JSONValueBridge.value(
      from: Data(contentsOf: Self.fixturesDirectory.appending(path: "envelopes/result-removed-command.json")))
    guard case .object(let removedFields) = removed,
      case .object(let error)? = removedFields["error"],
      case .object(let details)? = error["details"],
      case .object(let removedMeta)? = removedFields["meta"]
    else { return XCTFail("result-removed-command.json is not a failure envelope with details") }
    XCTAssertEqual(removedFields["ok"], .bool(false))
    XCTAssertEqual(error["code"], .string(CLIErrorCode.commandRemoved.rawValue))
    XCTAssertEqual(details["lifecycleStatus"], .string("removed"))
    XCTAssertEqual(details["replacementArgvPattern"], .string("arkdeck agent run"))
    XCTAssertNil(removedMeta["lifecycle"])

    let terminal = try String(
      contentsOf: Self.fixturesDirectory.appending(path: "envelopes/event-terminal-failure.jsonl"),
      encoding: .utf8)
    XCTAssertTrue(terminal.contains("\"type\":\"terminal\""))
    XCTAssertTrue(terminal.contains("\"exitCode\":\(CLIErrorCode.runtimeUnavailable.exitCode)"))
  }

  func testNextActionFixturesFollowTheirSchemaBranch() throws {
    let schema = try JSONValueBridge.value(
      from: Data(contentsOf: Self.contractsDirectory.appending(path: "cli-next-action.schema.json")))
    guard case .object(let schemaFields) = schema, case .object(let branches)? = schemaFields["$defs"]
    else { return XCTFail("next-action schema has no branches") }
    XCTAssertEqual(schemaFields["title"], .string(CLIMachineContracts.nextActionSchemaVersion))
    XCTAssertEqual(Set(branches.keys), ["wait", "humanAction", "reconcile", "cleanup", "readResult"])
    let directory = Self.fixturesDirectory.appending(path: "next-action")
    let files = try FileManager.default.contentsOfDirectory(atPath: directory.path).sorted()
    XCTAssertEqual(Set(files), Set(branches.keys.map { "\($0).json" } + ["null.json"]))
    for file in files {
      let document = try JSONValueBridge.value(from: Data(contentsOf: directory.appending(path: file)))
      if file == "null.json" {
        XCTAssertEqual(document, .null)
        continue
      }
      let kind = String(file.dropLast(".json".count))
      guard case .object(let branch)? = branches[kind],
        case .array(let required)? = branch["required"],
        case .object(let properties)? = branch["properties"],
        case .object(let fields) = document,
        case .object(let reasonCode)? = properties["reasonCode"]
      else { return XCTFail("\(file) or its branch is malformed"); }
      XCTAssertEqual(fields["kind"], .string(kind))
      let requiredKeys = Set(required.compactMap { value -> String? in
        if case .string(let text) = value { return text }
        return nil
      })
      XCTAssertTrue(requiredKeys.isSubset(of: Set(fields.keys)), "\(file) misses a required field")
      XCTAssertTrue(Set(fields.keys).isSubset(of: Set(properties.keys)), "\(file) carries a field outside its branch")
      if case .array(let codes)? = reasonCode["enum"] {
        XCTAssertTrue(codes.contains(fields["reasonCode"] ?? .null), "\(file) uses a reason code outside the vocabulary")
      }
    }
  }

  func testPageFixturesFollowThePageShape() throws {
    let directory = Self.fixturesDirectory.appending(path: "page")
    for file in ["snapshot.json", "event-stream.json"] {
      let page = try JSONValueBridge.value(from: Data(contentsOf: directory.appending(path: file)))
      guard case .object(let fields) = page else { return XCTFail(file) }
      XCTAssertEqual(fields["schemaVersion"], .string(CLIMachineContracts.pageSchemaVersion))
      XCTAssertEqual(
        Set(fields.keys),
        ["schemaVersion", "pageKind", "items", "order", "snapshotRevision", "hasMore", "nextCursor"])
      if fields["pageKind"] == .string("eventStream") {
        XCTAssertEqual(fields["order"], .string("streamPositionAsc"))
        XCTAssertNotEqual(fields["nextCursor"], .null, "an event page always returns its high-water cursor")
      } else if fields["hasMore"] == .bool(false) {
        XCTAssertEqual(fields["nextCursor"], .null)
      }
    }
  }

  // MARK: Schemas pin the implementation

  func testResultSchemaPinsTheErrorRegistryAndTheCorrelationGrammar() throws {
    let schema = try JSONValueBridge.value(
      from: Data(contentsOf: Self.contractsDirectory.appending(path: "cli-result.schema.json")))
    guard case .object(let fields) = schema,
      case .object(let defs)? = fields["$defs"],
      case .object(let error)? = defs["error"],
      case .object(let errorProperties)? = error["properties"],
      case .object(let code)? = errorProperties["code"],
      case .array(let codes)? = code["enum"],
      case .object(let meta)? = defs["meta"],
      case .object(let metaProperties)? = meta["properties"],
      case .object(let controlRequestID)? = metaProperties["controlRequestId"],
      case .string(let pattern)? = controlRequestID["pattern"]
    else { return XCTFail("result schema lost its shape") }
    XCTAssertEqual(fields["title"], .string(CLIResultEnvelope.schemaVersion))
    XCTAssertEqual(codes, CLIErrorCode.allCases.map { .string($0.rawValue) })
    XCTAssertEqual(defs["errorRegistryVersion"], .object(["const": .string(CLIErrorRegistryVersion.current)]))

    let regex = try NSRegularExpression(pattern: pattern)
    let samples = [
      "ctl-1", "a", "ctl-fixture-0001", "A.b:c_d-e", "", "-x", ".x", "ctl 1", "ctl/1",
      String(repeating: "a", count: 128), String(repeating: "a", count: 129), "é",
    ]
    for sample in samples {
      let matches = regex.firstMatch(
        in: sample, range: NSRange(sample.startIndex..., in: sample)) != nil
      XCTAssertEqual(
        matches, CLIControlRequestID.isValid(sample),
        "the published pattern and the parser disagree on \(sample.debugDescription)")
    }
  }

  func testStreamAndPageSchemasPinTheirVersions() throws {
    let page = try JSONValueBridge.value(
      from: Data(contentsOf: Self.contractsDirectory.appending(path: "cli-page.schema.json")))
    guard case .object(let pageFields) = page,
      case .object(let pageProperties)? = pageFields["properties"]
    else { return XCTFail("page schema lost its shape") }
    XCTAssertEqual(pageFields["title"], .string(try XCTUnwrap(CLIProductVersion.pageSchema)))
    XCTAssertEqual(pageProperties["schemaVersion"], .object(["const": .string(CLIMachineContracts.pageSchemaVersion)]))

    let event = try JSONValueBridge.value(
      from: Data(contentsOf: Self.contractsDirectory.appending(path: "cli-event.schema.json")))
    guard case .object(let eventFields) = event else { return XCTFail("event schema lost its shape") }
    XCTAssertEqual(eventFields["title"], .string(try XCTUnwrap(CLIProductVersion.eventSchema)))
    XCTAssertEqual(eventFields["title"], .string(CLIEventEnvelope.schemaVersion))
  }

  func testControlPlaneSchemaPinsTheMethodSetAndProtocolVersions() throws {
    let schema = try JSONValueBridge.value(
      from: Data(contentsOf: Self.contractsDirectory.appending(path: "runtime-control-plane.schema.json")))
    guard case .object(let fields) = schema,
      case .object(let defs)? = fields["$defs"],
      case .object(let request)? = defs["request"],
      case .object(let properties)? = request["properties"],
      case .object(let method)? = properties["method"],
      case .array(let methods)? = method["enum"],
      case .object(let protocolVersion)? = properties["protocolVersion"],
      case .array(let versions)? = protocolVersion["enum"]
    else { return XCTFail("control-plane schema lost its shape") }
    let expectedMethods = CLIControlMethodRegistry.classifiedMethods
      .union([ArkDeckControlProtocol.bootstrapMethod]).sorted().map { JSONValue.string($0) }
    XCTAssertEqual(methods, expectedMethods)
    XCTAssertEqual(versions, ArkDeckControlProtocol.supportedExactVersions.map { .string($0) })
    XCTAssertEqual(fields["x-arkdeck-targetProtocolVersion"], .string(ArkDeckControlProtocol.targetVersion))
  }

  func testVersionPinsAreSingleSourced() throws {
    XCTAssertEqual(CLIProductVersion.pageSchema, "arkdeck.cli.page/1")
    XCTAssertEqual(CLIProductVersion.nextActionSchema, "arkdeck.cli.next-action/1")
    XCTAssertEqual(CLIProductVersion.pageSchema, CLIMachineContracts.pageSchemaVersion)
    XCTAssertEqual(CLIProductVersion.nextActionSchema, CLIMachineContracts.nextActionSchemaVersion)
    XCTAssertEqual(CLIMachineContracts.contractRelativePaths.count, 10)

    // `arkdeck --version --output json` and the bundle name the same versions.
    guard case .object(let version) = CLIHelpRenderer.versionResult() else {
      return XCTFail("version projection lost its shape")
    }
    XCTAssertEqual(version["pageSchemaVersion"], .string(CLIMachineContracts.pageSchemaVersion))
    XCTAssertEqual(version["nextActionSchemaVersion"], .string(CLIMachineContracts.nextActionSchemaVersion))
    XCTAssertEqual(version["resultSchemaVersion"], .string(CLIResultEnvelope.schemaVersion))
    XCTAssertEqual(version["eventSchemaVersion"], .string(CLIEventEnvelope.schemaVersion))
    XCTAssertEqual(version["errorRegistryVersion"], .string(CLIErrorRegistryVersion.current))
    XCTAssertEqual(version["canonicalJsonVersion"], .string(CLICanonicalJSON.version))
    XCTAssertEqual(version["machineContractVersion"], .string(CLIProductVersion.machineContract))
    for name in ["cli-result", "cli-page", "cli-event", "cli-next-action"] {
      let schema = try JSONValueBridge.value(
        from: Data(contentsOf: Self.contractsDirectory.appending(path: "\(name).schema.json")))
      guard case .object(let fields) = schema else { return XCTFail(name) }
      XCTAssertEqual(fields["x-arkdeck-bundleVersion"], version["machineContractVersion"], name)
    }
    let registry = try YAMLSubset.parse(
      String(contentsOf: Self.contractsDirectory.appending(path: "cli-command-registry.yaml"), encoding: .utf8))
    guard case .object(let registryFields) = registry,
      case .object(let projection) = CLIRegistryProjection.result()
    else { return XCTFail("registry product lost its shape") }
    XCTAssertEqual(registryFields["schemaVersion"], version["commandRegistrySchemaVersion"])
    XCTAssertEqual(registryFields["commands"], projection["commands"], "the YAML registry and `commands --output json` differ")
  }

  // MARK: Schemas accept the real output and reject counterexamples

  private func schema(_ name: String) throws -> JSONValue {
    try JSONValueBridge.value(
      from: Data(contentsOf: Self.contractsDirectory.appending(path: "\(name).schema.json")))
  }

  private func fixture(_ path: String) throws -> JSONValue {
    try JSONValueBridge.value(from: Data(contentsOf: Self.fixturesDirectory.appending(path: path)))
  }

  private func jsonlLine(_ path: String) throws -> JSONValue {
    let text = try String(contentsOf: Self.fixturesDirectory.appending(path: path), encoding: .utf8)
    return try JSONValueBridge.value(from: Data(text.split(separator: "\n")[0].utf8))
  }

  private func mutate(_ value: JSONValue, _ body: (inout [String: JSONValue]) -> Void) -> JSONValue {
    guard case .object(var fields) = value else { return value }
    body(&fields)
    return .object(fields)
  }

  func testResultSchemaAcceptsRenderedEnvelopesAndRejectsCounterexamples() throws {
    let schema = try schema("cli-result")
    for name in ["result-success", "result-deprecated-alias", "result-argv-failure", "result-removed-command"] {
      XCTAssertTrue(JSONSchemaSubset.validate(try fixture("envelopes/\(name).json"), against: schema), name)
    }
    let success = try fixture("envelopes/result-success.json")
    let failure = try fixture("envelopes/result-argv-failure.json")
    XCTAssertFalse(JSONSchemaSubset.validate(mutate(success) { $0["error"] = .object([:]) }, against: schema), "ok:true with an error")
    XCTAssertFalse(JSONSchemaSubset.validate(mutate(success) { $0["meta"] = nil }, against: schema), "missing meta")
    XCTAssertFalse(JSONSchemaSubset.validate(mutate(success) { $0["extra"] = .bool(true) }, against: schema), "unknown top-level field")
    XCTAssertFalse(
      JSONSchemaSubset.validate(
        mutate(failure) { fields in
          fields["error"] = self.mutate(fields["error"] ?? .null) { $0["code"] = .string("notARegisteredCode") }
        }, against: schema), "unregistered error code")
    XCTAssertFalse(
      JSONSchemaSubset.validate(
        mutate(success) { fields in
          fields["meta"] = self.mutate(fields["meta"] ?? .null) { $0["controlRequestId"] = .string("") }
        }, against: schema), "empty correlation identity")
  }

  func testPageSchemaAcceptsBothPageKindsAndRejectsCounterexamples() throws {
    let schema = try schema("cli-page")
    let snapshot = try fixture("page/snapshot.json")
    let stream = try fixture("page/event-stream.json")
    XCTAssertTrue(JSONSchemaSubset.validate(snapshot, against: schema))
    XCTAssertTrue(JSONSchemaSubset.validate(stream, against: schema))
    XCTAssertFalse(JSONSchemaSubset.validate(mutate(snapshot) { $0["nextCursor"] = .string("c") }, against: schema), "exhausted snapshot with a cursor")
    XCTAssertFalse(JSONSchemaSubset.validate(mutate(snapshot) { $0["hasMore"] = .bool(true) }, against: schema), "hasMore without a cursor")
    XCTAssertFalse(JSONSchemaSubset.validate(mutate(stream) { $0["nextCursor"] = .null }, against: schema), "event page without its high-water cursor")
    XCTAssertFalse(JSONSchemaSubset.validate(mutate(stream) { $0["order"] = .string("createdAtDescJobIdAsc") }, against: schema), "event page with a snapshot order")
    XCTAssertFalse(JSONSchemaSubset.validate(mutate(stream) { $0["items"] = .array([.object([:])]) }, against: schema), "event item without identity")
    XCTAssertFalse(JSONSchemaSubset.validate(mutate(snapshot) { $0["pageKind"] = .string("cursor") }, against: schema), "unknown page kind")
  }

  func testEventSchemaAcceptsEveryFrameAndRejectsCounterexamples() throws {
    let schema = try schema("cli-event")
    let runtimeEvent = try jsonlLine("envelopes/event-runtime-event.jsonl")
    let terminalSuccess = try jsonlLine("envelopes/event-terminal-success.jsonl")
    let terminalFailure = try jsonlLine("envelopes/event-terminal-failure.jsonl")
    for frame in [runtimeEvent, terminalSuccess, terminalFailure] {
      XCTAssertTrue(JSONSchemaSubset.validate(frame, against: schema))
    }
    XCTAssertFalse(JSONSchemaSubset.validate(mutate(terminalSuccess) { $0["exitCode"] = nil }, against: schema), "terminal frame without exit code")
    XCTAssertFalse(JSONSchemaSubset.validate(mutate(terminalSuccess) { $0["error"] = .object([:]) }, against: schema), "ok terminal frame with an error")
    XCTAssertFalse(JSONSchemaSubset.validate(mutate(terminalFailure) { $0["result"] = .null }, against: schema), "failed terminal frame with a result")
    XCTAssertFalse(JSONSchemaSubset.validate(mutate(runtimeEvent) { $0["eventId"] = nil }, against: schema), "runtime event without identity")
    XCTAssertFalse(JSONSchemaSubset.validate(mutate(runtimeEvent) { $0["sequence"] = .integer(0) }, against: schema), "sequence starts at one")
  }

  func testNextActionSchemaAcceptsEveryBranchAndRejectsCounterexamples() throws {
    let schema = try schema("cli-next-action")
    for name in ["null", "wait", "humanAction", "reconcile", "cleanup", "readResult"] {
      XCTAssertTrue(JSONSchemaSubset.validate(try fixture("next-action/\(name).json"), against: schema), name)
    }
    let wait = try fixture("next-action/wait.json")
    let human = try fixture("next-action/humanAction.json")
    let reconcile = try fixture("next-action/reconcile.json")
    XCTAssertFalse(JSONSchemaSubset.validate(mutate(wait) { $0["resumeReference"] = .string("r") }, against: schema), "wait may not carry a resume reference")
    XCTAssertFalse(JSONSchemaSubset.validate(mutate(wait) { $0["retryAfter"] = .string("0s") }, against: schema), "zero retry hint")
    XCTAssertFalse(
      JSONSchemaSubset.validate(
        mutate(wait) { $0["resource"] = .object(["kind": .string("agentExecution"), "id": .string("x")]) },
        against: schema), "wait resource must mirror its owner")
    XCTAssertFalse(JSONSchemaSubset.validate(mutate(human) { $0["resumeReference"] = nil }, against: schema), "human action without resume reference")
    XCTAssertFalse(JSONSchemaSubset.validate(mutate(reconcile) { $0["reasonCode"] = .string("job.running") }, against: schema), "reconcile with a wait reason")
    XCTAssertFalse(JSONSchemaSubset.validate(mutate(wait) { $0["kind"] = .string("retry") }, against: schema), "unknown kind")
    XCTAssertFalse(JSONSchemaSubset.validate(.object([:]), against: schema), "empty object")
  }

  func testControlPlaneSchemaAcceptsRealFramesAndRejectsCounterexamples() throws {
    let schema = try schema("runtime-control-plane")
    let request = try JSONValueBridge.value(
      from: ArkDeckAgentXPC.requestFrame(
        method: "job.status", params: ["jobId": .string("job-1")], requestID: "req-1",
        protocolVersion: ArkDeckControlProtocol.targetVersion))
    XCTAssertTrue(JSONSchemaSubset.validate(request, against: schema))
    let response: JSONValue = .object(["id": .string("req-1"), "ok": .bool(true), "result": .object([:])])
    XCTAssertTrue(JSONSchemaSubset.validate(response, against: schema))
    let failed: JSONValue = .object([
      "id": .string("req-1"), "ok": .bool(false),
      "error": .object(["code": .string("resourceNotFound"), "message": .string("no such Job")]),
    ])
    XCTAssertTrue(JSONSchemaSubset.validate(failed, against: schema))
    XCTAssertFalse(JSONSchemaSubset.validate(mutate(request) { $0["method"] = .string("job.nope") }, against: schema), "unpublished method")
    XCTAssertFalse(JSONSchemaSubset.validate(mutate(request) { $0["protocolVersion"] = .string("3.0.0") }, against: schema), "unsupported protocol version")
    XCTAssertFalse(JSONSchemaSubset.validate(mutate(response) { $0["error"] = .object(["code": .string("x"), "message": .string("y")]) }, against: schema), "ok response with an error")
    XCTAssertFalse(JSONSchemaSubset.validate(mutate(failed) { $0["error"] = nil }, against: schema), "failed response without an error")
  }

  func testRegistryProjectionCarriesLifecycleOnEveryLeaf() throws {
    guard case .object(let projection) = CLIRegistryProjection.result(),
      case .array(let commands)? = projection["commands"]
    else { return XCTFail("projection lost its shape") }
    for command in commands {
      guard case .object(let fields) = command else { return XCTFail("command is not an object") }
      XCTAssertNotNil(fields["lifecycleStatus"], "\(fields["command"] ?? .null)")
      XCTAssertNotNil(fields["replacementArgvPattern"], "\(fields["command"] ?? .null)")
      if fields["kind"] == .string("tombstone") {
        XCTAssertEqual(fields["lifecycleStatus"], .string("removed"))
      }
    }
  }

  // MARK: App capability registry

  func testAppCapabilityRegistryCoversEveryImplementationSurface() throws {
    let coverage = try JSONValueBridge.value(
      from: Data(contentsOf: Self.repositoryRoot.appending(path: "docs/design/implementation-coverage.json")))
    guard case .object(let fields) = coverage, case .array(let surfaceIDs)? = fields["surfaceIDs"] else {
      return XCTFail("implementation-coverage.json has no surfaceIDs")
    }
    let published = Set(surfaceIDs.compactMap { value -> String? in
      if case .string(let text) = value { return text }
      return nil
    })
    let registered = AppProductCapabilityRegistry.capabilities
    let surfaces = Set(registered.map(\.surface))
    XCTAssertEqual(surfaces.count, registered.count, "surfaces must be unique")
    XCTAssertEqual(Set(registered.map(\.id)).count, registered.count, "ids must be unique")
    XCTAssertTrue(published.isSubset(of: surfaces), "unregistered surfaces: \(published.subtracting(surfaces).sorted())")
    for extra in surfaces.subtracting(published) {
      XCTAssertTrue(extra.hasPrefix("menu."), "surface \(extra) is neither a reviewed surface nor a menu command")
    }
    let index = try CLIMachineContracts.FeatureCoverage.LeafIndex()
    for capability in registered {
      XCTAssertEqual(capability.id, "app.\(capability.surface)")
      XCTAssertFalse(capability.owner.isEmpty, capability.id)
      for pattern in capability.cliEquivalent {
        XCTAssertNoThrow(try index.resolve(pattern: pattern), "\(capability.id): \(pattern)")
      }
      switch capability.classification {
      case .presentation, .platformService, .refused:
        break
      default:
        XCTAssertFalse(capability.cliEquivalent.isEmpty, "\(capability.id) claims CLI reach without a command")
      }
    }
    XCTAssertEqual(AppNavigationCapability.allCases.count, 8)
    for navigation in AppNavigationCapability.allCases {
      XCTAssertNotNil(AppProductCapabilityRegistry.capability(id: navigation.rawValue), navigation.rawValue)
    }
    for tab in AppDebugTabCapability.allCases {
      XCTAssertNotNil(AppProductCapabilityRegistry.capability(id: tab.rawValue), tab.rawValue)
    }
    for tab in AppViewerTabCapability.allCases {
      XCTAssertNotNil(AppProductCapabilityRegistry.capability(id: tab.rawValue), tab.rawValue)
    }
  }

  // MARK: Export and check behaviour

  func testExportThenCheckIsCleanAndCheckReportsEveryKindOfDrift() throws {
    let root = FileManager.default.temporaryDirectory.appending(path: "cli-contracts-\(UUID().uuidString)")
    let contracts = root.appending(path: "contracts")
    let fixtures = root.appending(path: "fixtures")
    defer { try? FileManager.default.removeItem(at: root) }

    let exported = try CLIMachineContracts.export(contractsDirectory: contracts, fixturesDirectory: fixtures)
    XCTAssertEqual(exported.removed, [])
    XCTAssertEqual(
      exported.written.count,
      CLIMachineContracts.contractRelativePaths.count + (try CLIMachineContracts.fixtureProducts()).count)
    XCTAssertTrue(try CLIMachineContracts.check(contractsDirectory: contracts, fixturesDirectory: fixtures).isClean)

    try Data("drift\n".utf8).write(to: contracts.appending(path: "cli-error-registry.yaml"))
    try FileManager.default.removeItem(at: fixtures.appending(path: "index.json"))
    try Data("{}\n".utf8).write(to: fixtures.appending(path: "argv/stray.json"))
    let report = try CLIMachineContracts.check(contractsDirectory: contracts, fixturesDirectory: fixtures)
    XCTAssertFalse(report.isClean)
    XCTAssertEqual(report.drifted, ["contracts/cli-error-registry.yaml"])
    XCTAssertEqual(report.missing, ["fixtures/index.json"])
    XCTAssertEqual(report.unexpected, ["fixtures/argv/stray.json"])

    let again = try CLIMachineContracts.export(contractsDirectory: contracts, fixturesDirectory: fixtures)
    XCTAssertEqual(again.removed, ["fixtures/argv/stray.json"])
    XCTAssertTrue(try CLIMachineContracts.check(contractsDirectory: contracts, fixturesDirectory: fixtures).isClean)
  }
}

// MARK: - Helpers

/// Foundation JSON to `JSONValue`, for reading committed products back.
enum JSONValueBridge {
  static func value(from data: Data) throws -> JSONValue {
    try value(JSONSerialization.jsonObject(with: data, options: [.fragmentsAllowed]))
  }

  static func value(_ object: Any) throws -> JSONValue {
    switch object {
    case is NSNull:
      return .null
    case let number as NSNumber:
      if CFGetTypeID(number) == CFBooleanGetTypeID() { return .bool(number.boolValue) }
      if let integer = Int64(exactly: number) { return .integer(integer) }
      return .number(number.doubleValue)
    case let text as String:
      return .string(text)
    case let items as [Any]:
      return .array(try items.map(value))
    case let fields as [String: Any]:
      return .object(try fields.mapValues(value))
    default:
      throw NSError(domain: "JSONValueBridge", code: 1, userInfo: [NSLocalizedDescriptionKey: "\(object)"])
    }
  }
}

/// A reader for exactly the YAML subset `ContractYAML` emits: block mappings
/// and sequences whose scalars, keys included, are JSON scalars. It exists so
/// the test can prove the YAML products read back as the documents they were
/// rendered from without a YAML library in the package.
enum YAMLSubset {
  struct Failure: Error { let message: String }

  static func parse(_ text: String) throws -> JSONValue {
    let lines = text.split(separator: "\n", omittingEmptySubsequences: false)
      .map(String.init)
      .filter { !$0.hasPrefix("#") && !$0.trimmingCharacters(in: .whitespaces).isEmpty }
    var cursor = 0
    let value = try parseBlock(lines, &cursor, indent: 0)
    guard cursor == lines.count else { throw Failure(message: "trailing content at line \(cursor)") }
    return value
  }

  private static func indentation(_ line: String) -> Int {
    line.prefix { $0 == " " }.count
  }

  private static func parseBlock(_ lines: [String], _ cursor: inout Int, indent: Int) throws -> JSONValue {
    guard cursor < lines.count else { throw Failure(message: "unexpected end") }
    let first = lines[cursor]
    guard indentation(first) == indent else { throw Failure(message: "bad indent at line \(cursor)") }
    let body = String(first.dropFirst(indent))
    if body.hasPrefix("- ") { return try parseSequence(lines, &cursor, indent: indent) }
    if body == "[]" || body == "{}" || !body.hasPrefix("\"") {
      cursor += 1
      return try scalar(body)
    }
    return try parseMapping(lines, &cursor, indent: indent)
  }

  private static func parseMapping(_ lines: [String], _ cursor: inout Int, indent: Int) throws -> JSONValue {
    var fields: [String: JSONValue] = [:]
    while cursor < lines.count, indentation(lines[cursor]) == indent, !lines[cursor].dropFirst(indent).hasPrefix("- ") {
      let body = String(lines[cursor].dropFirst(indent))
      let (keyText, rest) = try splitKey(body)
      guard case .string(let key) = try scalar(keyText) else { throw Failure(message: "key is not a string") }
      cursor += 1
      if rest.isEmpty {
        fields[key] = try parseBlock(lines, &cursor, indent: indent + 2)
      } else {
        fields[key] = try scalar(rest)
      }
    }
    return .object(fields)
  }

  private static func parseSequence(_ lines: [String], _ cursor: inout Int, indent: Int) throws -> JSONValue {
    var items: [JSONValue] = []
    while cursor < lines.count, indentation(lines[cursor]) == indent, lines[cursor].dropFirst(indent).hasPrefix("- ") {
      let rest = String(lines[cursor].dropFirst(indent + 2))
      // A quoted token followed by `:` opens a nested mapping on this line; a
      // bare quoted token is a scalar item.
      let opensMapping = rest.hasPrefix("\"") && (try? splitKey(rest)) != nil
      if opensMapping || rest.hasPrefix("- ") {
        // A nested block whose first line shares the `- ` line: re-indent it
        // and parse the block at indent + 2.
        var nested = [String(repeating: " ", count: indent + 2) + rest]
        cursor += 1
        while cursor < lines.count, indentation(lines[cursor]) >= indent + 2 {
          nested.append(lines[cursor])
          cursor += 1
        }
        var nestedCursor = 0
        items.append(try parseBlock(nested, &nestedCursor, indent: indent + 2))
        guard nestedCursor == nested.count else { throw Failure(message: "nested block not consumed") }
      } else {
        cursor += 1
        items.append(try scalar(rest))
      }
    }
    return .array(items)
  }

  /// Splits `"key": rest` into the quoted key and the remainder after `: `.
  private static func splitKey(_ body: String) throws -> (String, String) {
    guard body.hasPrefix("\"") else { throw Failure(message: "key is not quoted: \(body)") }
    var index = body.index(after: body.startIndex)
    var escaped = false
    while index < body.endIndex {
      let character = body[index]
      if escaped {
        escaped = false
      } else if character == "\\" {
        escaped = true
      } else if character == "\"" {
        let key = String(body[...index])
        let remainder = body[body.index(after: index)...]
        if remainder == ":" { return (key, "") }
        guard remainder.hasPrefix(": ") else { throw Failure(message: "malformed key line: \(body)") }
        return (key, String(remainder.dropFirst(2)))
      }
      index = body.index(after: index)
    }
    throw Failure(message: "unterminated key: \(body)")
  }

  private static func scalar(_ text: String) throws -> JSONValue {
    if text == "[]" { return .array([]) }
    if text == "{}" { return .object([:]) }
    return try JSONValueBridge.value(from: Data(text.utf8))
  }
}

/// A validator for exactly the JSON Schema 2020-12 vocabulary the bundle's
/// schemas use, so the tests can prove each schema accepts the real output
/// and rejects a counterexample without a schema library in the package.
enum JSONSchemaSubset {
  static func validate(_ value: JSONValue, against schema: JSONValue) -> Bool {
    validate(value, schema: schema, root: schema)
  }

  private static func resolve(_ ref: String, in root: JSONValue) -> JSONValue? {
    guard ref.hasPrefix("#/") else { return nil }
    var current = root
    for segment in ref.dropFirst(2).split(separator: "/") {
      guard case .object(let fields) = current, let next = fields[String(segment)] else { return nil }
      current = next
    }
    return current
  }

  private static func matchesType(_ value: JSONValue, _ type: String) -> Bool {
    switch (type, value) {
    case ("object", .object), ("array", .array), ("string", .string), ("boolean", .bool), ("null", .null):
      return true
    case ("integer", .integer), ("integer", .unsignedInteger):
      return true
    case ("number", .integer), ("number", .unsignedInteger), ("number", .number):
      return true
    default:
      return false
    }
  }

  private static func number(_ value: JSONValue) -> Double? {
    switch value {
    case .integer(let i): return Double(i)
    case .unsignedInteger(let u): return Double(u)
    case .number(let d): return d
    default: return nil
    }
  }

  private static func validate(_ value: JSONValue, schema: JSONValue, root: JSONValue) -> Bool {
    guard case .object(let s) = schema else { return true }
    if case .string(let ref)? = s["$ref"] {
      guard let target = resolve(ref, in: root), validate(value, schema: target, root: root) else { return false }
    }
    if let type = s["type"] {
      switch type {
      case .string(let name): if !matchesType(value, name) { return false }
      case .array(let names):
        if !names.contains(where: { if case .string(let name) = $0 { return matchesType(value, name) }; return false }) { return false }
      default: return false
      }
    }
    if let constant = s["const"], value != constant { return false }
    if case .array(let options)? = s["enum"], !options.contains(value) { return false }
    if case .object(let fields) = value {
      if case .array(let required)? = s["required"] {
        for case .string(let key) in required where fields[key] == nil { return false }
      }
      var properties: [String: JSONValue] = [:]
      if case .object(let declared)? = s["properties"] { properties = declared }
      for (key, sub) in properties {
        if let present = fields[key], !validate(present, schema: sub, root: root) { return false }
      }
      if s["additionalProperties"] == .bool(false) {
        for key in fields.keys where properties[key] == nil { return false }
      }
    }
    if case .array(let items) = value, let itemSchema = s["items"] {
      for item in items where !validate(item, schema: itemSchema, root: root) { return false }
    }
    if case .string(let text) = value {
      if case .integer(let minimum)? = s["minLength"], text.count < minimum { return false }
      if case .string(let pattern)? = s["pattern"] {
        guard let regex = try? NSRegularExpression(pattern: pattern),
          regex.firstMatch(in: text, range: NSRange(text.startIndex..., in: text)) != nil
        else { return false }
      }
    }
    if let numeric = number(value) {
      if let minimum = s["minimum"].flatMap(number), numeric < minimum { return false }
      if let maximum = s["maximum"].flatMap(number), numeric > maximum { return false }
    }
    if case .array(let options)? = s["oneOf"] {
      let matches = options.filter { validate(value, schema: $0, root: root) }.count
      if matches != 1 { return false }
    }
    if case .array(let options)? = s["anyOf"] {
      if !options.contains(where: { validate(value, schema: $0, root: root) }) { return false }
    }
    if case .array(let all)? = s["allOf"] {
      for sub in all where !validate(value, schema: sub, root: root) { return false }
    }
    if let negated = s["not"], validate(value, schema: negated, root: root) { return false }
    if let condition = s["if"] {
      if validate(value, schema: condition, root: root) {
        if let then = s["then"], !validate(value, schema: then, root: root) { return false }
      } else if let otherwise = s["else"], !validate(value, schema: otherwise, root: root) {
        return false
      }
    }
    return true
  }
}
