#!/usr/bin/env python3
"""Generate the bounded History ClientKit wire structures from published schemas.

Only structural JSON types are generated. Runtime semantic validation remains
in the facade. Unknown schema vocabulary fails closed rather than becoming Any.
"""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
METHODS = {
    "history.filter.list": "HistoryFilterList",
    "history.filter.save": "HistoryFilterSave",
    "history.filter.delete": "HistoryFilterDelete",
}
DESTINATION = "Packages/ArkDeckKit/Sources/ArkDeckClientKit/Generated/HistoryFilterWireGenerated.swift"
PRELUDE = '''import ArkDeckCore

// These internal wire types preserve missing fields separately from JSON null.
// They do not decide CAS, admission, retries, or presentation semantics.
enum HistoryWireError: Error { case invalidShape }
protocol HistoryWireValue: Equatable, Sendable {
  static func decode(_ value: JSONValue) throws -> Self
  var wire: JSONValue { get }
}
extension String: HistoryWireValue {
  static func decode(_ value: JSONValue) throws -> String {
    guard case .string(let text) = value else { throw HistoryWireError.invalidShape }
    return text
  }
  var wire: JSONValue { .string(self) }
}
struct HistoryWireNull: HistoryWireValue {
  static func decode(_ value: JSONValue) throws -> Self {
    guard value == .null else { throw HistoryWireError.invalidShape }
    return Self()
  }
  var wire: JSONValue { .null }
}
enum HistoryWireNullable<Value: HistoryWireValue>: HistoryWireValue {
  case null
  case value(Value)
  static func decode(_ value: JSONValue) throws -> Self {
    value == .null ? .null : .value(try Value.decode(value))
  }
  var wire: JSONValue {
    switch self { case .null: .null; case .value(let value): value.wire }
  }
}
extension Array: HistoryWireValue where Element: HistoryWireValue {
  static func decode(_ value: JSONValue) throws -> Self {
    guard case .array(let values) = value else { throw HistoryWireError.invalidShape }
    return try values.map(Element.decode)
  }
  var wire: JSONValue { .array(map(\\.wire)) }
}
'''


def render(documents):
    lines = ["// Generated by Scripts/generate-clientkit-models.py. Do not edit."]
    digest = hashlib.sha256(json.dumps(documents, sort_keys=True, separators=(",", ":")).encode()).hexdigest()
    lines += [f"// Published History schemas SHA-256: {digest}", PRELUDE]

    def emit(schema, name):
        nonlocal lines
        allowed = {"type", "properties", "required", "additionalProperties", "items"}
        if set(schema) - allowed:
            raise ValueError(f"{name}: unsupported schema keys {sorted(set(schema) - allowed)}")
        kind = schema.get("type")
        if isinstance(kind, list):
            if len(kind) != 2 or "null" not in kind:
                raise ValueError(f"{name}: unsupported union")
            inner = dict(schema, type=next(value for value in kind if value != "null"))
            return f"HistoryWireNullable<{emit(inner, name)}>"
        if kind == "string":
            return "String"
        if kind == "null":
            return "HistoryWireNull"
        if kind == "array":
            return f"[{emit(schema['items'], name + 'Item')}]"
        if kind != "object" or schema.get("additionalProperties") is not False:
            raise ValueError(f"{name}: only closed objects are supported")
        props = schema.get("properties", {})
        required = set(schema.get("required", []))
        if required - props.keys():
            raise ValueError(f"{name}: unknown required field")
        fields = []
        for key, child in sorted(props.items()):
            if not key.isidentifier() or key in {"self", "class", "struct", "extension", "let", "var"}:
                raise ValueError(f"{name}: unsupported field name {key}")
            fields.append((key, emit(child, name + key[0].upper() + key[1:]), key in required))
        lines.append(f"struct {name}: HistoryWireValue {{")
        for key, typ, mandatory in fields:
            lines.append(f"  let {key}: {typ}{'' if mandatory else '?'}")
        lines.append("  static func decode(_ value: JSONValue) throws -> Self {")
        lines.append("    guard case .object(let fields) = value,")
        keys = ", ".join(json.dumps(key) for key in sorted(props))
        reqs = ", ".join(json.dumps(key) for key in sorted(required))
        lines.append(f"      Set(fields.keys).isSubset(of: Set<String>([{keys}])),")
        lines.append(f"      Set<String>([{reqs}]).isSubset(of: Set(fields.keys))")
        lines.append("    else { throw HistoryWireError.invalidShape }")
        if fields:
            lines.append("    return try Self(")
            for index, (key, typ, mandatory) in enumerate(fields):
                expr = f'{typ}.decode(fields["{key}"] ?? .null)' if mandatory else f'fields["{key}"].map({typ}.decode)'
                lines.append(f"      {key}: {expr}{',' if index + 1 < len(fields) else ''}")
            lines.append("    )")
        else:
            lines.append("    return Self()")
        lines += ["  }", "  var wire: JSONValue {"]
        if not fields:
            lines.append("    .object([:])")
        else:
            lines.append("    var fields: [String: JSONValue] = [:]")
            for key, _, mandatory in fields:
                lines.append(f'    fields["{key}"] = {key}{"" if mandatory else "?"}.wire')
            lines.append("    return .object(fields)")
        lines += ["  }", "}", ""]
        return name

    for method, name in METHODS.items():
        document = documents[method]
        if document.get("x-arkdeck-method") != method:
            raise ValueError(f"method identity mismatch: {method}")
        for part in ("request", "result"):
            emit(document["$defs"][part], name + part.title())
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    documents = {method: json.loads((ROOT / f"spec/control/methods/{method}.json").read_text()) for method in METHODS}
    expected = render(documents)
    path = ROOT / DESTINATION
    if args.check:
        if not path.exists() or path.read_text() != expected:
            raise SystemExit("ClientKit History models drifted; run generate-clientkit-models.py")
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected)


if __name__ == "__main__":
    main()
