//! Swift `CLIMachineContracts`: the §14 machine-contract bundle, rendered
//! by the build that publishes it.
//!
//! The products listed here are the ones this CLI owns so far; each is held
//! byte for byte to the committed bundle
//! (`rust/tests/fixtures/contracts-bundle/owned.json`). The rest stay Swift's
//! until their slices move them.
use arkdeck_contract::{
    CATALOG_DIGEST, CONTRACT_IDENTITY, METHODS, PROTOCOL_VERSION, canonical_json,
};
use serde_json::{Map, Value, json};

/// Swift `CLIProductVersion.machineContract`.
pub const BUNDLE_VERSION: &str = "arkdeck.cli.contracts/1";
/// The page envelope every list and events result uses (§7.3).
pub const PAGE_SCHEMA_VERSION: &str = "arkdeck.cli.page/1";
/// The closed `nextAction` union shared by `job status` and `agent status`.
pub const NEXT_ACTION_SCHEMA_VERSION: &str = "arkdeck.cli.next-action/1";
pub const GENERATED_NOTICE: &str =
    "Generated by `arkdeck maintainer contracts export`; do not edit by hand.";

/// Swift `CLIResultEnvelope.schemaVersion`.
pub const RESULT_SCHEMA_VERSION: &str = "arkdeck.cli.result/1";
/// Swift `CLIEventEnvelope.schemaVersion`.
pub const EVENT_SCHEMA_VERSION: &str = "arkdeck.cli.event/1";
pub const CONTROL_PLANE_SCHEMA_VERSION: &str = "arkdeck.runtime-control-plane/1";
/// Where the per-method typed schemas the control-plane method table points
/// at live, relative to the repository.
pub const CONTROL_METHOD_SCHEMA_DIRECTORY: &str = "spec/control/methods";

const DRAFT: &str = "https://json-schema.org/draft/2020-12/schema";
const COMMAND_PATTERN: &str = "^[a-z][a-z0-9-]*(\\.[a-z][a-z0-9-]*)*$";
const CONTROL_REQUEST_ID_PATTERN: &str = "^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$";
const DURATION_PATTERN: &str = "^[1-9][0-9]*(ms|s|m|h)$";
const DECIMAL_POSITION_PATTERN: &str = "^[1-9][0-9]*$";

/// One generated file: a path relative to its root, and its exact bytes.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Product {
    pub relative_path: String,
    pub bytes: Vec<u8>,
}

impl Product {
    fn json(relative_path: &str, value: &Value) -> Self {
        Self {
            relative_path: relative_path.into(),
            bytes: json_document(value),
        }
    }
}

/// The products this CLI owns under `openspec/contracts/`.
pub fn contract_products() -> Vec<Product> {
    vec![
        Product {
            relative_path: "cli-command-registry.yaml".into(),
            bytes: yaml_document(&command_registry_document()),
        },
        Product {
            relative_path: "cli-error-registry.yaml".into(),
            bytes: yaml_document(&error_registry_document()),
        },
        Product::json(
            "cli-canonical-json-vectors.json",
            &canonical_vectors_document(),
        ),
        Product::json("cli-result.schema.json", &result_schema()),
        Product::json("cli-page.schema.json", &page_schema()),
        Product::json("cli-event.schema.json", &event_schema()),
        Product::json("cli-next-action.schema.json", &next_action_schema()),
        Product::json("runtime-control-plane.schema.json", &control_plane_schema()),
    ]
}

/// The fixtures this CLI owns next to the contract tests
/// (`Fixtures/CLI/`), sorted by path as Swift writes them.
pub fn fixture_products() -> Vec<Product> {
    let mut products: Vec<Product> = next_actions()
        .into_iter()
        .map(|(kind, document)| Product::json(&format!("next-action/{kind}.json"), &document))
        .collect();
    products.push(Product::json("next-action/null.json", &Value::Null));
    products.push(Product::json("page/snapshot.json", &snapshot_page()));
    products.push(Product::json(
        "page/event-stream.json",
        &event_stream_page(),
    ));
    products.extend(envelope_products());
    products.sort_by(|left, right| left.relative_path.cmp(&right.relative_path));
    products
}

// MARK: Rendering

/// Swift `ContractJSON.document`: pretty JSON with keys in
/// `arkdeck.cli.canonical-json/1` order (UTF-16 code units), two-space
/// indentation, scalars as the canonical encoder writes them, empty
/// containers inline, and one trailing LF.
pub fn json_document(value: &Value) -> Vec<u8> {
    let mut out = String::new();
    render(value, 0, &mut out);
    out.push('\n');
    out.into_bytes()
}

/// A scalar as the canonical encoder writes it; Swift writes `null` for one
/// the encoder refuses.
fn scalar(value: &Value) -> String {
    canonical_json(value)
        .ok()
        .and_then(|bytes| String::from_utf8(bytes).ok())
        .unwrap_or_else(|| "null".into())
}

/// Keys in UTF-16 code-unit order.
fn sorted_keys(fields: &Map<String, Value>) -> Vec<&String> {
    let mut keys: Vec<&String> = fields.keys().collect();
    keys.sort_by(|left, right| left.encode_utf16().cmp(right.encode_utf16()));
    keys
}

fn render(value: &Value, indent: usize, out: &mut String) {
    let pad = "  ".repeat(indent);
    match value {
        Value::Object(fields) if fields.is_empty() => out.push_str("{}"),
        Value::Object(fields) => {
            out.push_str("{\n");
            let keys = sorted_keys(fields);
            for (offset, key) in keys.iter().enumerate() {
                out.push_str(&pad);
                out.push_str("  ");
                out.push_str(&scalar(&Value::String((*key).clone())));
                out.push_str(": ");
                render(&fields[*key], indent + 1, out);
                out.push_str(if offset == keys.len() - 1 {
                    "\n"
                } else {
                    ",\n"
                });
            }
            out.push_str(&pad);
            out.push('}');
        }
        Value::Array(items) if items.is_empty() => out.push_str("[]"),
        Value::Array(items) => {
            out.push_str("[\n");
            for (offset, item) in items.iter().enumerate() {
                out.push_str(&pad);
                out.push_str("  ");
                render(item, indent + 1, out);
                out.push_str(if offset == items.len() - 1 {
                    "\n"
                } else {
                    ",\n"
                });
            }
            out.push_str(&pad);
            out.push(']');
        }
        other => out.push_str(&scalar(other)),
    }
}

/// Swift `ContractYAML.document`: the YAML subset the bundle uses, block
/// mappings and sequences whose every scalar, keys included, is a JSON scalar
/// from the canonical encoder, after the generated notice.
pub fn yaml_document(value: &Value) -> Vec<u8> {
    let mut out = format!("# {GENERATED_NOTICE}\n");
    out.push_str(&yaml_lines(value).join("\n"));
    out.push('\n');
    out.into_bytes()
}

/// A value written on its key's own line: a scalar or an empty container.
fn yaml_inline(value: &Value) -> bool {
    match value {
        Value::Object(fields) => fields.is_empty(),
        Value::Array(items) => items.is_empty(),
        _ => true,
    }
}

fn yaml_scalar(value: &Value) -> String {
    match value {
        Value::Object(_) => "{}".into(),
        Value::Array(_) => "[]".into(),
        other => scalar(other),
    }
}

fn yaml_lines(value: &Value) -> Vec<String> {
    match value {
        Value::Object(fields) if fields.is_empty() => vec!["{}".into()],
        Value::Object(fields) => {
            let mut out = Vec::new();
            for key in sorted_keys(fields) {
                let child = &fields[key];
                let rendered = scalar(&Value::String(key.clone()));
                if yaml_inline(child) {
                    out.push(format!("{rendered}: {}", yaml_scalar(child)));
                } else {
                    out.push(format!("{rendered}:"));
                    out.extend(
                        yaml_lines(child)
                            .into_iter()
                            .map(|line| format!("  {line}")),
                    );
                }
            }
            out
        }
        Value::Array(items) if items.is_empty() => vec!["[]".into()],
        Value::Array(items) => {
            let mut out = Vec::new();
            for item in items {
                if yaml_inline(item) {
                    out.push(format!("- {}", yaml_scalar(item)));
                } else {
                    let nested = yaml_lines(item);
                    out.push(format!("- {}", nested[0]));
                    out.extend(nested[1..].iter().map(|line| format!("  {line}")));
                }
            }
            out
        }
        other => vec![scalar(other)],
    }
}

// MARK: Registries

/// Swift `commandRegistryDocument`: the registry's projection, as this CLI
/// carries it (`command_registry.json`), with the bundle's versions and the
/// Catalog's digest.
fn command_registry_document() -> Value {
    let registry = crate::command_registry::projection();
    json!({
        "schemaVersion": registry["commandRegistrySchemaVersion"],
        "bundleVersion": BUNDLE_VERSION,
        "cliVersion": crate::CLI_VERSION,
        "catalogDigest": CATALOG_DIGEST,
        "commands": registry["commands"],
    })
}

/// Swift `errorRegistryDocument`: every exit category with its codes, and
/// every code with its category, exit status, retryability and attention.
fn error_registry_document() -> Value {
    use crate::error_registry::{
        CODES, ExitCategory, VERSION, control_request_retryable, requires_attention,
    };
    let categories: Vec<Value> = ExitCategory::ALL
        .iter()
        .map(|category| {
            json!({
                "category": category.machine_name(),
                "exitCode": category.exit_code(),
                "codes": CODES
                    .iter()
                    .filter(|(_, owner)| owner == category)
                    .map(|(code, _)| *code)
                    .collect::<Vec<_>>(),
            })
        })
        .collect();
    let codes: Vec<Value> = CODES
        .iter()
        .map(|(code, category)| {
            json!({
                "code": code,
                "category": category.machine_name(),
                "exitCode": category.exit_code(),
                "controlRequestRetryable": control_request_retryable(code),
                "attentionRequired": requires_attention(code),
            })
        })
        .collect();
    json!({
        "schemaVersion": VERSION,
        "bundleVersion": BUNDLE_VERSION,
        "cliVersion": crate::CLI_VERSION,
        "exitCategories": categories,
        "codes": codes,
    })
}

/// Swift `canonicalVectorsSchemaVersion` and `CLICanonicalJSON.version`.
const CANONICAL_VECTORS_SCHEMA_VERSION: &str = "arkdeck.cli.canonical-json-vectors/1";
const CANONICAL_JSON_VERSION: &str = "arkdeck.cli.canonical-json/1";

/// Swift `canonicalVectorInputs`: values a port must encode as this build
/// does.
fn canonical_vectors() -> Vec<(&'static str, Value)> {
    vec![
        ("emptyObject", json!({})),
        ("emptyArray", json!([])),
        ("scalars", json!([null, true, false, 0, ""])),
        (
            "keyOrderIsUtf16CodeUnit",
            json!({"b": 1, "a": 2, "aa": 3, "B": 0}),
        ),
        (
            "nonAsciiKeyOrder",
            json!({"z": 1, "\u{E9}": 2, "\u{1F600}": 3, "Z": 4}),
        ),
        (
            "stringEscapes",
            json!(
                "quote\" backslash\\ newline\n tab\t control\u{1} slash/ euro\u{20AC} emoji\u{1F600}"
            ),
        ),
        ("integers", json!([-1, 1, 9_007_199_254_740_991_i64])),
        ("unsignedInteger", json!(9_007_199_254_740_991_u64)),
        ("numbers", json!([0.5, 1.0, -0.0, 1e21, 123_456_789.125])),
        (
            "nested",
            json!({"list": [{}, [], {"k": [null]}], "text": "x"}),
        ),
    ]
}

/// Swift `canonicalRejectionInputs`, each with the refusal the published
/// bundle records (Swift's description of its encoder's error). This build
/// refuses the two integers too (`canonical_rejections_are_this_builds`); a
/// non-finite number cannot be held in a `serde_json::Value` at all, so this
/// build never accepts one either.
pub const CANONICAL_REJECTIONS: [(&str, &str); 5] = [
    ("positiveInfinity", "nonFiniteNumber"),
    ("negativeInfinity", "nonFiniteNumber"),
    ("nan", "nonFiniteNumber"),
    (
        "integerBeyondExactRange",
        "integerBeyondExactRange(\"9223372036854775807\")",
    ),
    (
        "unsignedIntegerBeyondExactRange",
        "integerBeyondExactRange(\"18446744073709551615\")",
    ),
];

/// Swift `canonicalVectorsDocument`: each vector with the canonical text this
/// build's encoder gives it, and the refusals.
fn canonical_vectors_document() -> Value {
    let vectors: Vec<Value> = canonical_vectors()
        .into_iter()
        .map(|(name, value)| {
            let canonical = String::from_utf8(
                canonical_json(&value).expect("every canonical vector is encodable"),
            )
            .expect("canonical JSON is UTF-8");
            json!({"name": name, "value": value, "canonical": canonical})
        })
        .collect();
    let rejections: Vec<Value> = CANONICAL_REJECTIONS
        .iter()
        .map(|(name, reason)| json!({"name": name, "reason": reason}))
        .collect();
    json!({
        "schemaVersion": CANONICAL_VECTORS_SCHEMA_VERSION,
        "canonicalJsonVersion": CANONICAL_JSON_VERSION,
        "bundleVersion": BUNDLE_VERSION,
        "cliVersion": crate::CLI_VERSION,
        "vectors": vectors,
        "rejections": rejections,
    })
}

// MARK: JSON Schemas

/// Swift `Schemas.header`.
fn header(title: &str, description: &str) -> Map<String, Value> {
    let mut fields = Map::new();
    fields.insert("$schema".into(), json!(DRAFT));
    fields.insert("$comment".into(), json!(GENERATED_NOTICE));
    fields.insert("title".into(), json!(title));
    fields.insert("description".into(), json!(description));
    fields.insert("x-arkdeck-bundleVersion".into(), json!(BUNDLE_VERSION));
    fields.insert("x-arkdeck-cliVersion".into(), json!(crate::CLI_VERSION));
    fields
}

/// Swift `Schemas.errorObject`: a failure's error, its code one of the
/// registry's.
fn error_object() -> Value {
    json!({
        "type": "object",
        "required": ["code", "message", "controlRequestRetryable", "attentionRequired"],
        "properties": {
            "code": {"enum": crate::error_registry::CODES
                .iter()
                .map(|(code, _)| *code)
                .collect::<Vec<_>>()},
            "message": {"type": "string"},
            "controlRequestRetryable": {"type": "boolean"},
            "attentionRequired": {"type": "boolean"},
            "details": {"type": "object"},
        },
        "additionalProperties": false,
    })
}

/// Swift `Schemas.lifecycleObject`.
fn lifecycle_object() -> Value {
    json!({
        "type": "object",
        "required": ["status", "replacementArgvPattern", "removalVersion"],
        "properties": {
            "status": {"enum": ["deprecated", "legacy"]},
            "replacementArgvPattern": {"type": ["string", "null"]},
            "removalVersion": {"type": ["string", "null"]},
        },
        "additionalProperties": false,
    })
}

/// A result or a terminal frame: `result` when `ok`, `error` otherwise,
/// never both.
fn result_or_error() -> Value {
    json!([
        {
            "properties": {"ok": {"const": true}},
            "required": ["result"],
            "not": {"required": ["error"]},
        },
        {
            "properties": {"ok": {"const": false}},
            "required": ["error"],
            "not": {"required": ["result"]},
        },
    ])
}

/// Swift `Schemas.result`.
fn result_schema() -> Value {
    let mut fields = header(
        RESULT_SCHEMA_VERSION,
        "The single result document a machine-mode invocation writes to stdout (§8.1, §8.2).",
    );
    fields.insert("type".into(), json!("object"));
    fields.insert(
        "required".into(),
        json!(["schemaVersion", "command", "ok", "meta"]),
    );
    fields.insert(
        "properties".into(),
        json!({
            "schemaVersion": {"const": RESULT_SCHEMA_VERSION},
            "command": {"type": "string", "pattern": COMMAND_PATTERN},
            "ok": {"type": "boolean"},
            "result": {},
            "error": {"$ref": "#/$defs/error"},
            "meta": {"$ref": "#/$defs/meta"},
        }),
    );
    fields.insert("additionalProperties".into(), json!(false));
    fields.insert("oneOf".into(), result_or_error());
    fields.insert(
        "$defs".into(),
        json!({
            "error": error_object(),
            "lifecycle": lifecycle_object(),
            "meta": {
                "type": "object",
                "required": ["controlRequestId", "cliVersion"],
                "properties": {
                    "controlRequestId": {"type": "string", "pattern": CONTROL_REQUEST_ID_PATTERN},
                    "cliVersion": {"type": "string"},
                    "controlProtocolVersion": {"const": PROTOCOL_VERSION},
                    "lifecycle": {"$ref": "#/$defs/lifecycle"},
                },
                "additionalProperties": false,
            },
            "errorRegistryVersion": {"const": crate::error_registry::VERSION},
        }),
    );
    Value::Object(fields)
}

/// Swift `Schemas.event`: a Runtime event line, or the one terminal frame.
fn event_schema() -> Value {
    let mut fields = header(
        EVENT_SCHEMA_VERSION,
        "One JSONL line of a streaming invocation: a Runtime event or the single terminal frame (§8.3).",
    );
    let mut common = Map::new();
    common.insert(
        "schemaVersion".into(),
        json!({"const": EVENT_SCHEMA_VERSION}),
    );
    common.insert("sequence".into(), json!({"type": "integer", "minimum": 1}));
    common.insert("type".into(), json!({"type": "string", "minLength": 1}));
    common.insert(
        "command".into(),
        json!({"type": "string", "pattern": COMMAND_PATTERN}),
    );
    common.insert(
        "controlRequestId".into(),
        json!({"type": "string", "pattern": CONTROL_REQUEST_ID_PATTERN}),
    );
    let mut terminal = common.clone();
    terminal.insert("type".into(), json!({"const": "terminal"}));
    terminal.insert("ok".into(), json!({"type": "boolean"}));
    terminal.insert(
        "exitCode".into(),
        json!({"type": "integer", "minimum": 0, "maximum": 255}),
    );
    terminal.insert("lastCursor".into(), json!({"type": ["string", "null"]}));
    terminal.insert("result".into(), json!({}));
    terminal.insert("error".into(), json!({"$ref": "#/$defs/error"}));
    let mut event = common;
    if let Value::Object(item) = &event_item()["properties"] {
        event.extend(item.clone());
    }
    fields.insert("type".into(), json!("object"));
    fields.insert(
        "required".into(),
        json!([
            "schemaVersion",
            "sequence",
            "type",
            "command",
            "controlRequestId"
        ]),
    );
    fields.insert(
        "oneOf".into(),
        json!([
            {"$ref": "#/$defs/terminalFrame"},
            {"$ref": "#/$defs/runtimeEventFrame"},
        ]),
    );
    fields.insert(
        "$defs".into(),
        json!({
            "error": error_object(),
            "terminalFrame": {
                "type": "object",
                "required": [
                    "schemaVersion", "sequence", "type", "command", "controlRequestId", "ok",
                    "exitCode", "lastCursor",
                ],
                "properties": terminal,
                "additionalProperties": false,
                "oneOf": result_or_error(),
            },
            "runtimeEventFrame": {
                "type": "object",
                "required": [
                    "schemaVersion", "sequence", "type", "command", "controlRequestId", "eventId",
                    "streamPosition", "cursor",
                ],
                "properties": event,
                "not": {"properties": {"type": {"const": "terminal"}}},
            },
        }),
    );
    Value::Object(fields)
}

/// Swift `Schemas.controlPlane`: the frames the CLI exchanges with the
/// Runtime, and the closed method set it may name, each pointing at its
/// typed schema. It is built from the compiled contract, so it follows the
/// contract inputs.
fn control_plane_schema() -> Value {
    let mut fields = header(
        CONTROL_PLANE_SCHEMA_VERSION,
        "The local control-plane request and response frames the CLI exchanges with the Runtime, and the closed method set it may name.",
    );
    let mut methods: Vec<&str> = METHODS.to_vec();
    methods.sort_unstable();
    let table: Vec<Value> = methods
        .iter()
        .map(|method| {
            json!({
                "method": method,
                "published": true,
                "schema": format!("{CONTROL_METHOD_SCHEMA_DIRECTORY}/{method}.json"),
            })
        })
        .collect();
    fields.insert(
        "oneOf".into(),
        json!([{"$ref": "#/$defs/request"}, {"$ref": "#/$defs/response"}]),
    );
    fields.insert(
        "x-arkdeck-currentProtocolVersion".into(),
        json!(PROTOCOL_VERSION),
    );
    fields.insert(
        "x-arkdeck-contractIdentity".into(),
        json!(CONTRACT_IDENTITY),
    );
    fields.insert(
        "x-arkdeck-methodSchemaDirectory".into(),
        json!(CONTROL_METHOD_SCHEMA_DIRECTORY),
    );
    fields.insert("x-arkdeck-methods".into(), json!(table));
    fields.insert(
        "$defs".into(),
        json!({
            "request": {
                "type": "object",
                "required": ["protocolVersion", "contractIdentity", "id", "method"],
                "properties": {
                    "protocolVersion": {"const": PROTOCOL_VERSION},
                    "contractIdentity": {"const": CONTRACT_IDENTITY},
                    "id": {"type": "string", "minLength": 1},
                    "method": {"enum": methods},
                    "params": {"type": "object"},
                },
                "additionalProperties": false,
            },
            "response": {
                "type": "object",
                "required": ["id", "ok"],
                "properties": {
                    "id": {"type": "string", "minLength": 1},
                    "ok": {"type": "boolean"},
                    "result": {},
                    "error": {"$ref": "#/$defs/wireError"},
                },
                "additionalProperties": false,
                "oneOf": result_or_error(),
            },
            "wireError": {
                "type": "object",
                "required": ["code", "message"],
                "properties": {
                    "code": {"type": "string", "minLength": 1},
                    "message": {"type": "string"},
                    "details": {"type": "object"},
                },
                "additionalProperties": false,
            },
        }),
    );
    Value::Object(fields)
}

/// Swift `Schemas.eventItem`.
fn event_item() -> Value {
    json!({
        "type": "object",
        "required": ["eventId", "streamPosition", "cursor", "type"],
        "properties": {
            "eventId": {"type": "string", "minLength": 1},
            "streamPosition": {"type": "string", "pattern": DECIMAL_POSITION_PATTERN},
            "runtimeRevision": {"type": "string"},
            "cursor": {"type": "string", "minLength": 1},
            "type": {"type": "string", "minLength": 1},
            "data": {},
        },
    })
}

/// Swift `Schemas.page`.
fn page_schema() -> Value {
    let mut fields = header(
        PAGE_SCHEMA_VERSION,
        "The fixed page shape every list and events result uses (§7.3).",
    );
    fields.insert("type".into(), json!("object"));
    fields.insert(
        "required".into(),
        json!([
            "schemaVersion",
            "pageKind",
            "items",
            "order",
            "snapshotRevision",
            "hasMore",
            "nextCursor",
        ]),
    );
    fields.insert(
        "properties".into(),
        json!({
            "schemaVersion": {"const": PAGE_SCHEMA_VERSION},
            "pageKind": {"enum": ["snapshot", "eventStream"]},
            "items": {"type": "array"},
            "order": {"type": "string", "minLength": 1},
            "snapshotRevision": {"type": "string"},
            "hasMore": {"type": "boolean"},
            "nextCursor": {"type": ["string", "null"]},
        }),
    );
    fields.insert("additionalProperties".into(), json!(false));
    fields.insert(
        "allOf".into(),
        json!([
            {
                "if": {"properties": {"pageKind": {"const": "eventStream"}}},
                "then": {"properties": {
                    "order": {"const": "streamPositionAsc"},
                    "nextCursor": {"type": "string", "minLength": 1},
                    "items": {"items": {"$ref": "#/$defs/eventItem"}},
                }},
            },
            {
                "if": {"properties": {
                    "pageKind": {"const": "snapshot"},
                    "hasMore": {"const": false},
                }},
                "then": {"properties": {"nextCursor": {"type": "null"}}},
            },
            {
                "if": {"properties": {"hasMore": {"const": true}}},
                "then": {"properties": {"nextCursor": {"type": "string", "minLength": 1}}},
            },
        ]),
    );
    fields.insert("$defs".into(), json!({"eventItem": event_item()}));
    Value::Object(fields)
}

/// Swift `Schemas.ownerObject(kinds:)`.
fn owner_object(kinds: &[&str]) -> Value {
    json!({
        "type": "object",
        "required": ["kind", "id"],
        "properties": {
            "kind": {"enum": kinds},
            "id": {"type": "string", "minLength": 1},
        },
        "additionalProperties": false,
    })
}

/// Swift `Schemas.branch`: one closed branch of the §7.3 union.
fn branch(
    kind: &str,
    owner_kinds: &[&str],
    resource_kinds: &[&str],
    reason_codes: Option<&[&str]>,
    extra: Value,
    required: &[&str],
    resource_mirrors_owner: bool,
) -> Value {
    let mut properties = Map::new();
    properties.insert("kind".into(), json!({"const": kind}));
    properties.insert("owner".into(), owner_object(owner_kinds));
    properties.insert("resource".into(), owner_object(resource_kinds));
    properties.insert(
        "reasonCode".into(),
        match reason_codes {
            Some(codes) => json!({"enum": codes}),
            None => json!({"type": "string", "minLength": 1}),
        },
    );
    if let Value::Object(extra) = extra {
        properties.extend(extra);
    }
    let mut all_required = vec!["kind", "owner", "resource", "reasonCode"];
    all_required.extend_from_slice(required);
    let mut fields = Map::new();
    fields.insert("type".into(), json!("object"));
    fields.insert("required".into(), json!(all_required));
    fields.insert("properties".into(), Value::Object(properties));
    fields.insert("additionalProperties".into(), json!(false));
    if resource_mirrors_owner {
        fields.insert(
            "allOf".into(),
            owner_kinds
                .iter()
                .map(|owner| {
                    json!({
                        "if": {"properties": {"owner": {"properties": {"kind": {"const": owner}}}}},
                        "then": {"properties": {"resource": {"properties": {"kind": {"const": owner}}}}},
                    })
                })
                .collect(),
        );
    }
    Value::Object(fields)
}

/// Swift `Schemas.nextAction`.
fn next_action_schema() -> Value {
    let mut fields = header(
        NEXT_ACTION_SCHEMA_VERSION,
        "The closed nextAction union shared by job status and agent status; null when nothing is pending (§7.3).",
    );
    let execution_owners = ["job", "agentExecution", "controlAction"];
    fields.insert(
        "oneOf".into(),
        json!([
            {"type": "null"},
            {"$ref": "#/$defs/wait"},
            {"$ref": "#/$defs/humanAction"},
            {"$ref": "#/$defs/reconcile"},
            {"$ref": "#/$defs/cleanup"},
            {"$ref": "#/$defs/readResult"},
        ]),
    );
    fields.insert(
        "$defs".into(),
        json!({
            "wait": branch(
                "wait",
                &execution_owners,
                &execution_owners,
                Some(&["job.running", "agent.orchestrationPending", "lifecycle.pending"]),
                json!({"retryAfter": {"type": "string", "pattern": DURATION_PATTERN}}),
                &["retryAfter"],
                true,
            ),
            "humanAction": branch(
                "humanAction",
                &execution_owners,
                &["humanAction"],
                None,
                json!({
                    "resumeReference": {"type": "string", "minLength": 1},
                    "expiresAt": {"type": ["string", "null"], "format": "date-time"},
                }),
                &["resumeReference", "expiresAt"],
                false,
            ),
            "reconcile": branch(
                "reconcile",
                &["job", "controlAction"],
                &["job", "controlAction"],
                Some(&[
                    "recovery.outcomeUnknown",
                    "lifecycle.outcomeUnknown",
                    "job.finalizationPending",
                ]),
                json!({}),
                &[],
                true,
            ),
            "cleanup": branch(
                "cleanup",
                &["job"],
                &["cleanupDebt"],
                Some(&["recovery.cleanupDebt"]),
                json!({}),
                &[],
                false,
            ),
            "readResult": branch(
                "readResult",
                &["job"],
                &["job"],
                Some(&["job.resultAvailable"]),
                json!({}),
                &[],
                false,
            ),
        }),
    );
    Value::Object(fields)
}

// MARK: Sample documents (Swift `SampleDocuments`): one conformance sample
// per `nextAction` kind and per page kind.

const JOB_ID: &str = "job-0f3c2a7e-4d1b-4c0a-9e2d-5b6a7c8d9e0f";
const EVENT_CURSOR: &str = "evc-1.job-0f3c2a7e.12";

fn next_actions() -> Vec<(&'static str, Value)> {
    let job = json!({"kind": "job", "id": JOB_ID});
    vec![
        (
            "wait",
            json!({
                "kind": "wait",
                "owner": job,
                "resource": job,
                "reasonCode": "job.running",
                "retryAfter": "250ms",
            }),
        ),
        (
            "humanAction",
            json!({
                "kind": "humanAction",
                "owner": {
                    "kind": "agentExecution",
                    "id": "exec-7a1d3f52-2c9e-4b8a-a1d0-3e4f5a6b7c8d",
                },
                "resource": {
                    "kind": "humanAction",
                    "id": "har-2b3c4d5e-6f70-4a8b-9c0d-1e2f3a4b5c6d",
                },
                "reasonCode": "device.trustPending",
                "resumeReference": "resume-9d8c7b6a-5f4e-4d3c-b2a1-0f9e8d7c6b5a",
                "expiresAt": "2026-08-30T12:00:00Z",
            }),
        ),
        (
            "reconcile",
            json!({
                "kind": "reconcile",
                "owner": job,
                "resource": job,
                "reasonCode": "recovery.outcomeUnknown",
            }),
        ),
        (
            "cleanup",
            json!({
                "kind": "cleanup",
                "owner": job,
                "resource": {
                    "kind": "cleanupDebt",
                    "id": "debt-3c4d5e6f-7a8b-4c9d-8e0f-1a2b3c4d5e6f",
                },
                "reasonCode": "recovery.cleanupDebt",
            }),
        ),
        (
            "readResult",
            json!({
                "kind": "readResult",
                "owner": job,
                "resource": job,
                "reasonCode": "job.resultAvailable",
            }),
        ),
    ]
}

/// Swift `fixtureControlRequestID`: fixed, so the committed envelopes are a
/// function of the build alone.
const FIXTURE_CONTROL_REQUEST_ID: &str = "ctl-fixture-0001";

fn wait_action() -> Value {
    next_actions()
        .into_iter()
        .find(|(kind, _)| *kind == "wait")
        .map(|(_, action)| action)
        .expect("the wait sample")
}

/// Swift `SampleDocuments.jobStatus`.
fn job_status() -> Value {
    json!({
        "jobId": JOB_ID,
        "state": "running",
        "operation": "observe.device@1",
        "runtimeRevision": "12",
        "nextAction": wait_action(),
    })
}

/// Swift `SampleDocuments.eventRow`.
fn event_row() -> Value {
    json!({
        "eventId": "evt-6c5b4a39-2817-4f0e-9d8c-7b6a5f4e3d2c",
        "streamPosition": "12",
        "runtimeRevision": "12",
        "cursor": EVENT_CURSOR,
        "type": "job.stepCompleted",
        "data": {"stepId": "observe-device", "outcome": "verified"},
    })
}

/// Swift `SampleDocuments.emptySnapshotPage`.
fn empty_snapshot_page() -> Value {
    json!({
        "schemaVersion": PAGE_SCHEMA_VERSION,
        "pageKind": "snapshot",
        "items": [],
        "order": "createdAtDescJobIdAsc",
        "snapshotRevision": "rev-000000000012",
        "hasMore": false,
        "nextCursor": null,
    })
}

/// Swift `EnvelopeFixtures.products`: one of each machine answer, each
/// written by the code this CLI answers with. The two refusals are its
/// parser's own, for `job status` without `--job` and for the retired
/// `agent chat`.
fn envelope_products() -> Vec<Product> {
    let id = FIXTURE_CONTROL_REQUEST_ID;
    let argv = |words: &[&str]| {
        words
            .iter()
            .map(|word| word.to_string())
            .collect::<Vec<_>>()
    };
    let Err(missing) = crate::parse(&argv(&["job", "status"])) else {
        panic!("`job status` without --job fails at parse time");
    };
    let Err(removed) = crate::parse(&argv(&["agent", "chat"])) else {
        panic!("`agent chat` is a tombstone");
    };
    let mut unavailable =
        crate::CliError::new("runtimeUnavailable", "the local Runtime did not answer");
    unavailable
        .details
        .insert("endpoint".into(), json!("local"));
    unavailable
        .details
        .insert("newDispatchCount".into(), json!(0));
    let status = job_status();
    let answers = [
        (
            "envelopes/result-success.json",
            crate::local_success_envelope("job.status", status.clone(), id),
        ),
        (
            "envelopes/result-deprecated-alias.json",
            crate::with_lifecycle(
                crate::local_success_envelope("cleanup-debt.list", empty_snapshot_page(), id),
                "cleanup-debt.list",
            ),
        ),
        (
            "envelopes/result-argv-failure.json",
            crate::failure_envelope(
                missing.command.unwrap_or("registry.parse"),
                &missing,
                id,
                false,
            ),
        ),
        (
            "envelopes/result-removed-command.json",
            crate::with_lifecycle(
                crate::failure_envelope(
                    removed.command.unwrap_or("registry.parse"),
                    &removed,
                    id,
                    false,
                ),
                removed.command.unwrap_or("registry.parse"),
            ),
        ),
        (
            "envelopes/event-runtime-event.jsonl",
            crate::event_line("job.watch", 1, &event_row(), id),
        ),
        (
            "envelopes/event-terminal-success.jsonl",
            crate::terminal_line("job.wait", 2, id, Some(EVENT_CURSOR), Ok((&status, 0))),
        ),
        (
            "envelopes/event-terminal-failure.jsonl",
            crate::terminal_line("job.wait", 1, id, None, Err(&unavailable)),
        ),
    ];
    answers
        .into_iter()
        .map(|(path, answer)| Product {
            relative_path: path.into(),
            bytes: crate::render(&answer).expect("every envelope is canonical JSON"),
        })
        .collect()
}

fn snapshot_page() -> Value {
    json!({
        "schemaVersion": PAGE_SCHEMA_VERSION,
        "pageKind": "snapshot",
        "items": [{"jobId": JOB_ID, "state": "running", "createdAt": "2026-09-02T04:00:00Z"}],
        "order": "createdAtDescJobIdAsc",
        "snapshotRevision": "rev-000000000012",
        "hasMore": false,
        "nextCursor": null,
    })
}

fn event_stream_page() -> Value {
    json!({
        "schemaVersion": PAGE_SCHEMA_VERSION,
        "pageKind": "eventStream",
        "items": [event_row()],
        "order": "streamPositionAsc",
        "snapshotRevision": "12",
        "hasMore": false,
        "nextCursor": EVENT_CURSOR,
    })
}
