//! Swift `CLIMachineContracts`: the §14 machine-contract bundle, rendered
//! by the build that publishes it.
//!
//! Every product of the bundle is rendered here, and each is held byte for
//! byte to the committed bundle: by its digest
//! (`rust/tests/fixtures/contracts-bundle/owned.json`), or, where it carries a
//! contract input, by the committed file itself.
use crate::registry_parse::Accepted;
use crate::{CliError, command_registry, error_registry, registry_parse};
use arkdeck_contract::{
    CATALOG_DIGEST, CONTRACT_IDENTITY, METHODS, PROTOCOL_VERSION, canonical_json,
};
use serde_json::{Map, Value, json};
use std::collections::BTreeSet;
use std::fs;
use std::io;
use std::path::Path;

/// Swift `CLIProductVersion.machineContract`.
pub const BUNDLE_VERSION: &str = "arkdeck.cli.contracts/1";
/// The page envelope every list and events result uses (§7.3).
pub const PAGE_SCHEMA_VERSION: &str = "arkdeck.cli.page/1";
/// The closed `nextAction` union shared by `job status` and `agent status`.
pub const NEXT_ACTION_SCHEMA_VERSION: &str = "arkdeck.cli.next-action/1";
pub const GENERATED_NOTICE: &str =
    "Generated by `arkdeck maintainer contracts export`; do not edit by hand.";

/// Swift `CLIResultEnvelope.schemaVersion`.
pub const RESULT_SCHEMA_VERSION: &str = "arkdeck.cli.result/1";
/// Swift `CLIEventEnvelope.schemaVersion`.
pub const EVENT_SCHEMA_VERSION: &str = "arkdeck.cli.event/1";
pub const CONTROL_PLANE_SCHEMA_VERSION: &str = "arkdeck.runtime-control-plane/1";
/// Where the per-method typed schemas the control-plane method table points
/// at live, relative to the repository.
pub const CONTROL_METHOD_SCHEMA_DIRECTORY: &str = "spec/control/methods";

const DRAFT: &str = "https://json-schema.org/draft/2020-12/schema";
const COMMAND_PATTERN: &str = "^[a-z][a-z0-9-]*(\\.[a-z][a-z0-9-]*)*$";
const CONTROL_REQUEST_ID_PATTERN: &str = "^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$";
const DURATION_PATTERN: &str = "^[1-9][0-9]*(ms|s|m|h)$";
const DECIMAL_POSITION_PATTERN: &str = "^[1-9][0-9]*$";

/// One generated file: a path relative to its root, and its exact bytes.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Product {
    pub relative_path: String,
    pub bytes: Vec<u8>,
}

impl Product {
    fn json(relative_path: &str, value: &Value) -> Self {
        Self {
            relative_path: relative_path.into(),
            bytes: json_document(value),
        }
    }
}

/// The products this CLI owns under `openspec/contracts/`.
pub fn contract_products() -> Vec<Product> {
    vec![
        Product {
            relative_path: "cli-command-registry.yaml".into(),
            bytes: yaml_document(&command_registry_document()),
        },
        Product {
            relative_path: "cli-error-registry.yaml".into(),
            bytes: yaml_document(&error_registry_document()),
        },
        Product::json(
            "cli-canonical-json-vectors.json",
            &canonical_vectors_document(),
        ),
        Product::json(
            "cli-feature-coverage.json",
            &crate::feature_coverage::document(),
        ),
        Product {
            relative_path: "app-product-capability-registry.yaml".into(),
            bytes: yaml_document(&crate::feature_coverage::app_registry_document()),
        },
        Product::json("cli-result.schema.json", &result_schema()),
        Product::json("cli-page.schema.json", &page_schema()),
        Product::json("cli-event.schema.json", &event_schema()),
        Product::json("cli-next-action.schema.json", &next_action_schema()),
        Product::json("runtime-control-plane.schema.json", &control_plane_schema()),
    ]
}

/// The fixtures this CLI owns next to the contract tests
/// (`Fixtures/CLI/`), sorted by path as Swift writes them: every one of them,
/// the index last written.
pub fn fixture_products() -> Vec<Product> {
    let mut products = argv_fixtures();
    products.extend(envelope_products());
    products.extend(
        next_actions()
            .into_iter()
            .map(|(kind, document)| Product::json(&format!("next-action/{kind}.json"), &document)),
    );
    products.push(Product::json("next-action/null.json", &Value::Null));
    products.push(Product::json("page/snapshot.json", &snapshot_page()));
    products.push(Product::json(
        "page/event-stream.json",
        &event_stream_page(),
    ));
    let mut files: Vec<&str> = products
        .iter()
        .map(|product| product.relative_path.as_str())
        .collect();
    files.sort_unstable();
    let index = json!({
        "schemaVersion": FIXTURE_INDEX_SCHEMA_VERSION,
        "bundleVersion": BUNDLE_VERSION,
        "cliVersion": crate::CLI_VERSION,
        "argvFixtureSchemaVersion": ARGV_FIXTURE_SCHEMA_VERSION,
        "envelopeFixtureSchemaVersion": ENVELOPE_FIXTURE_SCHEMA_VERSION,
        "controlRequestId": FIXTURE_CONTROL_REQUEST_ID,
        "files": files,
    });
    products.push(Product::json("index.json", &index));
    products.sort_by(|left, right| left.relative_path.cmp(&right.relative_path));
    products
}

/// What keeps the feature coverage from covering the compiled control
/// methods exactly: a method without a coverage ruling, or a ruling for no
/// method. A contract view compiles the methods at another revision than the
/// rulings, so the coverage takes the methods it has a ruling for; the
/// checkout's test requires this empty.
pub fn coverage_problems() -> Vec<String> {
    crate::feature_coverage::problems()
}

/// One leaf's argv fixture (`argv/<command>.json`) as this CLI renders it,
/// which the digest table holds to the published one; `None` for a command
/// the registry does not name.
pub fn argv_fixture(command: &str) -> Option<Value> {
    let leaf = array(&command_registry::projection()["commands"])
        .iter()
        .find(|leaf| leaf["command"] == command)?;
    Some(
        serde_json::from_slice(&json_document(&argv_document(leaf)))
            .expect("a rendered fixture is JSON"),
    )
}

// MARK: Export and drift

/// Swift `CLIMachineContracts.ExportReport`: what an export wrote and
/// removed, as `contracts/…` and `fixtures/…` paths.
#[derive(Debug, Default, PartialEq, Eq)]
pub struct ExportReport {
    pub written: Vec<String>,
    pub removed: Vec<String>,
}

/// Swift `CLIMachineContracts.CheckReport`: the products a checked bundle
/// holds otherwise than this build renders them, lacks, or holds besides.
#[derive(Debug, Default, PartialEq, Eq)]
pub struct CheckReport {
    pub drifted: Vec<String>,
    pub missing: Vec<String>,
    pub unexpected: Vec<String>,
    pub checked: u64,
}

impl CheckReport {
    pub fn is_clean(&self) -> bool {
        self.drifted.is_empty() && self.missing.is_empty() && self.unexpected.is_empty()
    }

    /// Swift `CheckReport.document`.
    pub fn document(&self) -> Value {
        json!({
            "clean": self.is_clean(),
            "checked": self.checked,
            "drifted": self.drifted,
            "missing": self.missing,
            "unexpected": self.unexpected,
        })
    }
}

/// Swift `CLIMachineContracts.export(contractsDirectory:fixturesDirectory:)`:
/// every contract product under `contracts`; under `fixtures`, each regular,
/// visible file no fixture product names removed, then every fixture
/// product.
pub fn export(contracts: &Path, fixtures: &Path) -> io::Result<ExportReport> {
    let contract = contract_products();
    let fixture = fixture_products();
    let mut report = ExportReport::default();
    for product in &contract {
        write(product, contracts)?;
        report
            .written
            .push(format!("contracts/{}", product.relative_path));
    }
    let expected: BTreeSet<&str> = fixture
        .iter()
        .map(|product| product.relative_path.as_str())
        .collect();
    for stale in regular_files(fixtures)? {
        if !expected.contains(stale.as_str()) {
            fs::remove_file(fixtures.join(&stale))?;
            report.removed.push(format!("fixtures/{stale}"));
        }
    }
    for product in &fixture {
        write(product, fixtures)?;
        report
            .written
            .push(format!("fixtures/{}", product.relative_path));
    }
    Ok(report)
}

/// Swift `CLIMachineContracts.check(contractsDirectory:fixturesDirectory:)`:
/// each product against its file, and the fixture directory's regular,
/// visible files no fixture product names.
pub fn check(contracts: &Path, fixtures: &Path) -> io::Result<CheckReport> {
    let mut report = CheckReport::default();
    for product in contract_products() {
        compare(&product, contracts, "contracts", &mut report);
    }
    let fixture = fixture_products();
    for product in &fixture {
        compare(product, fixtures, "fixtures", &mut report);
    }
    let expected: BTreeSet<&str> = fixture
        .iter()
        .map(|product| product.relative_path.as_str())
        .collect();
    for extra in regular_files(fixtures)? {
        if !expected.contains(extra.as_str()) {
            report.unexpected.push(format!("fixtures/{extra}"));
        }
    }
    report.unexpected.sort();
    Ok(report)
}

/// Swift `compare(_:under:label:into:)`: a file that cannot be read is
/// missing.
fn compare(product: &Product, root: &Path, label: &str, report: &mut CheckReport) {
    report.checked += 1;
    match fs::read(root.join(&product.relative_path)) {
        Err(_) => report
            .missing
            .push(format!("{label}/{}", product.relative_path)),
        Ok(existing) if existing != product.bytes => report
            .drifted
            .push(format!("{label}/{}", product.relative_path)),
        Ok(_) => {}
    }
}

/// Swift `write(_:under:)`: the product's directories, then its bytes
/// written atomically, through a hidden sibling renamed into place.
fn write(product: &Product, root: &Path) -> io::Result<()> {
    let path = root.join(&product.relative_path);
    let parent = path.parent().unwrap_or(root);
    fs::create_dir_all(parent)?;
    let name = path
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("product");
    let staged = parent.join(format!(".{name}.{}.export", std::process::id()));
    fs::write(&staged, &product.bytes)?;
    fs::rename(&staged, &path).inspect_err(|_| {
        let _ = fs::remove_file(&staged);
    })
}

/// Swift `regularFiles(under:)`: every regular, visible file below `root`
/// (a hidden directory is not entered, and a symbolic link is neither
/// followed nor listed), by its path relative to `root`, in order; none when
/// `root` is not a directory.
fn regular_files(root: &Path) -> io::Result<Vec<String>> {
    fn walk(directory: &Path, prefix: &str, found: &mut Vec<String>) -> io::Result<()> {
        for entry in fs::read_dir(directory)? {
            let entry = entry?;
            let Ok(name) = entry.file_name().into_string() else {
                continue;
            };
            let kind = entry.file_type()?;
            if hidden(&entry.path(), &name, kind.is_dir())? {
                continue;
            }
            let relative = if prefix.is_empty() {
                name
            } else {
                format!("{prefix}/{name}")
            };
            if kind.is_dir() {
                walk(&entry.path(), &relative, found)?;
            } else if kind.is_file() {
                found.push(relative);
            }
        }
        Ok(())
    }
    let mut found = Vec::new();
    if root.is_dir() {
        walk(root, "", &mut found)?;
    }
    found.sort();
    Ok(found)
}

/// Foundation's hidden key, which `.skipsHiddenFiles` reads: a leading dot,
/// or on macOS the hidden flag too.
fn hidden(path: &Path, name: &str, directory: bool) -> io::Result<bool> {
    #[cfg(target_os = "macos")]
    {
        let _ = name;
        arkdeck_platform::host_entry_presentation(path, directory).map(|entry| entry.hidden)
    }
    #[cfg(not(target_os = "macos"))]
    {
        let _ = (path, directory);
        Ok(name.starts_with('.'))
    }
}

// MARK: Rendering

/// Swift `ContractJSON.document`: pretty JSON with keys in
/// `arkdeck.cli.canonical-json/1` order (UTF-16 code units), two-space
/// indentation, scalars as the canonical encoder writes them, empty
/// containers inline, and one trailing LF.
pub fn json_document(value: &Value) -> Vec<u8> {
    let mut out = String::new();
    render(value, 0, &mut out);
    out.push('\n');
    out.into_bytes()
}

/// A scalar as the canonical encoder writes it; Swift writes `null` for one
/// the encoder refuses.
fn scalar(value: &Value) -> String {
    canonical_json(value)
        .ok()
        .and_then(|bytes| String::from_utf8(bytes).ok())
        .unwrap_or_else(|| "null".into())
}

/// Keys in UTF-16 code-unit order.
fn sorted_keys(fields: &Map<String, Value>) -> Vec<&String> {
    let mut keys: Vec<&String> = fields.keys().collect();
    keys.sort_by(|left, right| left.encode_utf16().cmp(right.encode_utf16()));
    keys
}

fn render(value: &Value, indent: usize, out: &mut String) {
    let pad = "  ".repeat(indent);
    match value {
        Value::Object(fields) if fields.is_empty() => out.push_str("{}"),
        Value::Object(fields) => {
            out.push_str("{\n");
            let keys = sorted_keys(fields);
            for (offset, key) in keys.iter().enumerate() {
                out.push_str(&pad);
                out.push_str("  ");
                out.push_str(&scalar(&Value::String((*key).clone())));
                out.push_str(": ");
                render(&fields[*key], indent + 1, out);
                out.push_str(if offset == keys.len() - 1 {
                    "\n"
                } else {
                    ",\n"
                });
            }
            out.push_str(&pad);
            out.push('}');
        }
        Value::Array(items) if items.is_empty() => out.push_str("[]"),
        Value::Array(items) => {
            out.push_str("[\n");
            for (offset, item) in items.iter().enumerate() {
                out.push_str(&pad);
                out.push_str("  ");
                render(item, indent + 1, out);
                out.push_str(if offset == items.len() - 1 {
                    "\n"
                } else {
                    ",\n"
                });
            }
            out.push_str(&pad);
            out.push(']');
        }
        other => out.push_str(&scalar(other)),
    }
}

/// Swift `ContractYAML.document`: the YAML subset the bundle uses, block
/// mappings and sequences whose every scalar, keys included, is a JSON scalar
/// from the canonical encoder, after the generated notice.
pub fn yaml_document(value: &Value) -> Vec<u8> {
    let mut out = format!("# {GENERATED_NOTICE}\n");
    out.push_str(&yaml_lines(value).join("\n"));
    out.push('\n');
    out.into_bytes()
}

/// A value written on its key's own line: a scalar or an empty container.
fn yaml_inline(value: &Value) -> bool {
    match value {
        Value::Object(fields) => fields.is_empty(),
        Value::Array(items) => items.is_empty(),
        _ => true,
    }
}

fn yaml_scalar(value: &Value) -> String {
    match value {
        Value::Object(_) => "{}".into(),
        Value::Array(_) => "[]".into(),
        other => scalar(other),
    }
}

fn yaml_lines(value: &Value) -> Vec<String> {
    match value {
        Value::Object(fields) if fields.is_empty() => vec!["{}".into()],
        Value::Object(fields) => {
            let mut out = Vec::new();
            for key in sorted_keys(fields) {
                let child = &fields[key];
                let rendered = scalar(&Value::String(key.clone()));
                if yaml_inline(child) {
                    out.push(format!("{rendered}: {}", yaml_scalar(child)));
                } else {
                    out.push(format!("{rendered}:"));
                    out.extend(
                        yaml_lines(child)
                            .into_iter()
                            .map(|line| format!("  {line}")),
                    );
                }
            }
            out
        }
        Value::Array(items) if items.is_empty() => vec!["[]".into()],
        Value::Array(items) => {
            let mut out = Vec::new();
            for item in items {
                if yaml_inline(item) {
                    out.push(format!("- {}", yaml_scalar(item)));
                } else {
                    let nested = yaml_lines(item);
                    out.push(format!("- {}", nested[0]));
                    out.extend(nested[1..].iter().map(|line| format!("  {line}")));
                }
            }
            out
        }
        other => vec![scalar(other)],
    }
}

// MARK: Registries

/// Swift `commandRegistryDocument`: the registry's projection, as this CLI
/// carries it (`command_registry.json`), with the bundle's versions and the
/// Catalog's digest.
fn command_registry_document() -> Value {
    let registry = crate::command_registry::projection();
    json!({
        "schemaVersion": registry["commandRegistrySchemaVersion"],
        "bundleVersion": BUNDLE_VERSION,
        "cliVersion": crate::CLI_VERSION,
        "catalogDigest": CATALOG_DIGEST,
        "commands": registry["commands"],
    })
}

/// Swift `errorRegistryDocument`: every exit category with its codes, and
/// every code with its category, exit status, retryability and attention.
fn error_registry_document() -> Value {
    use crate::error_registry::{
        CODES, ExitCategory, VERSION, control_request_retryable, requires_attention,
    };
    let categories: Vec<Value> = ExitCategory::ALL
        .iter()
        .map(|category| {
            json!({
                "category": category.machine_name(),
                "exitCode": category.exit_code(),
                "codes": CODES
                    .iter()
                    .filter(|(_, owner)| owner == category)
                    .map(|(code, _)| *code)
                    .collect::<Vec<_>>(),
            })
        })
        .collect();
    let codes: Vec<Value> = CODES
        .iter()
        .map(|(code, category)| {
            json!({
                "code": code,
                "category": category.machine_name(),
                "exitCode": category.exit_code(),
                "controlRequestRetryable": control_request_retryable(code),
                "attentionRequired": requires_attention(code),
            })
        })
        .collect();
    json!({
        "schemaVersion": VERSION,
        "bundleVersion": BUNDLE_VERSION,
        "cliVersion": crate::CLI_VERSION,
        "exitCategories": categories,
        "codes": codes,
    })
}

/// Swift `canonicalVectorsSchemaVersion` and `CLICanonicalJSON.version`.
const CANONICAL_VECTORS_SCHEMA_VERSION: &str = "arkdeck.cli.canonical-json-vectors/1";
const CANONICAL_JSON_VERSION: &str = "arkdeck.cli.canonical-json/1";

/// Swift `canonicalVectorInputs`: values a port must encode as this build
/// does.
fn canonical_vectors() -> Vec<(&'static str, Value)> {
    vec![
        ("emptyObject", json!({})),
        ("emptyArray", json!([])),
        ("scalars", json!([null, true, false, 0, ""])),
        (
            "keyOrderIsUtf16CodeUnit",
            json!({"b": 1, "a": 2, "aa": 3, "B": 0}),
        ),
        (
            "nonAsciiKeyOrder",
            json!({"z": 1, "\u{E9}": 2, "\u{1F600}": 3, "Z": 4}),
        ),
        (
            "stringEscapes",
            json!(
                "quote\" backslash\\ newline\n tab\t control\u{1} slash/ euro\u{20AC} emoji\u{1F600}"
            ),
        ),
        ("integers", json!([-1, 1, 9_007_199_254_740_991_i64])),
        ("unsignedInteger", json!(9_007_199_254_740_991_u64)),
        ("numbers", json!([0.5, 1.0, -0.0, 1e21, 123_456_789.125])),
        (
            "nested",
            json!({"list": [{}, [], {"k": [null]}], "text": "x"}),
        ),
    ]
}

/// Swift `canonicalRejectionInputs`, each with the refusal the published
/// bundle records (Swift's description of its encoder's error). This build
/// refuses the two integers too (`canonical_rejections_are_this_builds`); a
/// non-finite number cannot be held in a `serde_json::Value` at all, so this
/// build never accepts one either.
pub const CANONICAL_REJECTIONS: [(&str, &str); 5] = [
    ("positiveInfinity", "nonFiniteNumber"),
    ("negativeInfinity", "nonFiniteNumber"),
    ("nan", "nonFiniteNumber"),
    (
        "integerBeyondExactRange",
        "integerBeyondExactRange(\"9223372036854775807\")",
    ),
    (
        "unsignedIntegerBeyondExactRange",
        "integerBeyondExactRange(\"18446744073709551615\")",
    ),
];

/// Swift `canonicalVectorsDocument`: each vector with the canonical text this
/// build's encoder gives it, and the refusals.
fn canonical_vectors_document() -> Value {
    let vectors: Vec<Value> = canonical_vectors()
        .into_iter()
        .map(|(name, value)| {
            let canonical = String::from_utf8(
                canonical_json(&value).expect("every canonical vector is encodable"),
            )
            .expect("canonical JSON is UTF-8");
            json!({"name": name, "value": value, "canonical": canonical})
        })
        .collect();
    let rejections: Vec<Value> = CANONICAL_REJECTIONS
        .iter()
        .map(|(name, reason)| json!({"name": name, "reason": reason}))
        .collect();
    json!({
        "schemaVersion": CANONICAL_VECTORS_SCHEMA_VERSION,
        "canonicalJsonVersion": CANONICAL_JSON_VERSION,
        "bundleVersion": BUNDLE_VERSION,
        "cliVersion": crate::CLI_VERSION,
        "vectors": vectors,
        "rejections": rejections,
    })
}

// MARK: JSON Schemas

/// Swift `Schemas.header`.
fn header(title: &str, description: &str) -> Map<String, Value> {
    let mut fields = Map::new();
    fields.insert("$schema".into(), json!(DRAFT));
    fields.insert("$comment".into(), json!(GENERATED_NOTICE));
    fields.insert("title".into(), json!(title));
    fields.insert("description".into(), json!(description));
    fields.insert("x-arkdeck-bundleVersion".into(), json!(BUNDLE_VERSION));
    fields.insert("x-arkdeck-cliVersion".into(), json!(crate::CLI_VERSION));
    fields
}

/// Swift `Schemas.errorObject`: a failure's error, its code one of the
/// registry's.
fn error_object() -> Value {
    json!({
        "type": "object",
        "required": ["code", "message", "controlRequestRetryable", "attentionRequired"],
        "properties": {
            "code": {"enum": crate::error_registry::CODES
                .iter()
                .map(|(code, _)| *code)
                .collect::<Vec<_>>()},
            "message": {"type": "string"},
            "controlRequestRetryable": {"type": "boolean"},
            "attentionRequired": {"type": "boolean"},
            "details": {"type": "object"},
        },
        "additionalProperties": false,
    })
}

/// Swift `Schemas.lifecycleObject`.
fn lifecycle_object() -> Value {
    json!({
        "type": "object",
        "required": ["status", "replacementArgvPattern", "removalVersion"],
        "properties": {
            "status": {"enum": ["deprecated", "legacy"]},
            "replacementArgvPattern": {"type": ["string", "null"]},
            "removalVersion": {"type": ["string", "null"]},
        },
        "additionalProperties": false,
    })
}

/// A result or a terminal frame: `result` when `ok`, `error` otherwise,
/// never both.
fn result_or_error() -> Value {
    json!([
        {
            "properties": {"ok": {"const": true}},
            "required": ["result"],
            "not": {"required": ["error"]},
        },
        {
            "properties": {"ok": {"const": false}},
            "required": ["error"],
            "not": {"required": ["result"]},
        },
    ])
}

/// Swift `Schemas.result`.
fn result_schema() -> Value {
    let mut fields = header(
        RESULT_SCHEMA_VERSION,
        "The single result document a machine-mode invocation writes to stdout (§8.1, §8.2).",
    );
    fields.insert("type".into(), json!("object"));
    fields.insert(
        "required".into(),
        json!(["schemaVersion", "command", "ok", "meta"]),
    );
    fields.insert(
        "properties".into(),
        json!({
            "schemaVersion": {"const": RESULT_SCHEMA_VERSION},
            "command": {"type": "string", "pattern": COMMAND_PATTERN},
            "ok": {"type": "boolean"},
            "result": {},
            "error": {"$ref": "#/$defs/error"},
            "meta": {"$ref": "#/$defs/meta"},
        }),
    );
    fields.insert("additionalProperties".into(), json!(false));
    fields.insert("oneOf".into(), result_or_error());
    fields.insert(
        "$defs".into(),
        json!({
            "error": error_object(),
            "lifecycle": lifecycle_object(),
            "meta": {
                "type": "object",
                "required": ["controlRequestId", "cliVersion"],
                "properties": {
                    "controlRequestId": {"type": "string", "pattern": CONTROL_REQUEST_ID_PATTERN},
                    "cliVersion": {"type": "string"},
                    "controlProtocolVersion": {"const": PROTOCOL_VERSION},
                    "lifecycle": {"$ref": "#/$defs/lifecycle"},
                },
                "additionalProperties": false,
            },
            "errorRegistryVersion": {"const": crate::error_registry::VERSION},
        }),
    );
    Value::Object(fields)
}

/// Swift `Schemas.event`: a Runtime event line, or the one terminal frame.
fn event_schema() -> Value {
    let mut fields = header(
        EVENT_SCHEMA_VERSION,
        "One JSONL line of a streaming invocation: a Runtime event or the single terminal frame (§8.3).",
    );
    let mut common = Map::new();
    common.insert(
        "schemaVersion".into(),
        json!({"const": EVENT_SCHEMA_VERSION}),
    );
    common.insert("sequence".into(), json!({"type": "integer", "minimum": 1}));
    common.insert("type".into(), json!({"type": "string", "minLength": 1}));
    common.insert(
        "command".into(),
        json!({"type": "string", "pattern": COMMAND_PATTERN}),
    );
    common.insert(
        "controlRequestId".into(),
        json!({"type": "string", "pattern": CONTROL_REQUEST_ID_PATTERN}),
    );
    let mut terminal = common.clone();
    terminal.insert("type".into(), json!({"const": "terminal"}));
    terminal.insert("ok".into(), json!({"type": "boolean"}));
    terminal.insert(
        "exitCode".into(),
        json!({"type": "integer", "minimum": 0, "maximum": 255}),
    );
    terminal.insert("lastCursor".into(), json!({"type": ["string", "null"]}));
    terminal.insert("result".into(), json!({}));
    terminal.insert("error".into(), json!({"$ref": "#/$defs/error"}));
    let mut event = common;
    if let Value::Object(item) = &event_item()["properties"] {
        event.extend(item.clone());
    }
    fields.insert("type".into(), json!("object"));
    fields.insert(
        "required".into(),
        json!([
            "schemaVersion",
            "sequence",
            "type",
            "command",
            "controlRequestId"
        ]),
    );
    fields.insert(
        "oneOf".into(),
        json!([
            {"$ref": "#/$defs/terminalFrame"},
            {"$ref": "#/$defs/runtimeEventFrame"},
        ]),
    );
    fields.insert(
        "$defs".into(),
        json!({
            "error": error_object(),
            "terminalFrame": {
                "type": "object",
                "required": [
                    "schemaVersion", "sequence", "type", "command", "controlRequestId", "ok",
                    "exitCode", "lastCursor",
                ],
                "properties": terminal,
                "additionalProperties": false,
                "oneOf": result_or_error(),
            },
            "runtimeEventFrame": {
                "type": "object",
                "required": [
                    "schemaVersion", "sequence", "type", "command", "controlRequestId", "eventId",
                    "streamPosition", "cursor",
                ],
                "properties": event,
                "not": {"properties": {"type": {"const": "terminal"}}},
            },
        }),
    );
    Value::Object(fields)
}

/// Swift `Schemas.controlPlane`: the frames the CLI exchanges with the
/// Runtime, and the closed method set it may name, each pointing at its
/// typed schema. It is built from the compiled contract, so it follows the
/// contract inputs.
fn control_plane_schema() -> Value {
    let mut fields = header(
        CONTROL_PLANE_SCHEMA_VERSION,
        "The local control-plane request and response frames the CLI exchanges with the Runtime, and the closed method set it may name.",
    );
    let mut methods: Vec<&str> = METHODS.to_vec();
    methods.sort_unstable();
    let table: Vec<Value> = methods
        .iter()
        .map(|method| {
            json!({
                "method": method,
                "published": true,
                "schema": format!("{CONTROL_METHOD_SCHEMA_DIRECTORY}/{method}.json"),
            })
        })
        .collect();
    fields.insert(
        "oneOf".into(),
        json!([{"$ref": "#/$defs/request"}, {"$ref": "#/$defs/response"}]),
    );
    fields.insert(
        "x-arkdeck-currentProtocolVersion".into(),
        json!(PROTOCOL_VERSION),
    );
    fields.insert(
        "x-arkdeck-contractIdentity".into(),
        json!(CONTRACT_IDENTITY),
    );
    fields.insert(
        "x-arkdeck-methodSchemaDirectory".into(),
        json!(CONTROL_METHOD_SCHEMA_DIRECTORY),
    );
    fields.insert("x-arkdeck-methods".into(), json!(table));
    fields.insert(
        "$defs".into(),
        json!({
            "request": {
                "type": "object",
                "required": ["protocolVersion", "contractIdentity", "id", "method"],
                "properties": {
                    "protocolVersion": {"const": PROTOCOL_VERSION},
                    "contractIdentity": {"const": CONTRACT_IDENTITY},
                    "id": {"type": "string", "minLength": 1},
                    "method": {"enum": methods},
                    "params": {"type": "object"},
                },
                "additionalProperties": false,
            },
            "response": {
                "type": "object",
                "required": ["id", "ok"],
                "properties": {
                    "id": {"type": "string", "minLength": 1},
                    "ok": {"type": "boolean"},
                    "result": {},
                    "error": {"$ref": "#/$defs/wireError"},
                },
                "additionalProperties": false,
                "oneOf": result_or_error(),
            },
            "wireError": {
                "type": "object",
                "required": ["code", "message"],
                "properties": {
                    "code": {"type": "string", "minLength": 1},
                    "message": {"type": "string"},
                    "details": {"type": "object"},
                },
                "additionalProperties": false,
            },
        }),
    );
    Value::Object(fields)
}

/// Swift `Schemas.eventItem`.
fn event_item() -> Value {
    json!({
        "type": "object",
        "required": ["eventId", "streamPosition", "cursor", "type"],
        "properties": {
            "eventId": {"type": "string", "minLength": 1},
            "streamPosition": {"type": "string", "pattern": DECIMAL_POSITION_PATTERN},
            "runtimeRevision": {"type": "string"},
            "cursor": {"type": "string", "minLength": 1},
            "type": {"type": "string", "minLength": 1},
            "data": {},
        },
    })
}

/// Swift `Schemas.page`.
fn page_schema() -> Value {
    let mut fields = header(
        PAGE_SCHEMA_VERSION,
        "The fixed page shape every list and events result uses (§7.3).",
    );
    fields.insert("type".into(), json!("object"));
    fields.insert(
        "required".into(),
        json!([
            "schemaVersion",
            "pageKind",
            "items",
            "order",
            "snapshotRevision",
            "hasMore",
            "nextCursor",
        ]),
    );
    fields.insert(
        "properties".into(),
        json!({
            "schemaVersion": {"const": PAGE_SCHEMA_VERSION},
            "pageKind": {"enum": ["snapshot", "eventStream"]},
            "items": {"type": "array"},
            "order": {"type": "string", "minLength": 1},
            "snapshotRevision": {"type": "string"},
            "hasMore": {"type": "boolean"},
            "nextCursor": {"type": ["string", "null"]},
        }),
    );
    fields.insert("additionalProperties".into(), json!(false));
    fields.insert(
        "allOf".into(),
        json!([
            {
                "if": {"properties": {"pageKind": {"const": "eventStream"}}},
                "then": {"properties": {
                    "order": {"const": "streamPositionAsc"},
                    "nextCursor": {"type": "string", "minLength": 1},
                    "items": {"items": {"$ref": "#/$defs/eventItem"}},
                }},
            },
            {
                "if": {"properties": {
                    "pageKind": {"const": "snapshot"},
                    "hasMore": {"const": false},
                }},
                "then": {"properties": {"nextCursor": {"type": "null"}}},
            },
            {
                "if": {"properties": {"hasMore": {"const": true}}},
                "then": {"properties": {"nextCursor": {"type": "string", "minLength": 1}}},
            },
        ]),
    );
    fields.insert("$defs".into(), json!({"eventItem": event_item()}));
    Value::Object(fields)
}

/// Swift `Schemas.ownerObject(kinds:)`.
fn owner_object(kinds: &[&str]) -> Value {
    json!({
        "type": "object",
        "required": ["kind", "id"],
        "properties": {
            "kind": {"enum": kinds},
            "id": {"type": "string", "minLength": 1},
        },
        "additionalProperties": false,
    })
}

/// Swift `Schemas.branch`: one closed branch of the §7.3 union.
fn branch(
    kind: &str,
    owner_kinds: &[&str],
    resource_kinds: &[&str],
    reason_codes: Option<&[&str]>,
    extra: Value,
    required: &[&str],
    resource_mirrors_owner: bool,
) -> Value {
    let mut properties = Map::new();
    properties.insert("kind".into(), json!({"const": kind}));
    properties.insert("owner".into(), owner_object(owner_kinds));
    properties.insert("resource".into(), owner_object(resource_kinds));
    properties.insert(
        "reasonCode".into(),
        match reason_codes {
            Some(codes) => json!({"enum": codes}),
            None => json!({"type": "string", "minLength": 1}),
        },
    );
    if let Value::Object(extra) = extra {
        properties.extend(extra);
    }
    let mut all_required = vec!["kind", "owner", "resource", "reasonCode"];
    all_required.extend_from_slice(required);
    let mut fields = Map::new();
    fields.insert("type".into(), json!("object"));
    fields.insert("required".into(), json!(all_required));
    fields.insert("properties".into(), Value::Object(properties));
    fields.insert("additionalProperties".into(), json!(false));
    if resource_mirrors_owner {
        fields.insert(
            "allOf".into(),
            owner_kinds
                .iter()
                .map(|owner| {
                    json!({
                        "if": {"properties": {"owner": {"properties": {"kind": {"const": owner}}}}},
                        "then": {"properties": {"resource": {"properties": {"kind": {"const": owner}}}}},
                    })
                })
                .collect(),
        );
    }
    Value::Object(fields)
}

/// Swift `Schemas.nextAction`.
fn next_action_schema() -> Value {
    let mut fields = header(
        NEXT_ACTION_SCHEMA_VERSION,
        "The closed nextAction union shared by job status and agent status; null when nothing is pending (§7.3).",
    );
    let execution_owners = ["job", "agentExecution", "controlAction"];
    fields.insert(
        "oneOf".into(),
        json!([
            {"type": "null"},
            {"$ref": "#/$defs/wait"},
            {"$ref": "#/$defs/humanAction"},
            {"$ref": "#/$defs/reconcile"},
            {"$ref": "#/$defs/cleanup"},
            {"$ref": "#/$defs/readResult"},
        ]),
    );
    fields.insert(
        "$defs".into(),
        json!({
            "wait": branch(
                "wait",
                &execution_owners,
                &execution_owners,
                Some(&["job.running", "agent.orchestrationPending", "lifecycle.pending"]),
                json!({"retryAfter": {"type": "string", "pattern": DURATION_PATTERN}}),
                &["retryAfter"],
                true,
            ),
            "humanAction": branch(
                "humanAction",
                &execution_owners,
                &["humanAction"],
                None,
                json!({
                    "resumeReference": {"type": "string", "minLength": 1},
                    "expiresAt": {"type": ["string", "null"], "format": "date-time"},
                }),
                &["resumeReference", "expiresAt"],
                false,
            ),
            "reconcile": branch(
                "reconcile",
                &["job", "controlAction"],
                &["job", "controlAction"],
                Some(&[
                    "recovery.outcomeUnknown",
                    "lifecycle.outcomeUnknown",
                    "job.finalizationPending",
                ]),
                json!({}),
                &[],
                true,
            ),
            "cleanup": branch(
                "cleanup",
                &["job"],
                &["cleanupDebt"],
                Some(&["recovery.cleanupDebt"]),
                json!({}),
                &[],
                false,
            ),
            "readResult": branch(
                "readResult",
                &["job"],
                &["job"],
                Some(&["job.resultAvailable"]),
                json!({}),
                &[],
                false,
            ),
        }),
    );
    Value::Object(fields)
}

// MARK: Sample documents (Swift `SampleDocuments`): one conformance sample
// per `nextAction` kind and per page kind.

const JOB_ID: &str = "job-0f3c2a7e-4d1b-4c0a-9e2d-5b6a7c8d9e0f";
const EVENT_CURSOR: &str = "evc-1.job-0f3c2a7e.12";

fn next_actions() -> Vec<(&'static str, Value)> {
    let job = json!({"kind": "job", "id": JOB_ID});
    vec![
        (
            "wait",
            json!({
                "kind": "wait",
                "owner": job,
                "resource": job,
                "reasonCode": "job.running",
                "retryAfter": "250ms",
            }),
        ),
        (
            "humanAction",
            json!({
                "kind": "humanAction",
                "owner": {
                    "kind": "agentExecution",
                    "id": "exec-7a1d3f52-2c9e-4b8a-a1d0-3e4f5a6b7c8d",
                },
                "resource": {
                    "kind": "humanAction",
                    "id": "har-2b3c4d5e-6f70-4a8b-9c0d-1e2f3a4b5c6d",
                },
                "reasonCode": "device.trustPending",
                "resumeReference": "resume-9d8c7b6a-5f4e-4d3c-b2a1-0f9e8d7c6b5a",
                "expiresAt": "2026-08-30T12:00:00Z",
            }),
        ),
        (
            "reconcile",
            json!({
                "kind": "reconcile",
                "owner": job,
                "resource": job,
                "reasonCode": "recovery.outcomeUnknown",
            }),
        ),
        (
            "cleanup",
            json!({
                "kind": "cleanup",
                "owner": job,
                "resource": {
                    "kind": "cleanupDebt",
                    "id": "debt-3c4d5e6f-7a8b-4c9d-8e0f-1a2b3c4d5e6f",
                },
                "reasonCode": "recovery.cleanupDebt",
            }),
        ),
        (
            "readResult",
            json!({
                "kind": "readResult",
                "owner": job,
                "resource": job,
                "reasonCode": "job.resultAvailable",
            }),
        ),
    ]
}

/// Swift `fixtureControlRequestID`: fixed, so the committed envelopes are a
/// function of the build alone.
const FIXTURE_CONTROL_REQUEST_ID: &str = "ctl-fixture-0001";
/// Swift `argvFixtureSchemaVersion`, `envelopeFixtureSchemaVersion` and
/// `fixtureIndexSchemaVersion`.
const ARGV_FIXTURE_SCHEMA_VERSION: &str = "arkdeck.cli.argv-fixture/1";
const ENVELOPE_FIXTURE_SCHEMA_VERSION: &str = "arkdeck.cli.envelope-fixture/1";
const FIXTURE_INDEX_SCHEMA_VERSION: &str = "arkdeck.cli.fixture-index/1";

fn wait_action() -> Value {
    next_actions()
        .into_iter()
        .find(|(kind, _)| *kind == "wait")
        .map(|(_, action)| action)
        .expect("the wait sample")
}

/// Swift `SampleDocuments.jobStatus`.
fn job_status() -> Value {
    json!({
        "jobId": JOB_ID,
        "state": "running",
        "operation": "observe.device@1",
        "runtimeRevision": "12",
        "nextAction": wait_action(),
    })
}

/// Swift `SampleDocuments.eventRow`.
fn event_row() -> Value {
    json!({
        "eventId": "evt-6c5b4a39-2817-4f0e-9d8c-7b6a5f4e3d2c",
        "streamPosition": "12",
        "runtimeRevision": "12",
        "cursor": EVENT_CURSOR,
        "type": "job.stepCompleted",
        "data": {"stepId": "observe-device", "outcome": "verified"},
    })
}

/// Swift `SampleDocuments.emptySnapshotPage`.
fn empty_snapshot_page() -> Value {
    json!({
        "schemaVersion": PAGE_SCHEMA_VERSION,
        "pageKind": "snapshot",
        "items": [],
        "order": "createdAtDescJobIdAsc",
        "snapshotRevision": "rev-000000000012",
        "hasMore": false,
        "nextCursor": null,
    })
}

// MARK: Argv fixtures

fn array(value: &Value) -> &[Value] {
    value.as_array().map_or(&[], Vec::as_slice)
}

fn name(option: &Value) -> &str {
    option["name"].as_str().expect("an option's name")
}

fn required_and_published(option: &Value) -> bool {
    option["required"] == true && option["published"] == true
}

/// Swift `ArgvFixtures.sample(for:)`, over the registry's projection of each
/// grammar.
fn sample(grammar: &Value) -> String {
    let number = |key: &str| {
        grammar[key]
            .as_u64()
            .unwrap_or_else(|| panic!("{key} of {grammar}"))
    };
    match grammar["kind"].as_str() {
        Some("opaque") => "sample".into(),
        Some("positiveInteger" | "nonNegativeInteger") => number("minimum").to_string(),
        Some("enumeration") => grammar["values"][0].as_str().unwrap_or("sample").into(),
        Some("hexDigest") => "0".repeat(number("length") as usize),
        // Swift projects its control-request identity grammar as this pattern.
        Some("pattern") if grammar["pattern"] == CONTROL_REQUEST_ID_PATTERN => {
            FIXTURE_CONTROL_REQUEST_ID.into()
        }
        Some("duration") if number("maximumMilliseconds") >= 1000 => "1s".into(),
        Some("duration") => "1ms".into(),
        _ => panic!("no sample for the grammar {grammar}"),
    }
}

/// The option and, if it takes one, a sample value.
fn push_option(argv: &mut Vec<String>, option: &Value) {
    argv.push(name(option).into());
    if option["form"] == "value" {
        argv.push(sample(&option["grammar"]));
    }
}

/// Swift `ArgvFixtures.validArgv`: the path, each required published option,
/// the first declared member of each exactly-one group nothing named yet, and
/// each required positional, all with samples.
fn valid_argv(path: &[String], leaf: &Value) -> Vec<String> {
    let options = array(&leaf["options"]);
    let mut argv = path.to_vec();
    let mut present: Vec<&str> = Vec::new();
    for option in options
        .iter()
        .filter(|option| required_and_published(option))
    {
        push_option(&mut argv, option);
        present.push(name(option));
    }
    for group in array(&leaf["requiresExactlyOneOf"]) {
        let group: Vec<&str> = array(group).iter().filter_map(Value::as_str).collect();
        if group.iter().any(|member| present.contains(member)) {
            continue;
        }
        if let Some(option) = options.iter().find(|option| group.contains(&name(option))) {
            push_option(&mut argv, option);
            present.push(name(option));
        }
    }
    for positional in array(&leaf["positionals"]) {
        if positional["required"] == true {
            argv.push(sample(&positional["grammar"]));
        }
    }
    argv
}

/// What this CLI's parser answers `argv` with: a leaf that is not
/// executable by name, as it serves one (`command_registry::answer_by_name`),
/// any other by the registry pass.
fn parsed(argv: &[String]) -> Result<Accepted, CliError> {
    match command_registry::answer_by_name(argv) {
        Some(Ok(invocation)) => {
            assert!(invocation.help, "{argv:?} is answered by name with help");
            Ok(Accepted::LeafHelp(invocation.command))
        }
        Some(Err(error)) => Err(error),
        None => registry_parse::check(argv).map(|accepted| {
            accepted.unwrap_or_else(|| panic!("the registry pass leaves {argv:?} to the parser"))
        }),
    }
}

/// Swift `ArgvFixtures.outcome`: the answer, and for a refusal its code, exit
/// category and status, the leaf it names, and that leaf's lifecycle where
/// the registry publishes it as legacy or deprecated.
fn outcome(argv: &[String]) -> Value {
    match parsed(argv) {
        Ok(Accepted::RootHelp) => json!({"outcome": "rootHelp"}),
        Ok(Accepted::LeafHelp(command)) => json!({"outcome": "leafHelp", "command": command}),
        Ok(Accepted::Commands(mode)) => json!({"outcome": "commands", "outputMode": mode}),
        Ok(Accepted::Completion(shell)) => json!({"outcome": "completion", "shell": shell}),
        Ok(Accepted::Dispatch {
            command,
            handler_arguments,
        }) => json!({
            "outcome": "dispatch",
            "command": command,
            "handlerArguments": handler_arguments,
        }),
        Err(error) => {
            let category = error_registry::category(error.code)
                .unwrap_or_else(|| panic!("{} is a registry code", error.code));
            let mut fields = json!({
                "outcome": "failure",
                "code": error.code,
                "category": category.machine_name(),
                "exitCode": error.exit_code(),
            });
            if let Some(command) = error.command {
                fields["command"] = json!(command);
                if let Some((status, replacement)) = command_registry::lifecycle(command) {
                    fields["lifecycleStatus"] = json!(status);
                    if let Some(pattern) = replacement {
                        fields["replacementArgvPattern"] = json!(pattern);
                    }
                }
            }
            fields
        }
    }
}

/// Swift `ArgvFixtures.document`: a leaf's argv cases, each with the answer
/// this CLI's parser gives it.
fn argv_document(leaf: &Value) -> Value {
    let command = leaf["command"]
        .as_str()
        .expect("a leaf's canonical command");
    let path: Vec<String> = array(&leaf["path"])
        .iter()
        .filter_map(Value::as_str)
        .map(str::to_owned)
        .collect();
    let options = array(&leaf["options"]);
    let valid = valid_argv(&path, leaf);
    let with = |base: &[String], extra: &[&str]| -> Vec<String> {
        base.iter()
            .cloned()
            .chain(extra.iter().map(|word| (*word).to_owned()))
            .collect()
    };
    let mut cases = vec![
        ("valid", valid.clone()),
        ("leafHelp", with(&path, &["--help"])),
    ];
    if leaf["kind"] == "executable" {
        cases.push(("unknownOption", with(&valid, &["--no-such-option"])));
        if let Some(option) = options.iter().find(|option| required_and_published(option)) {
            let mut duplicate = valid.clone();
            push_option(&mut duplicate, option);
            cases.push(("duplicateOption", duplicate));
        }
        if options.iter().any(required_and_published)
            || !array(&leaf["requiresExactlyOneOf"]).is_empty()
            || array(&leaf["positionals"])
                .iter()
                .any(|positional| positional["required"] == true)
        {
            cases.push(("missingRequired", path.clone()));
        }
        let declares = |option: &str| options.iter().any(|declared| declared["name"] == option);
        if declares("--output") && !array(&leaf["outputModes"]).contains(&json!("jsonl")) {
            cases.push(("jsonlRefused", with(&valid, &["--output", "jsonl"])));
        }
        if (leaf["connectsToRuntime"] != true || command == "runtime.tool.register")
            && !declares("--endpoint")
        {
            cases.push(("endpointRefused", with(&valid, &["--endpoint", "local"])));
        }
        if let Some(option) = options
            .iter()
            .find(|option| option["stability"] == "macosCompatibilityOnly")
            .filter(|option| option["form"] == "value")
        {
            let value = sample(&option["grammar"]);
            cases.push((
                "macosCompatibilityOption",
                with(&valid, &[name(option), &value]),
            ));
        }
        if command == "runtime.tool.register" {
            let socket = ["--socket", "/private/tmp/arkdeck.sock"];
            let deveco = [
                "--kind",
                "deveco",
                "--root",
                "/Applications/DevEco-Studio.app/Contents",
            ];
            cases.push(("devecoSocket", with(&with(&path, &deveco), &socket)));
            cases.push(("hdcSocketRefused", with(&valid, &socket)));
        }
        match parsed(&valid) {
            Ok(Accepted::Dispatch {
                command: dispatched,
                ..
            }) if dispatched != command => {
                panic!("the generated valid argv for {command} dispatches to {dispatched}")
            }
            Ok(_) => {}
            Err(error) => {
                panic!("the generated valid argv for {command} is refused: {valid:?}: {error:?}")
            }
        }
    }
    let cases: Vec<Value> = cases
        .into_iter()
        .map(|(name, argv)| json!({"name": name, "expected": outcome(&argv), "argv": argv}))
        .collect();
    json!({
        "schemaVersion": ARGV_FIXTURE_SCHEMA_VERSION,
        "cliVersion": crate::CLI_VERSION,
        "command": command,
        "path": path,
        "kind": leaf["kind"],
        "lifecycleStatus": leaf["lifecycleStatus"],
        "cases": cases,
    })
}

/// Swift `ArgvFixtures`: one document for each leaf of the registry.
fn argv_fixtures() -> Vec<Product> {
    let projection = command_registry::projection();
    let mut seen = BTreeSet::new();
    array(&projection["commands"])
        .iter()
        .map(|leaf| {
            let command = leaf["command"]
                .as_str()
                .expect("a leaf's canonical command");
            assert!(
                seen.insert(command.to_owned()),
                "canonical command {command} is declared twice"
            );
            Product::json(&format!("argv/{command}.json"), &argv_document(leaf))
        })
        .collect()
}

/// Swift `EnvelopeFixtures.products`: one of each machine answer, each
/// written by the code this CLI answers with. The two refusals are its
/// parser's own, for `job status` without `--job` and for the retired
/// `agent chat`.
fn envelope_products() -> Vec<Product> {
    let id = FIXTURE_CONTROL_REQUEST_ID;
    let argv = |words: &[&str]| {
        words
            .iter()
            .map(|word| word.to_string())
            .collect::<Vec<_>>()
    };
    let Err(missing) = crate::parse(&argv(&["job", "status"])) else {
        panic!("`job status` without --job fails at parse time");
    };
    let Err(removed) = crate::parse(&argv(&["agent", "chat"])) else {
        panic!("`agent chat` is a tombstone");
    };
    let mut unavailable =
        crate::CliError::new("runtimeUnavailable", "the local Runtime did not answer");
    unavailable
        .details
        .insert("endpoint".into(), json!("local"));
    unavailable
        .details
        .insert("newDispatchCount".into(), json!(0));
    let status = job_status();
    let answers = [
        (
            "envelopes/result-success.json",
            crate::local_success_envelope("job.status", status.clone(), id),
        ),
        (
            "envelopes/result-deprecated-alias.json",
            crate::with_lifecycle(
                crate::local_success_envelope("cleanup-debt.list", empty_snapshot_page(), id),
                "cleanup-debt.list",
            ),
        ),
        (
            "envelopes/result-argv-failure.json",
            crate::failure_envelope(
                missing.command.unwrap_or("registry.parse"),
                &missing,
                id,
                false,
            ),
        ),
        (
            "envelopes/result-removed-command.json",
            crate::with_lifecycle(
                crate::failure_envelope(
                    removed.command.unwrap_or("registry.parse"),
                    &removed,
                    id,
                    false,
                ),
                removed.command.unwrap_or("registry.parse"),
            ),
        ),
        (
            "envelopes/event-runtime-event.jsonl",
            crate::event_line("job.watch", 1, &event_row(), id),
        ),
        (
            "envelopes/event-terminal-success.jsonl",
            crate::terminal_line("job.wait", 2, id, Some(EVENT_CURSOR), Ok((&status, 0))),
        ),
        (
            "envelopes/event-terminal-failure.jsonl",
            crate::terminal_line("job.wait", 1, id, None, Err(&unavailable)),
        ),
    ];
    answers
        .into_iter()
        .map(|(path, answer)| Product {
            relative_path: path.into(),
            bytes: crate::render(&answer).expect("every envelope is canonical JSON"),
        })
        .collect()
}

fn snapshot_page() -> Value {
    json!({
        "schemaVersion": PAGE_SCHEMA_VERSION,
        "pageKind": "snapshot",
        "items": [{"jobId": JOB_ID, "state": "running", "createdAt": "2026-09-02T04:00:00Z"}],
        "order": "createdAtDescJobIdAsc",
        "snapshotRevision": "rev-000000000012",
        "hasMore": false,
        "nextCursor": null,
    })
}

fn event_stream_page() -> Value {
    json!({
        "schemaVersion": PAGE_SCHEMA_VERSION,
        "pageKind": "eventStream",
        "items": [event_row()],
        "order": "streamPositionAsc",
        "snapshotRevision": "12",
        "hasMore": false,
        "nextCursor": EVENT_CURSOR,
    })
}

#[cfg(test)]
mod tests {
    use super::sample;
    use serde_json::json;

    /// Swift `ArgvFixtures.sample(for:)` for the grammars no published case
    /// samples yet: no duration option is required, and each leaf's first
    /// macOS-compatibility option is `--socket`.
    #[test]
    fn a_duration_is_sampled_as_swift_samples_it() {
        let duration = |maximum: u64| json!({"kind": "duration", "maximumMilliseconds": maximum});
        assert_eq!(sample(&duration(600_000)), "1s");
        assert_eq!(sample(&duration(1000)), "1s");
        assert_eq!(sample(&duration(999)), "1ms");
    }
}
