//! Swift `CLIMachineContracts`: the §14 machine-contract bundle, rendered
//! by the build that publishes it.
//!
//! The products listed here are the ones this CLI owns so far; each is held
//! byte for byte to the committed bundle
//! (`rust/tests/fixtures/contracts-bundle/owned.json`). The rest stay Swift's
//! until their slices move them.
use arkdeck_contract::canonical_json;
use serde_json::{Map, Value, json};

/// Swift `CLIProductVersion.machineContract`.
pub const BUNDLE_VERSION: &str = "arkdeck.cli.contracts/1";
/// The page envelope every list and events result uses (§7.3).
pub const PAGE_SCHEMA_VERSION: &str = "arkdeck.cli.page/1";
/// The closed `nextAction` union shared by `job status` and `agent status`.
pub const NEXT_ACTION_SCHEMA_VERSION: &str = "arkdeck.cli.next-action/1";
pub const GENERATED_NOTICE: &str =
    "Generated by `arkdeck maintainer contracts export`; do not edit by hand.";

const DRAFT: &str = "https://json-schema.org/draft/2020-12/schema";
const DURATION_PATTERN: &str = "^[1-9][0-9]*(ms|s|m|h)$";
const DECIMAL_POSITION_PATTERN: &str = "^[1-9][0-9]*$";

/// One generated file: a path relative to its root, and its exact bytes.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Product {
    pub relative_path: String,
    pub bytes: Vec<u8>,
}

impl Product {
    fn json(relative_path: &str, value: &Value) -> Self {
        Self {
            relative_path: relative_path.into(),
            bytes: json_document(value),
        }
    }
}

/// The products this CLI owns under `openspec/contracts/`.
pub fn contract_products() -> Vec<Product> {
    vec![
        Product::json("cli-page.schema.json", &page_schema()),
        Product::json("cli-next-action.schema.json", &next_action_schema()),
    ]
}

/// The fixtures this CLI owns next to the contract tests
/// (`Fixtures/CLI/`), sorted by path as Swift writes them.
pub fn fixture_products() -> Vec<Product> {
    let mut products: Vec<Product> = next_actions()
        .into_iter()
        .map(|(kind, document)| Product::json(&format!("next-action/{kind}.json"), &document))
        .collect();
    products.push(Product::json("next-action/null.json", &Value::Null));
    products.push(Product::json("page/snapshot.json", &snapshot_page()));
    products.push(Product::json(
        "page/event-stream.json",
        &event_stream_page(),
    ));
    products.sort_by(|left, right| left.relative_path.cmp(&right.relative_path));
    products
}

// MARK: Rendering

/// Swift `ContractJSON.document`: pretty JSON with keys in
/// `arkdeck.cli.canonical-json/1` order (UTF-16 code units), two-space
/// indentation, scalars as the canonical encoder writes them, empty
/// containers inline, and one trailing LF.
pub fn json_document(value: &Value) -> Vec<u8> {
    let mut out = String::new();
    render(value, 0, &mut out);
    out.push('\n');
    out.into_bytes()
}

/// A scalar as the canonical encoder writes it; Swift writes `null` for one
/// the encoder refuses.
fn scalar(value: &Value) -> String {
    canonical_json(value)
        .ok()
        .and_then(|bytes| String::from_utf8(bytes).ok())
        .unwrap_or_else(|| "null".into())
}

/// Keys in UTF-16 code-unit order.
fn sorted_keys(fields: &Map<String, Value>) -> Vec<&String> {
    let mut keys: Vec<&String> = fields.keys().collect();
    keys.sort_by(|left, right| left.encode_utf16().cmp(right.encode_utf16()));
    keys
}

fn render(value: &Value, indent: usize, out: &mut String) {
    let pad = "  ".repeat(indent);
    match value {
        Value::Object(fields) if fields.is_empty() => out.push_str("{}"),
        Value::Object(fields) => {
            out.push_str("{\n");
            let keys = sorted_keys(fields);
            for (offset, key) in keys.iter().enumerate() {
                out.push_str(&pad);
                out.push_str("  ");
                out.push_str(&scalar(&Value::String((*key).clone())));
                out.push_str(": ");
                render(&fields[*key], indent + 1, out);
                out.push_str(if offset == keys.len() - 1 {
                    "\n"
                } else {
                    ",\n"
                });
            }
            out.push_str(&pad);
            out.push('}');
        }
        Value::Array(items) if items.is_empty() => out.push_str("[]"),
        Value::Array(items) => {
            out.push_str("[\n");
            for (offset, item) in items.iter().enumerate() {
                out.push_str(&pad);
                out.push_str("  ");
                render(item, indent + 1, out);
                out.push_str(if offset == items.len() - 1 {
                    "\n"
                } else {
                    ",\n"
                });
            }
            out.push_str(&pad);
            out.push(']');
        }
        other => out.push_str(&scalar(other)),
    }
}

// MARK: JSON Schemas

/// Swift `Schemas.header`.
fn header(title: &str, description: &str) -> Map<String, Value> {
    let mut fields = Map::new();
    fields.insert("$schema".into(), json!(DRAFT));
    fields.insert("$comment".into(), json!(GENERATED_NOTICE));
    fields.insert("title".into(), json!(title));
    fields.insert("description".into(), json!(description));
    fields.insert("x-arkdeck-bundleVersion".into(), json!(BUNDLE_VERSION));
    fields.insert("x-arkdeck-cliVersion".into(), json!(crate::CLI_VERSION));
    fields
}

/// Swift `Schemas.eventItem`.
fn event_item() -> Value {
    json!({
        "type": "object",
        "required": ["eventId", "streamPosition", "cursor", "type"],
        "properties": {
            "eventId": {"type": "string", "minLength": 1},
            "streamPosition": {"type": "string", "pattern": DECIMAL_POSITION_PATTERN},
            "runtimeRevision": {"type": "string"},
            "cursor": {"type": "string", "minLength": 1},
            "type": {"type": "string", "minLength": 1},
            "data": {},
        },
    })
}

/// Swift `Schemas.page`.
fn page_schema() -> Value {
    let mut fields = header(
        PAGE_SCHEMA_VERSION,
        "The fixed page shape every list and events result uses (§7.3).",
    );
    fields.insert("type".into(), json!("object"));
    fields.insert(
        "required".into(),
        json!([
            "schemaVersion",
            "pageKind",
            "items",
            "order",
            "snapshotRevision",
            "hasMore",
            "nextCursor",
        ]),
    );
    fields.insert(
        "properties".into(),
        json!({
            "schemaVersion": {"const": PAGE_SCHEMA_VERSION},
            "pageKind": {"enum": ["snapshot", "eventStream"]},
            "items": {"type": "array"},
            "order": {"type": "string", "minLength": 1},
            "snapshotRevision": {"type": "string"},
            "hasMore": {"type": "boolean"},
            "nextCursor": {"type": ["string", "null"]},
        }),
    );
    fields.insert("additionalProperties".into(), json!(false));
    fields.insert(
        "allOf".into(),
        json!([
            {
                "if": {"properties": {"pageKind": {"const": "eventStream"}}},
                "then": {"properties": {
                    "order": {"const": "streamPositionAsc"},
                    "nextCursor": {"type": "string", "minLength": 1},
                    "items": {"items": {"$ref": "#/$defs/eventItem"}},
                }},
            },
            {
                "if": {"properties": {
                    "pageKind": {"const": "snapshot"},
                    "hasMore": {"const": false},
                }},
                "then": {"properties": {"nextCursor": {"type": "null"}}},
            },
            {
                "if": {"properties": {"hasMore": {"const": true}}},
                "then": {"properties": {"nextCursor": {"type": "string", "minLength": 1}}},
            },
        ]),
    );
    fields.insert("$defs".into(), json!({"eventItem": event_item()}));
    Value::Object(fields)
}

/// Swift `Schemas.ownerObject(kinds:)`.
fn owner_object(kinds: &[&str]) -> Value {
    json!({
        "type": "object",
        "required": ["kind", "id"],
        "properties": {
            "kind": {"enum": kinds},
            "id": {"type": "string", "minLength": 1},
        },
        "additionalProperties": false,
    })
}

/// Swift `Schemas.branch`: one closed branch of the §7.3 union.
fn branch(
    kind: &str,
    owner_kinds: &[&str],
    resource_kinds: &[&str],
    reason_codes: Option<&[&str]>,
    extra: Value,
    required: &[&str],
    resource_mirrors_owner: bool,
) -> Value {
    let mut properties = Map::new();
    properties.insert("kind".into(), json!({"const": kind}));
    properties.insert("owner".into(), owner_object(owner_kinds));
    properties.insert("resource".into(), owner_object(resource_kinds));
    properties.insert(
        "reasonCode".into(),
        match reason_codes {
            Some(codes) => json!({"enum": codes}),
            None => json!({"type": "string", "minLength": 1}),
        },
    );
    if let Value::Object(extra) = extra {
        properties.extend(extra);
    }
    let mut all_required = vec!["kind", "owner", "resource", "reasonCode"];
    all_required.extend_from_slice(required);
    let mut fields = Map::new();
    fields.insert("type".into(), json!("object"));
    fields.insert("required".into(), json!(all_required));
    fields.insert("properties".into(), Value::Object(properties));
    fields.insert("additionalProperties".into(), json!(false));
    if resource_mirrors_owner {
        fields.insert(
            "allOf".into(),
            owner_kinds
                .iter()
                .map(|owner| {
                    json!({
                        "if": {"properties": {"owner": {"properties": {"kind": {"const": owner}}}}},
                        "then": {"properties": {"resource": {"properties": {"kind": {"const": owner}}}}},
                    })
                })
                .collect(),
        );
    }
    Value::Object(fields)
}

/// Swift `Schemas.nextAction`.
fn next_action_schema() -> Value {
    let mut fields = header(
        NEXT_ACTION_SCHEMA_VERSION,
        "The closed nextAction union shared by job status and agent status; null when nothing is pending (§7.3).",
    );
    let execution_owners = ["job", "agentExecution", "controlAction"];
    fields.insert(
        "oneOf".into(),
        json!([
            {"type": "null"},
            {"$ref": "#/$defs/wait"},
            {"$ref": "#/$defs/humanAction"},
            {"$ref": "#/$defs/reconcile"},
            {"$ref": "#/$defs/cleanup"},
            {"$ref": "#/$defs/readResult"},
        ]),
    );
    fields.insert(
        "$defs".into(),
        json!({
            "wait": branch(
                "wait",
                &execution_owners,
                &execution_owners,
                Some(&["job.running", "agent.orchestrationPending", "lifecycle.pending"]),
                json!({"retryAfter": {"type": "string", "pattern": DURATION_PATTERN}}),
                &["retryAfter"],
                true,
            ),
            "humanAction": branch(
                "humanAction",
                &execution_owners,
                &["humanAction"],
                None,
                json!({
                    "resumeReference": {"type": "string", "minLength": 1},
                    "expiresAt": {"type": ["string", "null"], "format": "date-time"},
                }),
                &["resumeReference", "expiresAt"],
                false,
            ),
            "reconcile": branch(
                "reconcile",
                &["job", "controlAction"],
                &["job", "controlAction"],
                Some(&[
                    "recovery.outcomeUnknown",
                    "lifecycle.outcomeUnknown",
                    "job.finalizationPending",
                ]),
                json!({}),
                &[],
                true,
            ),
            "cleanup": branch(
                "cleanup",
                &["job"],
                &["cleanupDebt"],
                Some(&["recovery.cleanupDebt"]),
                json!({}),
                &[],
                false,
            ),
            "readResult": branch(
                "readResult",
                &["job"],
                &["job"],
                Some(&["job.resultAvailable"]),
                json!({}),
                &[],
                false,
            ),
        }),
    );
    Value::Object(fields)
}

// MARK: Sample documents (Swift `SampleDocuments`): one conformance sample
// per `nextAction` kind and per page kind.

const JOB_ID: &str = "job-0f3c2a7e-4d1b-4c0a-9e2d-5b6a7c8d9e0f";
const EVENT_CURSOR: &str = "evc-1.job-0f3c2a7e.12";

fn next_actions() -> Vec<(&'static str, Value)> {
    let job = json!({"kind": "job", "id": JOB_ID});
    vec![
        (
            "wait",
            json!({
                "kind": "wait",
                "owner": job,
                "resource": job,
                "reasonCode": "job.running",
                "retryAfter": "250ms",
            }),
        ),
        (
            "humanAction",
            json!({
                "kind": "humanAction",
                "owner": {
                    "kind": "agentExecution",
                    "id": "exec-7a1d3f52-2c9e-4b8a-a1d0-3e4f5a6b7c8d",
                },
                "resource": {
                    "kind": "humanAction",
                    "id": "har-2b3c4d5e-6f70-4a8b-9c0d-1e2f3a4b5c6d",
                },
                "reasonCode": "device.trustPending",
                "resumeReference": "resume-9d8c7b6a-5f4e-4d3c-b2a1-0f9e8d7c6b5a",
                "expiresAt": "2026-08-30T12:00:00Z",
            }),
        ),
        (
            "reconcile",
            json!({
                "kind": "reconcile",
                "owner": job,
                "resource": job,
                "reasonCode": "recovery.outcomeUnknown",
            }),
        ),
        (
            "cleanup",
            json!({
                "kind": "cleanup",
                "owner": job,
                "resource": {
                    "kind": "cleanupDebt",
                    "id": "debt-3c4d5e6f-7a8b-4c9d-8e0f-1a2b3c4d5e6f",
                },
                "reasonCode": "recovery.cleanupDebt",
            }),
        ),
        (
            "readResult",
            json!({
                "kind": "readResult",
                "owner": job,
                "resource": job,
                "reasonCode": "job.resultAvailable",
            }),
        ),
    ]
}

fn snapshot_page() -> Value {
    json!({
        "schemaVersion": PAGE_SCHEMA_VERSION,
        "pageKind": "snapshot",
        "items": [{"jobId": JOB_ID, "state": "running", "createdAt": "2026-09-02T04:00:00Z"}],
        "order": "createdAtDescJobIdAsc",
        "snapshotRevision": "rev-000000000012",
        "hasMore": false,
        "nextCursor": null,
    })
}

fn event_stream_page() -> Value {
    json!({
        "schemaVersion": PAGE_SCHEMA_VERSION,
        "pageKind": "eventStream",
        "items": [{
            "eventId": "evt-6c5b4a39-2817-4f0e-9d8c-7b6a5f4e3d2c",
            "streamPosition": "12",
            "runtimeRevision": "12",
            "cursor": EVENT_CURSOR,
            "type": "job.stepCompleted",
            "data": {"stepId": "observe-device", "outcome": "verified"},
        }],
        "order": "streamPositionAsc",
        "snapshotRevision": "12",
        "hasMore": false,
        "nextCursor": EVENT_CURSOR,
    })
}
