//! Task-private workspace Jobs generated by the real planner, admitter and
//! runner. Only the tool dispatch port is a counted stand-in; no child, HDC,
//! installed Runtime or Harmony tool is launched.
#![allow(dead_code)]

use arkdeck_contract::{ImportIntent, WireError, encode_import_chunk, sha256_hex};
use arkdeck_hoststore::{
    ArtifactReadStore, CapabilityStore, DeviceHolds, ImportBinding, ImportUploadStore, JobAdmitter,
    JobPlanner, JobReconciler, JobRecord, JobResultReader, JobRunner, JobStore, MutationAuthority,
    MutationExecution, ProfilePresets, SessionPublisher, SessionStore, StorageClaims, ToolFailure,
    ToolInvocation, ToolReceipt, WorkspaceCommandPreset, WorkspaceComposition, WorkspaceProfile,
    WorkspaceToolDispatch,
};
use serde_json::{Value, json};
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicUsize, Ordering};
use std::sync::{Arc, Mutex};

const PROFILE: &str = "publication-retry@1";
const PROJECT: &str = "PublicationRetryProject";
const INDEX: &str = "entry/src/main/ets/pages/Index.ets";
const PRODUCT: &str = "entry/build/default/outputs/default/entry-default-unsigned.hap";
pub const PATCH: &[u8] = b"--- a/entry/src/main/ets/pages/Index.ets\n+++ b/entry/src/main/ets/pages/Index.ets\n@@ -1 +1 @@\n-@Entry\n+@Entry // task-owned patch fixture\n";
pub const PATCHED_INDEX: &[u8] = b"@Entry // task-owned patch fixture\n";

fn now() -> Option<String> {
    Some("2026-10-06T00:00:00Z".into())
}

fn text(path: &Path) -> String {
    path.to_str().unwrap().to_owned()
}

struct Dispatch {
    root: PathBuf,
    executable: String,
    digest: String,
    calls: Arc<AtomicUsize>,
    patch_job: Arc<Mutex<Option<String>>>,
    patch_source: Arc<Mutex<Option<Value>>>,
}

impl WorkspaceToolDispatch for Dispatch {
    fn dispatch(&self, invocation: &ToolInvocation<'_>) -> Result<ToolReceipt, ToolFailure> {
        assert_eq!(invocation.executable_path, self.executable);
        assert_eq!(invocation.executable_sha256, self.digest);
        let working = Path::new(invocation.working_directory.unwrap());
        assert!(working.starts_with(self.root.join("evolution-workspaces")));
        match invocation.arguments {
            [task] if task == "build-fixture" => {
                let product = working.join(PRODUCT);
                fs::create_dir_all(product.parent().unwrap()).unwrap();
                fs::write(product, b"PK\x03\x04task-owned build fixture\n").unwrap();
            }
            [task] if task == "test-fixture" => {}
            [force, strip, directory, root, input, patch]
                if force == "-f" && strip == "-p1" && directory == "-d" && input == "-i" =>
            {
                assert_eq!(Path::new(root), working);
                assert_eq!(fs::read(patch).unwrap(), PATCH);
                assert_eq!(fs::read(working.join(INDEX)).unwrap(), b"@Entry\n");
                // Capture the durable audit after the real admission/consume
                // path and before this fixture performs its single effect.
                let job = self.patch_job.lock().unwrap().clone().unwrap();
                let source: Value = serde_json::from_slice(
                    &fs::read(
                        self.root
                            .join("state/jobs")
                            .join(job)
                            .join("job-record.json"),
                    )
                    .unwrap(),
                )
                .unwrap();
                assert_eq!(source["admissionEvidence"]["kind"], "runtimeCapability");
                *self.patch_source.lock().unwrap() = Some(source);
                fs::write(working.join(INDEX), PATCHED_INDEX).unwrap();
            }
            other => panic!("unexpected fixture argv: {other:?}"),
        }
        self.calls.fetch_add(1, Ordering::SeqCst);
        Ok(ToolReceipt {
            exit_status: 0,
            stdout: b"task-owned workspace fixture succeeded\n".to_vec(),
            stderr: Vec::new(),
            truncated: false,
        })
    }
}

pub struct Owners {
    pub root: PathBuf,
    state: PathBuf,
    pub job_ids: [String; 2],
    pub calls: Arc<AtomicUsize>,
    jobs: Option<JobStore>,
    artifacts: ArtifactReadStore,
    imports: ImportUploadStore,
    capabilities: CapabilityStore,
    holds: DeviceHolds,
    workspace: WorkspaceComposition,
    sessions: SessionStore,
    claims: StorageClaims,
    probe: crate::support::OracleProbe,
    imported: Value,
    copy_project: String,
    copy_root: PathBuf,
    copy_revision: String,
    patch_job: Arc<Mutex<Option<String>>>,
    patch_source: Arc<Mutex<Option<Value>>>,
}

impl Owners {
    pub fn new() -> Self {
        let nonce = u128::from_ne_bytes(arkdeck_platform::random_bytes::<16>().unwrap());
        let root = std::env::temp_dir()
            .canonicalize()
            .unwrap()
            .join(format!("arkdeck-workspace-publication-{nonce:032x}"));
        arkdeck_platform::create_private_directory(&root).unwrap();
        let root = arkdeck_platform::host_resolved_path(&root).unwrap();
        for name in ["state", "artifacts", "session-owner", "Sessions", "source"] {
            arkdeck_platform::HostDirectory::open_or_create_private(&root.join(name)).unwrap();
        }
        let source = root.join("source");
        for (relative, contents) in [
            (INDEX, "@Entry\n"),
            ("entry/src/main/module.json5", "{}\n"),
            ("build-profile.json5", "{}\n"),
        ] {
            let path = source.join(relative);
            fs::create_dir_all(path.parent().unwrap()).unwrap();
            fs::write(path, contents).unwrap();
        }
        // The same actual current image is pinned in the original plan. Its
        // own package version is the code-owned version source, not a guessed
        // version for another executable or a stand-in trust fact.
        let executable =
            arkdeck_platform::host_resolved_path(&std::env::current_exe().unwrap()).unwrap();
        let path = text(&executable);
        let digest = sha256_hex(&fs::read(&executable).unwrap());
        let preset = |id: &str, args: &[&str]| {
            WorkspaceCommandPreset::hashing(id, &path, None, args, 60).unwrap()
        };
        let profile = WorkspaceProfile::primary(
            PROFILE,
            PROJECT,
            &text(&source),
            &["entry/src/main/ets/**"],
            preset("inspect", &[]),
            preset("patch", &[]),
            ProfilePresets {
                build: vec![preset("fixture-build", &["build-fixture"])],
                test: vec![preset("fixture-tests", &["test-fixture"])],
                build_products: [("fixture-build".to_owned(), PRODUCT.to_owned())].into(),
                ..ProfilePresets::default()
            },
        )
        .unwrap();
        let calls = Arc::new(AtomicUsize::new(0));
        let patch_job = Arc::new(Mutex::new(None));
        let patch_source = Arc::new(Mutex::new(None));
        let workspace = WorkspaceComposition::with_profiles(
            vec![profile],
            &root.join("evolution-workspaces"),
            now,
        )
        .unwrap()
        .with_tool_dispatch(Box::new(Dispatch {
            root: root.clone(),
            executable: path,
            digest,
            calls: Arc::clone(&calls),
            patch_job: Arc::clone(&patch_job),
            patch_source: Arc::clone(&patch_source),
        }));
        let artifacts = ArtifactReadStore::open(&root.join("artifacts")).unwrap();
        let imports = ImportUploadStore::open(&root.join("artifacts")).unwrap();
        let imported = crate::support::debug_hap::import_package(
            &imports,
            &artifacts,
            "workspace-publication",
            "TGT-ISOLATED-IMPORT",
            1,
            &"a".repeat(64),
            &now().unwrap(),
        );
        let mut owners = Self {
            jobs: Some(JobStore::open_owner(&root.join("state")).unwrap()),
            capabilities: CapabilityStore::open(&root.join("state/capabilities")).unwrap(),
            sessions: SessionStore::open(&root.join("session-owner"), &root.join("Sessions"))
                .unwrap(),
            artifacts,
            imports,
            holds: DeviceHolds::default(),
            workspace,
            claims: StorageClaims::default(),
            probe: crate::support::OracleProbe::new(
                &json!({"availableBytes": 8_u64 * 1024 * 1024 * 1024}),
            ),
            imported,
            state: root.join("state"),
            root,
            calls,
            job_ids: [String::new(), String::new()],
            copy_project: String::new(),
            copy_root: PathBuf::new(),
            copy_revision: String::new(),
            patch_job,
            patch_source,
        };
        let revision = sha256_hex(
            format!(
                "profileVersion\t{PROFILE}\nhead\tabsent\nindex\tabsent\nfile\t{INDEX}\t{}\n",
                sha256_hex(b"@Entry\n")
            )
            .as_bytes(),
        );
        let isolate = owners.submit(
            "isolate",
            "workspace.prepare-isolated-copy",
            json!({
                "projectRef": PROJECT, "allowedFileGlobs": ["entry/src/main/ets/**"],
                "expectedWorkspaceRevision": revision,
            }),
        );
        let publisher = owners.publisher();
        let isolated = owners
            .runner(Some(&publisher))
            .handle(json!({"jobId": isolate}).as_object().unwrap())
            .unwrap();
        assert_eq!(isolated["state"], "succeeded", "{isolated}");
        assert_eq!(
            isolated["sessionPublication"]["state"], "published",
            "{isolated}"
        );
        let artifact = owners.result(&isolate)["artifacts"]
            .as_array()
            .unwrap()
            .iter()
            .find(|row| row["name"] == "isolated-workspace.json")
            .unwrap()["artifactId"]
            .as_str()
            .unwrap()
            .to_owned();
        let receipt: Value = serde_json::from_slice(
            &fs::read(owners.root.join("artifacts").join(&isolate).join(artifact)).unwrap(),
        )
        .unwrap();
        let copy = receipt["projectRef"].as_str().unwrap();
        owners.copy_project = copy.to_owned();
        owners.copy_root = owners
            .root
            .join("evolution-workspaces")
            .join(receipt["workspaceId"].as_str().unwrap())
            .join("workspace");
        owners.copy_revision = receipt["workspaceRevision"].as_str().unwrap().to_owned();
        for (index, label, operation, inputs) in [
            (
                0,
                "build",
                "workspace.build-openharmony",
                json!({"projectRef": copy, "buildPresetRef": "fixture-build"}),
            ),
            (
                1,
                "tests",
                "workspace.run-tests",
                json!({"projectRef": copy, "testPresetRef": "fixture-tests"}),
            ),
        ] {
            let job = owners.submit(label, operation, inputs);
            let terminal = owners
                .runner(None)
                .handle(json!({"jobId": job}).as_object().unwrap())
                .unwrap();
            assert_eq!(terminal["state"], "succeeded", "{terminal}");
            let mut value = owners.record(&job);
            assert_eq!(
                value["admissionEvidence"]["kind"], "runtimeCapability",
                "{value}"
            );
            assert!(value["recoveryAction"].is_null());
            assert!(value["recoveryStepID"].is_null());
            assert!(value["recoveryIntentEventID"].is_null());
            value["sessionPublicationRecord"] = json!({
                "sessionID": format!("session-{job}"), "catalogDigest": value["catalogDigest"],
                "policyGeneration": "0", "root": {"path": "", "device": "0", "inode": "0", "volumeIdentity": ""},
                "relativeSessionPath": "", "claims": [], "phase": "awaitingStorage",
                "failure": {"code": "sourceIntegrityFailed", "certainty": "confirmed", "detail": "isolated historical publisher fixture"},
            });
            let record = JobRecord::decode(&serde_json::to_vec(&value).unwrap()).unwrap();
            owners.jobs().persist(&record, &now().unwrap()).unwrap();
            owners.job_ids[index] = job;
        }
        assert_eq!(owners.calls.load(Ordering::SeqCst), 2);
        owners
    }

    pub fn jobs(&self) -> &JobStore {
        self.jobs.as_ref().unwrap()
    }
    pub fn run_patch(&self) -> (String, Value, Value) {
        let binding = |intent: &ImportIntent| -> Result<ImportBinding, WireError> {
            Ok(ImportBinding {
                target_id: intent.target_id.clone(),
                binding_revision: None,
                stable_identity_sha256: None,
            })
        };
        let begun = self.imports.handle_resource(
            "artifact.import.begin",
            json!({"schemaVersion": "arkdeck.import-intent/1", "importRequestId": "cached-plan-patch",
                "kind": "workspace-patch", "targetId": "workspace-host", "bindingRevision": "1",
                "deviceProfile": null, "name": "fix.patch", "byteCount": PATCH.len().to_string(),
                "sha256": sha256_hex(PATCH)}).as_object().unwrap(),
            &now().unwrap(), false, binding,
        ).unwrap();
        let id = begun["importId"].as_str().unwrap();
        self.imports.handle_resource(
            "artifact.import.append",
            json!({"importId": id, "generation": "1", "offset": "0", "byteCount": PATCH.len().to_string(),
                "sha256": sha256_hex(PATCH), "base64": encode_import_chunk(PATCH).unwrap()}).as_object().unwrap(),
            &now().unwrap(), false, binding,
        ).unwrap();
        let imported = self
            .imports
            .commit(
                json!({"importId": id, "generation": "1"})
                    .as_object()
                    .unwrap(),
                &now().unwrap(),
                false,
                &self.artifacts,
                1024 * 1024,
                binding,
            )
            .unwrap();
        assert_eq!(imported["state"], "committed");
        assert_eq!(imported["receipt"]["artifactDigest"], sha256_hex(PATCH));
        assert_eq!(imported["receipt"]["byteCount"], PATCH.len().to_string());
        let job = self.submit(
            "apply",
            "workspace.apply-patch",
            json!({
                "projectRef": self.copy_project,
                "patchArtifactRef": imported["receipt"]["lease"],
                "allowedFileGlobs": [INDEX], "expectedWorkspaceRevision": self.copy_revision,
            }),
        );
        let original_plan = self.plan_job(&job).unwrap();
        *self.patch_job.lock().unwrap() = Some(job.clone());
        let publisher = self.publisher();
        let status = self
            .runner(Some(&publisher))
            .handle(json!({"jobId": job}).as_object().unwrap())
            .unwrap();
        (job, status, original_plan)
    }
    pub fn plan_job(&self, job: &str) -> Result<Value, (String, String)> {
        let mut request = self.record(job)["request"].clone();
        request.as_object_mut().unwrap().remove("authorization");
        self.planner()
            .plan(&serde_json::to_vec(&request).unwrap())
            .map_err(|refusal| (refusal.code.to_owned(), refusal.message))
    }
    pub fn patch_source(&self) -> Value {
        self.patch_source.lock().unwrap().clone().unwrap()
    }
    pub fn isolated_index(&self) -> PathBuf {
        self.copy_root.join(INDEX)
    }
    pub fn manifest(&self, job: &str) -> Value {
        let record = self.record(job);
        serde_json::from_slice(
            &fs::read(
                self.root
                    .join("Sessions")
                    .join(
                        record["sessionPublicationRecord"]["relativeSessionPath"]
                            .as_str()
                            .unwrap(),
                    )
                    .join("manifest.json"),
            )
            .unwrap(),
        )
        .unwrap()
    }
    fn authority(&self) -> MutationAuthority<'_> {
        MutationAuthority {
            default_root: &self.state,
            sessions: Some(&self.sessions),
            capabilities: &self.capabilities,
            holds: &self.holds,
        }
    }
    fn planner(&self) -> JobPlanner<'_> {
        JobPlanner {
            artifacts: Some(&self.artifacts),
            imports: Some(&self.imports),
            analyzer: None,
            state_root: &self.state,
            hdc: None,
            workspace: Some(&self.workspace),
        }
    }
    fn submit(&self, label: &str, operation: &str, inputs: Value) -> String {
        let document = json!({"documentType": "runtime-operation-request", "schemaVersion": "1.0.0",
            "requestId": format!("request-{label}"), "idempotencyKey": format!("idempotency-{label}"),
            "target": {"targetId": "workspace-host"}, "operation": {"id": operation, "version": 1},
            "inputs": inputs, "requestedOutputs": ["derivedArtifacts"]});
        let admitter = JobAdmitter {
            planner: self.planner(),
            jobs: self.jobs(),
            now,
            authority: Some(self.authority()),
        };
        let answer = admitter
            .handle(
                json!({"requestJson": document.to_string()})
                    .as_object()
                    .unwrap(),
            )
            .unwrap_or_else(|refusal| panic!("{}: {}", refusal.code, refusal.message));
        answer["jobId"].as_str().unwrap().to_owned()
    }
    fn publisher(&self) -> SessionPublisher<'_> {
        SessionPublisher {
            sessions: &self.sessions,
            claims: &self.claims,
            probe: &self.probe,
        }
    }
    fn runner<'a>(&'a self, sessions: Option<&'a SessionPublisher<'a>>) -> JobRunner<'a> {
        JobRunner {
            mutation: Some(MutationExecution {
                authority: self.authority(),
                state_root: &self.state,
            }),
            jobs: self.jobs(),
            artifacts: &self.artifacts,
            imports: Some(&self.imports),
            analyzer: None,
            quota: 8 * 1024 * 1024 * 1024,
            home: "C:/nonexistent-home",
            now,
            precise_now: now,
            sessions,
            cancellation: None,
            after_commit: None,
            hdc: None,
            workspace: Some(&self.workspace),
        }
    }
    pub fn reconcile(&self, job: &str) -> Result<Value, WireError> {
        self.reconcile_with_context(job, true)
    }
    pub fn reconcile_with_context(&self, job: &str, context: bool) -> Result<Value, WireError> {
        let publisher = self.publisher();
        let runner = self.runner(Some(&publisher));
        JobReconciler {
            jobs: self.jobs(),
            artifacts: &self.artifacts,
            imports: Some(&self.imports),
            now,
            sessions: Some(&publisher),
            hdc: None,
            capabilities: Some(&self.capabilities),
            runner: context.then_some(&runner),
        }
        .handle(json!({"jobId": job}).as_object().unwrap())
    }
    pub fn result(&self, job: &str) -> Value {
        JobResultReader {
            jobs: self.jobs(),
            artifacts: &self.artifacts,
        }
        .handle("job.result", json!({"jobId": job}).as_object().unwrap())
        .unwrap()
    }
    pub fn inspection(&self) -> Result<Value, WireError> {
        self.imports.lifecycle_resource(
            &self.artifacts,
            self.jobs(),
            "artifact.import.inspection",
            json!({"importId": self.imported["importId"]})
                .as_object()
                .unwrap(),
            &now().unwrap(),
        )
    }
    pub fn directory(&self, job: &str) -> PathBuf {
        self.root.join("state/jobs").join(job)
    }
    pub fn record(&self, job: &str) -> Value {
        self.jobs().read_snapshot(job).unwrap().value().unwrap()
    }
    pub fn reopen(&mut self) {
        drop(self.jobs.take());
        self.jobs = Some(JobStore::open_owner(&self.root.join("state")).unwrap());
    }
}

impl Drop for Owners {
    fn drop(&mut self) {
        drop(self.jobs.take());
        let _ = fs::remove_dir_all(&self.root);
    }
}
