#!/usr/bin/env python3
"""TEST-INT-UD-R2-DIAG-001 — synthetic-only contract for diagnose.py.

Implements the readiness r1 verification plan: 32 pinned case families plus
2 mandatory audit tests (additions are allowed, removals are not). Every
fixture is a synthetic byte sequence generated by this file in a temporary
directory outside the repository; no test reads any real raw. The CLI is
exercised in-process (no subprocess, socket, or network use anywhere in
this file).
"""

import ast
import contextlib
import hashlib
import io
import json
import os
import shutil
import sys
import tempfile
import unicodedata
import unittest

_SCRIPT_DIR = os.path.dirname(os.path.realpath(__file__))
if _SCRIPT_DIR not in sys.path:
    sys.path.insert(0, _SCRIPT_DIR)

import diagnose

REPO_ROOT = os.path.realpath(os.path.join(_SCRIPT_DIR, os.pardir, os.pardir))

# Readiness r1 pins, duplicated here on purpose so a drifted constant in
# diagnose.py cannot vouch for itself.
PINNED_REDACT_PY_SHA256 = (
    "938cc117da97304b5ede66ff55c84dd9ce0a987600d4a1ecec2c3e01351f53e1"
)
PINNED_ALGORITHM_MANIFEST_SHA256 = (
    "a75778fdf525050c4c0bcf11579e5f09f99a6fa70697bcf79026656a71f20185"
)

DUMMY_SHA256 = "0" * 64

# Independent copy of the closed report schema (key sets only), so the
# closed-key test does not trust the tool's own validator.
EXPECTED_TOP_KEYS = {
    "schema",
    "tool",
    "policyRefs",
    "input",
    "byteHistogram",
    "utf8Structure",
    "codepointPolicy",
    "redactorEquivalent",
}
EXPECTED_TOOL_KEYS = {"name", "sha256"}
EXPECTED_POLICY_REFS_KEYS = {"redactPySha256", "algorithmManifestSha256"}
EXPECTED_INPUT_KEYS = {
    "expectedSha256",
    "measuredSha256",
    "expectedLength",
    "measuredLength",
}
EXPECTED_HISTOGRAM_KEYS = {
    "nul",
    "tab",
    "lf",
    "cr",
    "otherC0",
    "asciiPrintable",
    "del",
    "lead2",
    "lead3",
    "lead4",
    "continuation",
    "invalidByte",
}
EXPECTED_UTF8_KEYS = {
    "decodable",
    "invalidSequenceCount",
    "invalidByteCount",
    "firstInvalidOffset",
    "lastInvalidOffset",
    "classCounts",
    "runs",
    "runsTruncated",
    "decileCounts",
    "tailConcentrated",
}
EXPECTED_POLICY_KEYS = {
    "evaluated",
    "nfc",
    "combiningMarkCount",
    "violationCount",
    "firstViolationByteOffset",
    "lastViolationByteOffset",
    "classCounts",
    "runs",
    "runsTruncated",
    "decileCounts",
    "tailConcentrated",
}
EXPECTED_EQUIVALENT_KEYS = {"errorName", "errorCode"}
EXPECTED_RUN_KEYS = {"offset", "length", "class"}
EXPECTED_UTF8_CLASSES = {
    "STRAY_CONTINUATION",
    "INVALID_LEAD",
    "OVERLONG",
    "SURROGATE_ENCODING",
    "OUT_OF_RANGE",
    "TRUNCATED_SEQUENCE_MID",
    "TRUNCATED_SEQUENCE_EOF",
}
EXPECTED_POLICY_CLASSES = {
    "DEL_7F",
    "CONTROL_C0",
    "CATEGORY_CC",
    "CATEGORY_CF",
    "CATEGORY_CS",
    "CATEGORY_CO",
    "CATEGORY_CN",
    "CONFUSABLE_NAME_PREFIX",
}
EXPECTED_STRING_WHITELIST = (
    {
        "arkdeck-ud-raw-diagnosis-1.0.0",
        "arkdeck-ud-raw-diagnosis",
        "NONE",
        "INVALID_UTF8",
        "INVALID_UNICODE",
    }
    | EXPECTED_UTF8_CLASSES
    | EXPECTED_POLICY_CLASSES
)

# The readiness r1 verification matrix: 32 case families + 2 mandatory
# audits. This manifest is asserted against the actual test methods so a
# family cannot be dropped silently.
PINNED_MATRIX = (
    "test_gate_01_hash_mismatch_rejected",
    "test_gate_02_length_mismatch_rejected",
    "test_gate_03_oversized_input_rejected",
    "test_gate_04_symlink_input_rejected",
    "test_gate_05_non_regular_file_rejected",
    "test_gate_06_repository_path_rejected",
    "test_gate_07_expected_length_usage_error",
    "test_clean_08_pure_ascii_lf",
    "test_clean_09_multibyte_2_3_4_with_crlf",
    "test_clean_10_cr_only_line_endings",
    "test_utf8_11_truncated_multibyte_eof",
    "test_utf8_12_truncated_multibyte_mid",
    "test_utf8_13_stray_continuation",
    "test_utf8_14_invalid_lead_fe_ff",
    "test_utf8_15_overlong_c0_af",
    "test_utf8_16_surrogate_encoding",
    "test_utf8_17_out_of_range",
    "test_policy_18_nul",
    "test_policy_19_tab_and_other_c0_with_line_ending_exemption",
    "test_policy_20_del_7f",
    "test_policy_21_category_cf_zero_width_space",
    "test_policy_22_category_co_private_use",
    "test_policy_23_category_cn_noncharacter",
    "test_policy_24_confusable_name_prefix",
    "test_policy_25_non_nfc_combining_sequence",
    "test_distribution_26_tail_concentrated",
    "test_distribution_27_uniform_spread_not_tail_concentrated",
    "test_output_28_closed_key_schema",
    "test_output_29_unknown_key_injection_rejected",
    "test_output_30_free_string_value_injection_rejected",
    "test_output_31_deterministic_identical_bytes",
    "test_output_32_runs_truncated_over_64_counts_exact",
    "test_audit_33_ast_no_shell_no_network_no_write",
    "test_audit_34_policy_refs_match_repository_redactor",
)


def _sha256_hex(data):
    return hashlib.sha256(data).hexdigest()


def _collect_import_roots(tree):
    plain_roots = set()
    from_roots = set()
    from_nodes = 0
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                plain_roots.add(alias.name.split(".")[0])
        elif isinstance(node, ast.ImportFrom):
            from_nodes += 1
            if node.module:
                from_roots.add(node.module.split(".")[0])
    return plain_roots, from_roots, from_nodes


def _collect_attributes_of(tree, base_name):
    attributes = set()
    for node in ast.walk(tree):
        if (
            isinstance(node, ast.Attribute)
            and isinstance(node.value, ast.Name)
            and node.value.id == base_name
        ):
            attributes.add(node.attr)
    return attributes


def _collect_os_path_attributes(tree):
    attributes = set()
    for node in ast.walk(tree):
        if (
            isinstance(node, ast.Attribute)
            and isinstance(node.value, ast.Attribute)
            and isinstance(node.value.value, ast.Name)
            and node.value.value.id == "os"
            and node.value.attr == "path"
        ):
            attributes.add(node.attr)
    return attributes


def _collect_called_names(tree):
    names = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Call) and isinstance(node.func, ast.Name):
            names.add(node.func.id)
    return names


class DiagnoseContractTest(unittest.TestCase):
    maxDiff = None

    def setUp(self):
        candidate = tempfile.mkdtemp(prefix="ud-diag-")
        if os.path.realpath(candidate).startswith(REPO_ROOT + os.sep):
            shutil.rmtree(candidate, ignore_errors=True)
            candidate = tempfile.mkdtemp(prefix="ud-diag-", dir="/tmp")
        self.tmp = candidate
        self.addCleanup(shutil.rmtree, candidate, ignore_errors=True)

    # ---- helpers -------------------------------------------------------

    def write_fixture(self, name, data):
        path = os.path.join(self.tmp, name)
        with open(path, "wb") as handle:
            handle.write(data)
        return path

    def run_cli(self, argv):
        stdout = io.StringIO()
        stderr = io.StringIO()
        with contextlib.redirect_stdout(stdout), contextlib.redirect_stderr(
            stderr
        ):
            try:
                code = diagnose.main(argv)
            except SystemExit as exc:
                code = exc.code
        return code, stdout.getvalue(), stderr.getvalue()

    def run_cli_on_bytes(self, data, name="fixture.bin"):
        path = self.write_fixture(name, data)
        return self.run_cli(
            [
                "--input",
                path,
                "--expected-input-sha256",
                _sha256_hex(data),
                "--expected-length",
                str(len(data)),
            ]
        )

    def diagnose_file(self, data, name="fixture.bin"):
        code, stdout, stderr = self.run_cli_on_bytes(data, name=name)
        self.assertEqual(code, 0)
        self.assertEqual(stderr, "")
        self.assertTrue(stdout.endswith("\n"))
        self.assertEqual(stdout.count("\n"), 1)
        report = json.loads(stdout)
        expected_decodable = True
        try:
            data.decode("utf-8")
        except UnicodeDecodeError:
            expected_decodable = False
        self.assertEqual(
            report["utf8Structure"]["decodable"], expected_decodable
        )
        return report

    def assert_stable_error(self, code, stdout, stderr, name):
        self.assertEqual(code, diagnose.ERROR_CODES[name])
        self.assertEqual(stdout, "")
        self.assertEqual(stderr, f"diagnose: {name}\n")

    def utf8_runs(self, report):
        return [
            (entry["offset"], entry["length"], entry["class"])
            for entry in report["utf8Structure"]["runs"]
        ]

    def policy_runs(self, report):
        return [
            (entry["offset"], entry["length"], entry["class"])
            for entry in report["codepointPolicy"]["runs"]
        ]

    def assert_clean_policy(self, report, nfc=True):
        policy = report["codepointPolicy"]
        self.assertTrue(policy["evaluated"])
        self.assertEqual(policy["nfc"], nfc)
        self.assertEqual(policy["violationCount"], 0)
        self.assertIsNone(policy["firstViolationByteOffset"])
        self.assertIsNone(policy["lastViolationByteOffset"])
        self.assertEqual(policy["runs"], [])

    def assert_equivalent(self, report, name, code):
        self.assertEqual(
            report["redactorEquivalent"], {"errorName": name, "errorCode": code}
        )

    def tampered_run(self, data, tamper):
        """Run the real CLI path with the built report tampered post-build."""
        original = diagnose.diagnose_bytes

        def wrapper(*args, **kwargs):
            report = original(*args, **kwargs)
            tamper(report)
            return report

        diagnose.diagnose_bytes = wrapper
        try:
            return self.run_cli_on_bytes(data, name="tampered.bin")
        finally:
            diagnose.diagnose_bytes = original

    # ---- input gates (7) ----------------------------------------------

    def test_gate_01_hash_mismatch_rejected(self):
        data = b"clean\n"
        path = self.write_fixture("hash-mismatch.bin", data)
        wrong = _sha256_hex(b"different")
        code, stdout, stderr = self.run_cli(
            [
                "--input",
                path,
                "--expected-input-sha256",
                wrong,
                "--expected-length",
                str(len(data)),
            ]
        )
        self.assert_stable_error(code, stdout, stderr, "INPUT_HASH_MISMATCH")
        malformed = _sha256_hex(data).upper()
        code, stdout, stderr = self.run_cli(
            [
                "--input",
                path,
                "--expected-input-sha256",
                malformed,
                "--expected-length",
                str(len(data)),
            ]
        )
        self.assert_stable_error(code, stdout, stderr, "INPUT_HASH_MISMATCH")

    def test_gate_02_length_mismatch_rejected(self):
        data = b"clean\n"
        path = self.write_fixture("length-mismatch.bin", data)
        code, stdout, stderr = self.run_cli(
            [
                "--input",
                path,
                "--expected-input-sha256",
                _sha256_hex(data),
                "--expected-length",
                str(len(data) + 1),
            ]
        )
        self.assert_stable_error(code, stdout, stderr, "INPUT_HASH_MISMATCH")

    def test_gate_03_oversized_input_rejected(self):
        path = self.write_fixture("oversized.bin", b"")
        oversize = diagnose.INPUT_BYTES_LIMIT + 1
        os.truncate(path, oversize)
        code, stdout, stderr = self.run_cli(
            [
                "--input",
                path,
                "--expected-input-sha256",
                DUMMY_SHA256,
                "--expected-length",
                str(oversize),
            ]
        )
        self.assert_stable_error(code, stdout, stderr, "INPUT_TOO_LARGE")

    def test_gate_04_symlink_input_rejected(self):
        data = b"clean\n"
        target = self.write_fixture("symlink-target.bin", data)
        link = os.path.join(self.tmp, "symlink-input.bin")
        os.symlink(target, link)
        code, stdout, stderr = self.run_cli(
            [
                "--input",
                link,
                "--expected-input-sha256",
                _sha256_hex(data),
                "--expected-length",
                str(len(data)),
            ]
        )
        self.assert_stable_error(code, stdout, stderr, "IO_ERROR")

    def test_gate_05_non_regular_file_rejected(self):
        for candidate in ("/dev/null", self.tmp):
            code, stdout, stderr = self.run_cli(
                [
                    "--input",
                    candidate,
                    "--expected-input-sha256",
                    DUMMY_SHA256,
                    "--expected-length",
                    "1",
                ]
            )
            self.assert_stable_error(code, stdout, stderr, "IO_ERROR")

    def test_gate_06_repository_path_rejected(self):
        inside = os.path.join(
            REPO_ROOT, "scripts", "ui_dump_diagnosis", "diagnose.py"
        )
        self.assertTrue(os.path.isfile(inside))
        code, stdout, stderr = self.run_cli(
            [
                "--input",
                inside,
                "--expected-input-sha256",
                DUMMY_SHA256,
                "--expected-length",
                "1",
            ]
        )
        # IO_ERROR, not INPUT_HASH_MISMATCH: the path policy fires before
        # any byte of a repository file is read or hashed.
        self.assert_stable_error(code, stdout, stderr, "IO_ERROR")

    def test_gate_07_expected_length_usage_error(self):
        data = b"clean\n"
        path = self.write_fixture("usage.bin", data)
        for bad_length in ("0", "-5", "abc", "1.5", ""):
            code, stdout, stderr = self.run_cli(
                [
                    "--input",
                    path,
                    "--expected-input-sha256",
                    _sha256_hex(data),
                    "--expected-length",
                    bad_length,
                ]
            )
            self.assertEqual(code, 2)
            self.assertEqual(stdout, "")
            self.assertIn("usage", stderr)

    # ---- clean positives (3) ------------------------------------------

    def test_clean_08_pure_ascii_lf(self):
        data = b"hello world\nsecond line\n"
        report = self.diagnose_file(data)
        self.assertEqual(
            report["input"],
            {
                "expectedSha256": _sha256_hex(data),
                "measuredSha256": _sha256_hex(data),
                "expectedLength": len(data),
                "measuredLength": len(data),
            },
        )
        histogram = report["byteHistogram"]
        self.assertEqual(histogram["asciiPrintable"], 22)
        self.assertEqual(histogram["lf"], 2)
        self.assertEqual(sum(histogram.values()), len(data))
        structure = report["utf8Structure"]
        self.assertTrue(structure["decodable"])
        self.assertEqual(structure["invalidSequenceCount"], 0)
        self.assertEqual(structure["invalidByteCount"], 0)
        self.assertIsNone(structure["firstInvalidOffset"])
        self.assertIsNone(structure["lastInvalidOffset"])
        self.assertEqual(structure["decileCounts"], [0] * 10)
        self.assertFalse(structure["tailConcentrated"])
        self.assert_clean_policy(report)
        self.assert_equivalent(report, "NONE", None)

    def test_clean_09_multibyte_2_3_4_with_crlf(self):
        data = "caf\u00e9\r\n\u20ac\r\n\U00010348\r\n".encode("utf-8")
        self.assertEqual(len(data), 18)
        report = self.diagnose_file(data)
        histogram = report["byteHistogram"]
        self.assertEqual(histogram["asciiPrintable"], 3)
        self.assertEqual(histogram["lead2"], 1)
        self.assertEqual(histogram["lead3"], 1)
        self.assertEqual(histogram["lead4"], 1)
        self.assertEqual(histogram["continuation"], 6)
        self.assertEqual(histogram["cr"], 3)
        self.assertEqual(histogram["lf"], 3)
        self.assertEqual(sum(histogram.values()), len(data))
        self.assertTrue(report["utf8Structure"]["decodable"])
        self.assertEqual(report["utf8Structure"]["invalidSequenceCount"], 0)
        self.assert_clean_policy(report)
        self.assert_equivalent(report, "NONE", None)

    def test_clean_10_cr_only_line_endings(self):
        data = b"line one\rline two\r"
        report = self.diagnose_file(data)
        histogram = report["byteHistogram"]
        self.assertEqual(histogram["cr"], 2)
        self.assertEqual(histogram["lf"], 0)
        self.assertEqual(histogram["asciiPrintable"], 16)
        self.assertEqual(report["utf8Structure"]["invalidSequenceCount"], 0)
        self.assert_clean_policy(report)
        self.assert_equivalent(report, "NONE", None)

    # ---- UTF-8 structure negatives (7) --------------------------------

    def test_utf8_11_truncated_multibyte_eof(self):
        data = b"abc\xe2\x82"
        report = self.diagnose_file(data)
        structure = report["utf8Structure"]
        self.assertFalse(structure["decodable"])
        self.assertEqual(
            self.utf8_runs(report), [(3, 2, "TRUNCATED_SEQUENCE_EOF")]
        )
        self.assertEqual(structure["invalidSequenceCount"], 1)
        self.assertEqual(structure["invalidByteCount"], 2)
        self.assertEqual(structure["firstInvalidOffset"], 3)
        self.assertEqual(structure["lastInvalidOffset"], 3)
        self.assertEqual(
            structure["classCounts"]["TRUNCATED_SEQUENCE_EOF"], 1
        )
        policy = report["codepointPolicy"]
        self.assertFalse(policy["evaluated"])
        self.assertIsNone(policy["nfc"])
        self.assertEqual(policy["violationCount"], 0)
        self.assertEqual(policy["runs"], [])
        self.assert_equivalent(report, "INVALID_UTF8", 26)

    def test_utf8_12_truncated_multibyte_mid(self):
        data = b"a\xe2\x82b"
        report = self.diagnose_file(data)
        self.assertEqual(
            self.utf8_runs(report), [(1, 2, "TRUNCATED_SEQUENCE_MID")]
        )
        self.assertEqual(report["utf8Structure"]["invalidByteCount"], 2)
        self.assertEqual(report["byteHistogram"]["asciiPrintable"], 2)
        self.assertEqual(report["byteHistogram"]["lead3"], 1)
        self.assertEqual(report["byteHistogram"]["continuation"], 1)
        self.assert_equivalent(report, "INVALID_UTF8", 26)

    def test_utf8_13_stray_continuation(self):
        data = b"a\x80b"
        report = self.diagnose_file(data)
        self.assertEqual(self.utf8_runs(report), [(1, 1, "STRAY_CONTINUATION")])
        self.assertEqual(
            report["utf8Structure"]["classCounts"]["STRAY_CONTINUATION"], 1
        )
        self.assert_equivalent(report, "INVALID_UTF8", 26)

    def test_utf8_14_invalid_lead_fe_ff(self):
        data = b"a\xfe\xffb"
        report = self.diagnose_file(data)
        self.assertEqual(
            self.utf8_runs(report),
            [(1, 1, "INVALID_LEAD"), (2, 1, "INVALID_LEAD")],
        )
        self.assertEqual(report["utf8Structure"]["invalidSequenceCount"], 2)
        self.assertEqual(report["byteHistogram"]["invalidByte"], 2)
        self.assert_equivalent(report, "INVALID_UTF8", 26)

    def test_utf8_15_overlong_c0_af(self):
        data = b"a\xc0\xafb"
        report = self.diagnose_file(data)
        self.assertEqual(self.utf8_runs(report), [(1, 2, "OVERLONG")])
        self.assertEqual(report["byteHistogram"]["lead2"], 1)
        self.assertEqual(report["byteHistogram"]["continuation"], 1)
        self.assert_equivalent(report, "INVALID_UTF8", 26)
        overlong_three = self.diagnose_file(
            b"a\xe0\x80\x80b", name="overlong3.bin"
        )
        self.assertEqual(self.utf8_runs(overlong_three), [(1, 3, "OVERLONG")])

    def test_utf8_16_surrogate_encoding(self):
        data = b"a\xed\xa0\x80b"
        report = self.diagnose_file(data)
        self.assertEqual(
            self.utf8_runs(report), [(1, 3, "SURROGATE_ENCODING")]
        )
        self.assertEqual(report["utf8Structure"]["invalidByteCount"], 3)
        self.assert_equivalent(report, "INVALID_UTF8", 26)

    def test_utf8_17_out_of_range(self):
        data = b"a\xf4\x90\x80\x80b"
        report = self.diagnose_file(data)
        self.assertEqual(self.utf8_runs(report), [(1, 4, "OUT_OF_RANGE")])
        self.assertEqual(report["utf8Structure"]["invalidByteCount"], 4)
        self.assert_equivalent(report, "INVALID_UTF8", 26)
        high_lead = self.diagnose_file(
            b"\xf5\x80\x80\x80", name="out-of-range-f5.bin"
        )
        self.assertEqual(self.utf8_runs(high_lead), [(0, 4, "OUT_OF_RANGE")])

    # ---- codepoint policy negatives (8) -------------------------------

    def test_policy_18_nul(self):
        data = b"a\x00b\n"
        report = self.diagnose_file(data)
        self.assertTrue(report["utf8Structure"]["decodable"])
        self.assertEqual(self.policy_runs(report), [(1, 1, "CONTROL_C0")])
        policy = report["codepointPolicy"]
        self.assertEqual(policy["violationCount"], 1)
        self.assertEqual(policy["firstViolationByteOffset"], 1)
        self.assertEqual(policy["lastViolationByteOffset"], 1)
        self.assertEqual(report["byteHistogram"]["nul"], 1)
        self.assert_equivalent(report, "INVALID_UNICODE", 27)

    def test_policy_19_tab_and_other_c0_with_line_ending_exemption(self):
        data = b"a\tb\x01c\r\nd\n"
        report = self.diagnose_file(data)
        self.assertEqual(
            self.policy_runs(report),
            [(1, 1, "CONTROL_C0"), (3, 1, "CONTROL_C0")],
        )
        policy = report["codepointPolicy"]
        # Exactly two violations: the LF/CR bytes in the same file are
        # exempt, mirroring allow_line_endings=True in the redactor.
        self.assertEqual(policy["violationCount"], 2)
        self.assertEqual(policy["classCounts"]["CONTROL_C0"], 2)
        histogram = report["byteHistogram"]
        self.assertEqual(histogram["tab"], 1)
        self.assertEqual(histogram["otherC0"], 1)
        self.assertEqual(histogram["cr"], 1)
        self.assertEqual(histogram["lf"], 2)
        self.assert_equivalent(report, "INVALID_UNICODE", 27)
        lone_line_endings = self.diagnose_file(
            b"\n\r\r\n", name="line-endings-only.bin"
        )
        self.assertEqual(
            lone_line_endings["codepointPolicy"]["violationCount"], 0
        )
        self.assert_equivalent(lone_line_endings, "NONE", None)

    def test_policy_20_del_7f(self):
        data = b"a\x7fb\n"
        report = self.diagnose_file(data)
        self.assertEqual(self.policy_runs(report), [(1, 1, "DEL_7F")])
        self.assertEqual(report["byteHistogram"]["del"], 1)
        self.assert_equivalent(report, "INVALID_UNICODE", 27)

    def test_policy_21_category_cf_zero_width_space(self):
        self.assertEqual(unicodedata.category("\u200b"), "Cf")
        data = "a\u200bb\n".encode("utf-8")
        report = self.diagnose_file(data)
        self.assertEqual(self.policy_runs(report), [(1, 3, "CATEGORY_CF")])
        self.assert_equivalent(report, "INVALID_UNICODE", 27)

    def test_policy_22_category_co_private_use(self):
        self.assertEqual(unicodedata.category("\ue000"), "Co")
        data = "a\ue000b\n".encode("utf-8")
        report = self.diagnose_file(data)
        self.assertEqual(self.policy_runs(report), [(1, 3, "CATEGORY_CO")])
        self.assert_equivalent(report, "INVALID_UNICODE", 27)

    def test_policy_23_category_cn_noncharacter(self):
        self.assertEqual(unicodedata.category("\uffff"), "Cn")
        data = "a\uffffb\n".encode("utf-8")
        report = self.diagnose_file(data)
        self.assertEqual(self.policy_runs(report), [(1, 3, "CATEGORY_CN")])
        self.assert_equivalent(report, "INVALID_UNICODE", 27)

    def test_policy_24_confusable_name_prefix(self):
        self.assertTrue(unicodedata.name("\u0410").startswith("CYRILLIC "))
        cyrillic = "a\u0410b\n".encode("utf-8")
        report = self.diagnose_file(cyrillic)
        self.assertEqual(
            self.policy_runs(report), [(1, 2, "CONFUSABLE_NAME_PREFIX")]
        )
        self.assert_equivalent(report, "INVALID_UNICODE", 27)
        self.assertTrue(unicodedata.name("\uff21").startswith("FULLWIDTH "))
        fullwidth = "a\uff21b\n".encode("utf-8")
        report = self.diagnose_file(fullwidth, name="fullwidth.bin")
        self.assertEqual(
            self.policy_runs(report), [(1, 3, "CONFUSABLE_NAME_PREFIX")]
        )
        self.assert_equivalent(report, "INVALID_UNICODE", 27)

    def test_policy_25_non_nfc_combining_sequence(self):
        data = "e\u0301\n".encode("utf-8")
        self.assertNotEqual(
            unicodedata.normalize("NFC", data.decode("utf-8")),
            data.decode("utf-8"),
        )
        report = self.diagnose_file(data)
        structure = report["utf8Structure"]
        self.assertTrue(structure["decodable"])
        self.assertEqual(structure["invalidSequenceCount"], 0)
        policy = report["codepointPolicy"]
        self.assertTrue(policy["evaluated"])
        self.assertFalse(policy["nfc"])
        self.assertEqual(policy["combiningMarkCount"], 1)
        # U+0301 is Mn and not itself a violation: only the non-NFC form
        # drives the redactor-equivalent INVALID_UNICODE conclusion.
        self.assertEqual(policy["violationCount"], 0)
        self.assert_equivalent(report, "INVALID_UNICODE", 27)

    # ---- distribution and summary (2) ---------------------------------

    def test_distribution_26_tail_concentrated(self):
        structural = b"a" * 90 + b"\x80" * 10
        report = self.diagnose_file(structural)
        structure = report["utf8Structure"]
        self.assertEqual(structure["invalidSequenceCount"], 10)
        self.assertEqual(structure["decileCounts"], [0] * 9 + [10])
        self.assertTrue(structure["tailConcentrated"])
        self.assertEqual(structure["firstInvalidOffset"], 90)
        self.assertEqual(structure["lastInvalidOffset"], 99)
        self.assert_equivalent(report, "INVALID_UTF8", 26)
        decodable_tail = b"a" * 90 + b"\x00" * 10
        report = self.diagnose_file(decodable_tail, name="tail-nul.bin")
        policy = report["codepointPolicy"]
        self.assertEqual(policy["violationCount"], 10)
        self.assertEqual(policy["decileCounts"], [0] * 9 + [10])
        self.assertTrue(policy["tailConcentrated"])
        self.assert_equivalent(report, "INVALID_UNICODE", 27)

    def test_distribution_27_uniform_spread_not_tail_concentrated(self):
        buffer = bytearray(b"a" * 100)
        for decile in range(10):
            buffer[10 * decile + 5] = 0x00
        report = self.diagnose_file(bytes(buffer))
        policy = report["codepointPolicy"]
        self.assertEqual(policy["violationCount"], 10)
        self.assertEqual(policy["decileCounts"], [1] * 10)
        self.assertFalse(policy["tailConcentrated"])
        self.assert_equivalent(report, "INVALID_UNICODE", 27)
        buffer = bytearray(b"a" * 100)
        for decile in range(10):
            buffer[10 * decile + 5] = 0x80
        report = self.diagnose_file(bytes(buffer), name="uniform-cont.bin")
        structure = report["utf8Structure"]
        self.assertEqual(structure["invalidSequenceCount"], 10)
        self.assertEqual(structure["decileCounts"], [1] * 10)
        self.assertFalse(structure["tailConcentrated"])
        self.assert_equivalent(report, "INVALID_UTF8", 26)

    # ---- output discipline (5) ----------------------------------------

    def _assert_closed_string(self, value):
        self.assertTrue(
            value in EXPECTED_STRING_WHITELIST
            or (
                len(value) == 64
                and all(ch in "0123456789abcdef" for ch in value)
            ),
            f"free-form string escaped the value law: {value!r}",
        )

    def _walk_independent_value_law(self, value):
        if isinstance(value, dict):
            for key, item in value.items():
                self.assertIsInstance(key, str)
                self._walk_independent_value_law(item)
        elif isinstance(value, list):
            for item in value:
                self._walk_independent_value_law(item)
        elif isinstance(value, str):
            self._assert_closed_string(value)
        else:
            self.assertTrue(
                value is None or type(value) is bool or type(value) is int,
                f"non-closed value type: {value!r}",
            )

    def test_output_28_closed_key_schema(self):
        data = b"a\x00b\xe2\x82\n"
        report = self.diagnose_file(data)
        self.assertEqual(set(report), EXPECTED_TOP_KEYS)
        self.assertEqual(report["schema"], "arkdeck-ud-raw-diagnosis-1.0.0")
        self.assertEqual(set(report["tool"]), EXPECTED_TOOL_KEYS)
        self.assertEqual(report["tool"]["name"], "arkdeck-ud-raw-diagnosis")
        tool_path = os.path.join(
            REPO_ROOT, "scripts", "ui_dump_diagnosis", "diagnose.py"
        )
        with open(tool_path, "rb") as handle:
            self.assertEqual(report["tool"]["sha256"], _sha256_hex(handle.read()))
        self.assertEqual(set(report["policyRefs"]), EXPECTED_POLICY_REFS_KEYS)
        self.assertEqual(set(report["input"]), EXPECTED_INPUT_KEYS)
        self.assertEqual(set(report["byteHistogram"]), EXPECTED_HISTOGRAM_KEYS)
        self.assertEqual(set(report["utf8Structure"]), EXPECTED_UTF8_KEYS)
        self.assertEqual(set(report["codepointPolicy"]), EXPECTED_POLICY_KEYS)
        self.assertEqual(
            set(report["redactorEquivalent"]), EXPECTED_EQUIVALENT_KEYS
        )
        for entry in report["utf8Structure"]["runs"]:
            self.assertEqual(set(entry), EXPECTED_RUN_KEYS)
        for entry in report["codepointPolicy"]["runs"]:
            self.assertEqual(set(entry), EXPECTED_RUN_KEYS)
        self.assertEqual(
            set(report["utf8Structure"]["classCounts"]),
            EXPECTED_UTF8_CLASSES,
        )
        self.assertEqual(
            set(report["codepointPolicy"]["classCounts"]),
            EXPECTED_POLICY_CLASSES,
        )
        self._walk_independent_value_law(report)

    def test_output_29_unknown_key_injection_rejected(self):
        def add_unknown_top_key(report):
            report["unexpectedKey"] = 1

        code, stdout, stderr = self.tampered_run(
            b"clean\n", add_unknown_top_key
        )
        self.assert_stable_error(code, stdout, stderr, "SENSITIVE_OUTPUT")

        def add_unknown_nested_key(report):
            report["utf8Structure"]["contextWindow"] = 0

        code, stdout, stderr = self.tampered_run(
            b"clean\n", add_unknown_nested_key
        )
        self.assert_stable_error(code, stdout, stderr, "SENSITIVE_OUTPUT")

    def test_output_30_free_string_value_injection_rejected(self):
        def inject_free_string(report):
            report["input"]["measuredLength"] = "six bytes of text"

        code, stdout, stderr = self.tampered_run(b"clean\n", inject_free_string)
        self.assert_stable_error(code, stdout, stderr, "SENSITIVE_OUTPUT")

        def inject_free_class(report):
            report["utf8Structure"]["runs"][0]["class"] = "RAW BYTES HERE"

        code, stdout, stderr = self.tampered_run(b"a\x80b", inject_free_class)
        self.assert_stable_error(code, stdout, stderr, "SENSITIVE_OUTPUT")

        def inject_float(report):
            report["byteHistogram"]["nul"] = 0.0

        code, stdout, stderr = self.tampered_run(b"clean\n", inject_float)
        self.assert_stable_error(code, stdout, stderr, "SENSITIVE_OUTPUT")

    def test_output_31_deterministic_identical_bytes(self):
        data = b"a\x00b\xe2"
        first = self.run_cli_on_bytes(data, name="det-a.bin")
        second = self.run_cli_on_bytes(data, name="det-b.bin")
        self.assertEqual(first[0], 0)
        self.assertEqual(second[0], 0)
        self.assertEqual(
            first[1].encode("ascii"), second[1].encode("ascii")
        )
        canonical = (
            json.dumps(
                json.loads(first[1]),
                ensure_ascii=True,
                separators=(",", ":"),
                sort_keys=True,
            )
            + "\n"
        )
        self.assertEqual(first[1], canonical)

    def test_output_32_runs_truncated_over_64_counts_exact(self):
        data = b"a" * 10 + b"\x80" * 100 + b"z" * 10
        report = self.diagnose_file(data)
        structure = report["utf8Structure"]
        self.assertEqual(structure["invalidSequenceCount"], 100)
        self.assertEqual(structure["invalidByteCount"], 100)
        self.assertTrue(structure["runsTruncated"])
        self.assertEqual(len(structure["runs"]), 64)
        runs = self.utf8_runs(report)
        self.assertEqual(runs[0], (10, 1, "STRAY_CONTINUATION"))
        self.assertEqual(runs[31], (41, 1, "STRAY_CONTINUATION"))
        self.assertEqual(runs[32], (78, 1, "STRAY_CONTINUATION"))
        self.assertEqual(runs[63], (109, 1, "STRAY_CONTINUATION"))
        self.assertEqual(
            structure["classCounts"]["STRAY_CONTINUATION"], 100
        )
        policy_data = b"x" + b"\x00" * 70 + b"y\n"
        report = self.diagnose_file(policy_data, name="policy-70.bin")
        policy = report["codepointPolicy"]
        self.assertEqual(policy["violationCount"], 70)
        self.assertTrue(policy["runsTruncated"])
        self.assertEqual(len(policy["runs"]), 64)
        self.assertEqual(policy["classCounts"]["CONTROL_C0"], 70)
        self.assertEqual(policy["firstViolationByteOffset"], 1)
        self.assertEqual(policy["lastViolationByteOffset"], 70)

    # ---- mandatory audits (2) -----------------------------------------

    def test_audit_33_ast_no_shell_no_network_no_write(self):
        tool_path = os.path.join(_SCRIPT_DIR, "diagnose.py")
        with open(tool_path, encoding="utf-8") as handle:
            tool_tree = ast.parse(handle.read())
        plain_roots, from_roots, from_nodes = _collect_import_roots(tool_tree)
        self.assertEqual(
            plain_roots,
            {
                "argparse",
                "hashlib",
                "json",
                "os",
                "re",
                "stat",
                "sys",
                "unicodedata",
            },
        )
        self.assertEqual(from_nodes, 0)
        self.assertEqual(from_roots, set())
        os_attributes = _collect_attributes_of(tool_tree, "os")
        self.assertLessEqual(
            os_attributes,
            {
                "path",
                "pardir",
                "sep",
                "open",
                "read",
                "close",
                "fstat",
                "O_RDONLY",
                "O_CLOEXEC",
                "O_NOFOLLOW",
                "O_NONBLOCK",
            },
        )
        self.assertLessEqual(
            _collect_os_path_attributes(tool_tree),
            {"dirname", "realpath", "join"},
        )
        called = _collect_called_names(tool_tree)
        forbidden_calls = {
            "open",
            "eval",
            "exec",
            "compile",
            "__import__",
            "getattr",
            "setattr",
            "delattr",
            "globals",
            "locals",
            "vars",
            "breakpoint",
            "input",
        }
        self.assertEqual(called & forbidden_calls, set())

        test_path = os.path.join(_SCRIPT_DIR, "test_diagnose.py")
        with open(test_path, encoding="utf-8") as handle:
            test_tree = ast.parse(handle.read())
        test_plain, test_from, _ = _collect_import_roots(test_tree)
        forbidden_roots = {
            "subprocess",
            "socket",
            "ssl",
            "http",
            "urllib",
            "ftplib",
            "smtplib",
            "telnetlib",
            "xmlrpc",
            "asyncio",
            "requests",
            "pty",
            "ctypes",
            "multiprocessing",
        }
        self.assertEqual((test_plain | test_from) & forbidden_roots, set())
        self.assertLessEqual(
            test_plain,
            {
                "ast",
                "contextlib",
                "hashlib",
                "io",
                "json",
                "os",
                "shutil",
                "sys",
                "tempfile",
                "unicodedata",
                "unittest",
                "diagnose",
            },
        )
        test_os_attributes = _collect_attributes_of(test_tree, "os")
        forbidden_os = {
            "system",
            "popen",
            "fork",
            "forkpty",
            "execl",
            "execle",
            "execlp",
            "execlpe",
            "execv",
            "execve",
            "execvp",
            "execvpe",
            "spawnl",
            "spawnle",
            "spawnlp",
            "spawnlpe",
            "spawnv",
            "spawnve",
            "spawnvp",
            "spawnvpe",
            "posix_spawn",
            "posix_spawnp",
            "startfile",
        }
        self.assertEqual(test_os_attributes & forbidden_os, set())

    def test_audit_34_policy_refs_match_repository_redactor(self):
        self.assertEqual(diagnose.REDACT_PY_SHA256, PINNED_REDACT_PY_SHA256)
        self.assertEqual(
            diagnose.ALGORITHM_MANIFEST_SHA256,
            PINNED_ALGORITHM_MANIFEST_SHA256,
        )
        redaction_dir = os.path.join(REPO_ROOT, "scripts", "ui_dump_redaction")
        with open(os.path.join(redaction_dir, "redact.py"), "rb") as handle:
            self.assertEqual(
                _sha256_hex(handle.read()), diagnose.REDACT_PY_SHA256
            )
        with open(
            os.path.join(redaction_dir, "algorithm-v1.json"), "rb"
        ) as handle:
            self.assertEqual(
                _sha256_hex(handle.read()),
                diagnose.ALGORITHM_MANIFEST_SHA256,
            )
        report = self.diagnose_file(b"policy refs\n")
        self.assertEqual(
            report["policyRefs"],
            {
                "redactPySha256": PINNED_REDACT_PY_SHA256,
                "algorithmManifestSha256": PINNED_ALGORITHM_MANIFEST_SHA256,
            },
        )

    # ---- additive coverage beyond the pinned 32+2 ----------------------

    def test_extra_35_matrix_manifest_complete(self):
        self.assertEqual(len(PINNED_MATRIX), 34)
        for name in PINNED_MATRIX:
            self.assertTrue(
                hasattr(self, name), f"pinned matrix family missing: {name}"
            )

    def test_extra_36_empty_input_pure_function(self):
        report = diagnose.diagnose_bytes(
            b"",
            expected_sha256=_sha256_hex(b""),
            expected_length=0,
            tool_sha256=DUMMY_SHA256,
        )
        diagnose.validate_report(report)
        self.assertEqual(sum(report["byteHistogram"].values()), 0)
        self.assertTrue(report["utf8Structure"]["decodable"])
        self.assertEqual(report["utf8Structure"]["decileCounts"], [0] * 10)
        self.assertFalse(report["utf8Structure"]["tailConcentrated"])
        self.assertTrue(report["codepointPolicy"]["nfc"])
        self.assert_equivalent(report, "NONE", None)

    def test_extra_37_scanner_agrees_with_strict_codec(self):
        corpus = [
            b"",
            b"plain ascii\n",
            b"\xc2\x80",
            b"\xdf\xbf",
            b"\xe0\xa0\x80",
            b"\xed\x9f\xbf",
            b"\xee\x80\x80",
            b"\xf0\x90\x80\x80",
            b"\xf4\x8f\xbf\xbf",
            b"caf\xc3\xa9\r\n",
            b"\x80",
            b"\xbf\xbf",
            b"\xc0\xaf",
            b"\xc1\x81",
            b"\xc2",
            b"\xc2x",
            b"\xe0\x80\x80",
            b"\xe0\x9f\xbf",
            b"\xed\xa0\x80",
            b"\xed\xbf\xbf",
            b"\xe2\x82",
            b"\xe2\x82x",
            b"\xf0\x80\x80\x80",
            b"\xf0\x8f\xbf\xbf",
            b"\xf4\x90\x80\x80",
            b"\xf5\x80\x80\x80",
            b"\xf7\xbf\xbf\xbf",
            b"\xf8\x88\x80\x80\x80",
            b"\xfe",
            b"\xff\xfe",
            b"\xf0\x9f\x92",
            b"\xf0\x9f\x92x",
            b"a\x80\x80\x80b",
            b"mixed\xc0\xaf\xed\xa0\x80\xf4\x90\x80\x80tail\xe2\x82",
        ]
        for data in corpus:
            sequences, invalid_byte_count = diagnose._scan_utf8(data)
            decodable = True
            try:
                data.decode("utf-8")
            except UnicodeDecodeError:
                decodable = False
            self.assertEqual(
                not sequences,
                decodable,
                f"scanner/codec disagreement on {data!r}",
            )
            covered = sum(entry[1] for entry in sequences)
            self.assertEqual(covered, invalid_byte_count)
            self.assertLessEqual(invalid_byte_count, len(data))
            previous_end = -1
            for offset, length, entry_class in sequences:
                self.assertGreaterEqual(offset, 0)
                self.assertGreaterEqual(length, 1)
                self.assertLessEqual(offset + length, len(data))
                self.assertGreaterEqual(offset, previous_end)
                previous_end = offset + length
                self.assertIn(entry_class, EXPECTED_UTF8_CLASSES)


if __name__ == "__main__":
    unittest.main()
