//! Regenerate the App's offline presentation data with Runtime selection semantics.
#[cfg(any(target_os = "macos", windows))]
fn main() {
    let json = serde_json::to_string_pretty(&arkdeck_hoststore::flash_catalog_review()).unwrap();
    println!(
        "// Generated by: cargo run -p arkdeck-hoststore --example flash_catalog_review\n// Presentation data only; no materialized plan, availability or execution authority.\npublic enum FlashReviewCatalogGenerated {{\n  public static let json = #\"\"\"\n{json}\n\"\"\"#\n}}"
    );
}
#[cfg(not(any(target_os = "macos", windows)))]
fn main() {
    eprintln!("Generate the Flash App projection on macOS or Windows");
    std::process::exit(1);
}
