//! Regenerate the App's offline presentation data with Runtime selection semantics.
#[cfg(target_os = "macos")]
fn main() {
    let json = serde_json::to_string_pretty(&arkdeck_hoststore::flash_catalog_review()).unwrap();
    println!(
        "// Generated by: cargo run -p arkdeck-hoststore --example flash_catalog_review\n// Presentation data only; no materialized plan, availability or execution authority.\npublic enum FlashReviewCatalogGenerated {{\n  public static let json = #\"\"\"\n{json}\n\"\"\"#\n}}"
    );
}
#[cfg(not(target_os = "macos"))]
fn main() {
    eprintln!("Generate the macOS Flash App projection on macOS");
    std::process::exit(1);
}
