# capture.diagnostics@1 Trace-leg answers of the shared fake HDC, by mode.
# The probe's reads run concurrently, so each call appends its own line
# here (one append); the driver's log appends a call's arguments and its
# newline apart.
printf '%s\n' "$*" >> "$root/hdc-calls.log"
keys='aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb'
# The adopted device a call names, if it names one.
key=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
if [ "$1" = -t ]; then
  for adopted in $keys; do [ "$2" = "$adopted" ] && key=$adopted; done
fi
resources=$root/resources
# The devices' /data/local/tmp and trace ring, kept beside the log so that
# a Job's owned files outlive the calls that made them; every owned name
# carries its Job.
device() { printf '%s/device-tmp/%s' "$root" "${1#/data/local/tmp/}"; }
/bin/mkdir -p "$root/device-tmp"
umask 077
parameter() {
  case "$mode:$1" in
  ringNotHeld:persist.rosen.animationtrace.enabled)
    printf 'device offline\n'
    exit 1 ;;
  esac
  case "$1" in
  persist.ace.trace.syntax.enabled) printf 'false\n' ;;
  persist.ace.trace.layout.enabled) printf '%s = true\n' "$1" ;;
  persist.ace.trace.build.enabled) printf 'Get parameter "%s" fail! errNum is:106!\n' "$1" ;;
  persist.ace.trace.measure.debug.enabled) printf '%s=1\n' "$1" ;;
  persist.ace.trace.sync.debug.enabled) : ;;
  persist.ace.debug.enabled) printf '0\n' ;;
  persist.ace.performance.monitor.enabled) printf '\n  true  \n\n' ;;
  persist.sys.graphic.openDebugTrace) printf '1\n' ;;
  persist.rosen.animationtrace.enabled) printf 'false\n' ;;
  *)
    printf 'unregistered fixture parameter\n' >&2
    exit 24 ;;
  esac
}
case "$*" in
"list targets -v")
  for adopted in $keys; do
    printf '%s\t\tUSB\tConnected\tlocalhost\n' "$adopted"
  done ;;
"-t $key shell param get const.product.name")
  printf 'OpenHarmony Reference Device\n' ;;
"-t $key shell param get const.ohos.fullname")
  printf 'OpenHarmony-4.1-release\n' ;;
"-t $key shell param get "*) parameter "$6" ;;
"-t $key shell df -k /data/local/tmp")
  printf 'Filesystem 1K-blocks Used Available Use%% Mounted on\n'
  printf '/dev/block/data 1048576 1024 1047552 1%% /data\n' ;;
"-t $key shell hitrace --help") /bin/cat "$resources/hitrace-help.stdout.bin" ;;
"-t $key shell bytrace --help") /bin/cat "$resources/bytrace-help.stdout.bin" ;;
"-t $key shell hitrace -l")
  case $mode in
  tagListLost) printf '[Fail]ExecuteCommand need connect-key?\n' ;;
  afterTagListLost)
    if [ -e "$root/tag-list-read" ]; then
      printf '[Fail]ExecuteCommand need connect-key?\n'
    else
      : > "$root/tag-list-read"
      /bin/cat "$resources/hitrace-tags.stdout.bin"
    fi ;;
  *) /bin/cat "$resources/hitrace-tags.stdout.bin" ;;
  esac ;;
"-t $key shell pidof "*) printf '1234\n' ;;
"-t $key shell hilog -x") printf '01-01 00:00:00 I app: hello\n' ;;
"-t $key shell hidumper -s WindowManagerService -a -a") printf '{"windows":[]}\n' ;;
"-t $key shell hidumper -s WindowManagerService -a -w 7 -element -lastpage 42")
  printf 'WindowId: 7\nComponentId: 42\ntype: Button\ntext: Sign in\n' ;;
"-t $key shell hidumper -s 1201 -a -p Faultlogger -l")
  printf 'Fault log list:\n******\ncppcrash-com.example.demo-20010039-20260914000000\n******\n' ;;
"-t $key shell hidumper -s 1201 -a -p Faultlogger -f "*)
  printf 'Generated by HiviewDFX@OpenHarmony\nProcess name:%s\n' "${8##* }" ;;
"-t $key shell uitest dumpLayout -p /data/local/tmp/arkdeck-"*)
  printf '{"attributes":{"text":"Sign in"},"children":[]}\n' > "$(device "$7")"
  printf 'DumpLayout saved to:%s\n' "$7" ;;
"-t $key shell snapshot_display -t "*)
  printf '\211PNG\r\n\032\nIHDR still' > "$(device "$8")"
  printf 'process: display 0, file type: %s, width: 720, height: 1280\n' "$6" ;;
"-t $key shell hitrace -t "*)
  # The owned path is the last argument, after `-o`.
  for owned; do :; done
  case $mode in
  emptyTrace) : > "$(device "$owned")" ;;
  traceMissing)
    printf 'hitrace: capture failed\n'
    exit 1 ;;
  *)
    printf '# tracer: nop\n  hitrace-1 [000] ....  1.000000: tracing_mark_write: B|1|capture\n' \
      > "$(device "$owned")" ;;
  esac
  printf 'hitrace enter, running_state is RECORDING_SHORT_TEXT\n' ;;
"-t $key shell hitrace --trace_begin -b "*)
  : > "$root/device-ring"
  printf 'hitrace enter, running_state is RECORDING_LONG_BEGIN\n' ;;
"-t $key shell echo ARKDECKANCHOR"*)
  marker=${4#echo }
  printf '%s\n' "${marker%% *}" >> "$root/device-ring" ;;
"-t $key shell grep -c ARKDECKANCHOR"*)
  marker=${4#grep -c }
  if [ "$mode" = ringNotHeld ]; then
    printf '0\n'
  else
    /usr/bin/grep -c "${marker%% *}" "$root/device-ring"
  fi ;;
"-t $key shell sleep "*) : ;;
"-t $key shell hitrace --trace_dump -o /data/local/tmp/arkdeck-"*)
  {
    printf '# tracer: nop\n'
    while IFS= read -r line; do
      printf '  <...>-1 [000] ....  1.000000: tracing_mark_write: %s\n' "$line"
    done < "$root/device-ring"
  } > "$(device "$7")"
  printf 'hitrace enter, running_state is SNAPSHOT_DUMP\n' ;;
"-t $key shell hitrace --trace_finish_nodump")
  printf 'hitrace enter, running_state is RECORDING_LONG_FINISH_NODUMP\n' ;;
"-t $key shell ls -l /data/local/tmp/arkdeck-"*)
  if [ -f "$(device "$6")" ]; then
    printf '%s 1 shell shell %s 2026-09-14 00:00 %s\n' -rw-rw-rw- \
      "$(($(/usr/bin/wc -c < "$(device "$6")")))" "$6"
  else
    printf 'ls: %s: No such file or directory\n' "$6"
  fi ;;
"-t $key file recv /data/local/tmp/arkdeck-"*)
  /bin/cp "$(device "$5")" "$6"
  printf 'FileTransfer finish\n' ;;
"-t $key shell rm -f /data/local/tmp/arkdeck-"*)
  case $mode in
  cleanupRefused)
    printf 'rm: %s: Read-only file system\n' "$6"
    exit 1 ;;
  *) /bin/rm -f "$(device "$6")" ;;
  esac ;;
*)
  printf 'unregistered fixture output\n' >&2
  exit 23 ;;
esac
